### ISSUE TITLE
install 3rd party dependencies via yarn

### ISSUE THREAD

**Issue by graingert** [gchq/CyberChef#1]
Currently all 3rd party code is stored in https://github.com/gchq/CyberChef/tree/master/src/js/lib

It would be much easier to manage updates to these packages if they were declared in your package.json and installed via `yarn install` https://yarnpkg.com/

**Comment by n1474335** [comment]
Hi @graingert,

As discussed in #10 and #43, we're going to look at library management over the next few months. We will consider the use of yarn along with other options.
