### ISSUE TITLE
Bug report: Development does not work with current LTS (Node.js 12)

### ISSUE THREAD

**Issue by Prinzhorn** [gchq/CyberChef#1002]
**Describe the bug**

This is already known (#575, #662) but there is no issue to track this. More importantly https://github.com/gchq/CyberChef/wiki/Getting-started still says

> Install the latest LTS version of Node.js and its package manager, npm

which is wrong. I guess I don't have permission to edit the wiki, so updating this would save people like me some time in the future.

**To Reproduce**

Follow Getting Started with latest LTS (Node 12 not 10) and see `grunt dev` crash due to `mjs` stuff.

**Expected behaviour**

It should work with "the latest LTS version of Node.js". In the mean time the Wiki needs to be updated.

**Additional context**

@n1474335 says

> Yes, you must be using the current Node LTS to build CyberChef. There are some dependencies that don't support Node 12 yet. We'll update them as soon as they are fixed.

But which dependencies exactly are affected? Where is this tracked? I know of "crypto-api", PR is here https://github.com/nf404/crypto-api/issues/12

**Comment by n1073645** [comment]
It has been modified.

**Comment by Prinzhorn** [comment]
Thank you

**Comment by mt3571** [comment]
Would it be possible to update this to make it even more clear, or add a suggestion that if you are getting issues this could be the cause? As this is no longer a very recent version of Node people are likely to have other versions installed. See issue #1035 for another example of someone running into this.
