### ISSUE TITLE
Feature request: AAD in AES GCM mode

### ISSUE THREAD

**Issue by wumb0** [gchq/CyberChef#1008]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
AES Encrypt/Decrypt GCM mode does not support Additional Authenticated Data (AAD).

**Describe the solution you'd like**
Support for AAD in GCM mode.

**Describe alternatives you've considered**
Python cryptography or python cryptodomex. 

**Additional context**
GCM mode has an additional authenticated data feature that allows you to feed extra data into the cipher to be authenticated. Without support for this feature verification fails for ciphertext and encryption will output the incorrect tag when additional authenticated data is present. Either add the ability to include AAD or add a checkbox to ignore the tag. Preferably the former, but the latter would be a quicker fix.

**Comment by n1073645** [comment]
We use node-forge for AES, might be worth raising an issue on their repository for this feature.

**Comment by mattnotmitt** [comment]
> We use node-forge for AES, might be worth raising an issue on their repository for this feature.

You shouldn't be closing feature requests just because the current dependency we rely upon doesn't support it.

**Comment by n1073645** [comment]
Apologies, I will place this one on my to-do list. We are trying to tidy up the repository, this one was a mistake.
