### ISSUE TITLE
Jpath Expression Query Issue

### ISSUE THREAD

**Issue by prabhusrmist** [gchq/CyberChef#1019]
Issue in Domain Search Operation
* Tried to resolve multiple domains and used Jpath Query expressions to fetch name and data from the output. But the query is not working properly

**To Reproduce**
Steps to reproduce the behavior or a link to the recipe / input used to cause the bug:

![image](https://user-images.githubusercontent.com/63996021/79719553-74225d00-82fc-11ea-8f53-5e21506c1a47.png)

**Comment by n1073645** [comment]
We use dchester/jsonpath for this operation and it does not support this syntax. If we wanted to implement it into CyberChef we'd have to completely rewrite the library or use a different library which isn't a priority for us. 

It is probably worth raising an issue on their repository, we will then update our dependencies when they implement it.

I'll close this for now.

**Comment by brad** [comment]
As a workaround, I'm getting all the attributes, beautifying and then using "Filter" rules to cut out the attributes I don't want.
