### ISSUE TITLE
Feature request: i18n Internationalisation support for different languages 

### ISSUE THREAD

**Issue by l50741** [gchq/CyberChef#102]
### Summary
Detect the user language and display the application in that language.
More work might be required for RtL scripts.

### Possible solutions
There are plugins for grunt that exist that do this, but will depend on whether the content is static or dynamic.

e.g.: https://www.npmjs.com/package/grunt-i18n-static

**Comment by n1474335** [comment]
Duplicate, see #42.

I am working on a solution for this in #121.
