### ISSUE TITLE
RISON Operation

### ISSUE THREAD

**Issue by andyDemisto** [gchq/CyberChef#1023]
**Is your feature request related to a problem? Please describe.**
No problem, just a popular new library

**Describe the solution you'd like**
Add Rison encide/decode operations

https://observablehq.com/@nyurik/rison-online-decoder-encoder
https://github.com/Nanonid/rison/tree/master/js

**Comment by a3957273** [comment]
RISON is now supported.

**Comment by baphael** [comment]
Well, almost. RISON Decode operation is broken. The "decode option" dropdown contains 3 `undefined` options, and makes it unusable. Replacing l.31 `type: "editableOption",` with `type: "option",` should do the trick.
