### ISSUE TITLE
Bug report: Can't add iframe in source index.html

### ISSUE THREAD

**Issue by egwm** [gchq/CyberChef#1024]
**Describe the bug**
I am developing using `grunt dev`

If i insert an `<iframe />` into the document (I am trying to make it a child of `div#banner` the webpage will just cycle on the loading screen and never seems to load lower in the page.

I don't know how to get more debug info out of grunt on the cli, it doesn't report any errors or issues.

What I am trying to do is replace the banner with a custom header I am going to maintain in another file.

**To Reproduce**
Add in `iframe` in `src\web\html\index.html`, the page won't load

**Expected behaviour**
Page loads and allows me to use `iframe`

**Desktop (if relevant, please complete the following information):**
 - OS: Windows, CyberChef running in wsl
 - Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.158 Safari/537.36
 - CyberChef version: 9.20.3

**Additional context**
New to nodejs, just want to do some customization so we can intergate this tool on any internal project and self host.

**Comment by egwm** [comment]
I am able to inject an iframe using javascript within the `setup()` function, but it would be a lot cleaner to just have this be part of the HTML since its extra JS and it's requiring me to update JS in a few places (e.g., created a separate module).

**Comment by d98762625** [comment]
Hi @egwm, I don't think this is really a bug, it seems like you're editing the functionality of the application and as a result it won't work. Feel free to re-open if you disagree.

You can pass `--verbose` to any grunt command and it will give you some more output. Also you can look in the devtools on the browser and see if there's anything helpful in there?
