### ISSUE TITLE
Operation request: Argon2 Hashes

### ISSUE THREAD

**Issue by retnikt** [gchq/CyberChef#1028]
## Summary
[Argon2](https://en.wikipedia.org/wiki/Argon2) is a KDF and hash algorithm which won the Password Hashing Competition in 2015. A JavaScript implementation is [here](https://github.com/ranisalt/node-argon2). The reference C implementation is [here](https://github.com/P-H-C/phc-winner-argon2)
### Example Input
```
hunter2
```
### Example Output
```
$argon2id$v=19$m=16,t=2,p=1$OUtVaFRMRUJ2dkh4NGptVw$v0Rd0bFT22+ce7WTVfMp6g
```

**Comment by mattnotmitt** [comment]
This has already been requested in #608 and is pending merge in #661.

**Comment by retnikt** [comment]
Oh, sorry, must have typo'd in the search box

**Comment by mattnotmitt** [comment]
Ha! Me too, it would only find it if I typed in `argon2`, not `argon`.
