### ISSUE TITLE
From Hex To Dec does not work

### ISSUE THREAD

**Issue by scugn1zz0** [gchq/CyberChef#1029]
I create my recipe in which first element is "from hex" and second element is "To dec" and my input is: 0x1cda3c000, in decimal it is 7745028096, but CyberChef reports "28 218 60 0 0"
<img width="649" alt="Screen Shot 2020-05-04 at 1 47 10 PM" src="https://user-images.githubusercontent.com/14803862/80962678-c344b380-8e0d-11ea-8272-d4f5540c97be.png">

**Comment by n1073645** [comment]
The From Hex operation operates on bytes, in this case it operates on 1c, da, 3c, 00, 0 separately. The To Decimal operation will then operate on each of those bytes separately.

For the functionality that you are looking for I recommend using the From Base operation with radix 16.
https://gchq.github.io/CyberChef/#recipe=From_Base(16)&input=MHgxY2RhM2MwMDA
