### ISSUE TITLE
How to treat the output as a number?

### ISSUE THREAD

**Issue by leafcutterant** [gchq/CyberChef#1053]
## Summary
This is not strictly an operation request as there may be a way to achieve this; I just don't know how.

I want to treat a hash output value as a hexadecimal *number* and represent the number in standard base64. Values are handled by default as utf-8 so "To Base64" turns the text interpretation to base64, which is not appropriate for me. Neither can I achieve this with a "From Base" (16) and a "To Base" (64), because the maximum base this operation handles is 36. Even if it were 64, there's no option to specify which base64 alphabet is used so I can't be sure of the result.

I believe the higher-level need here is to be able to treat values as numbers and not utf-8 strings, thus my title. But I'm open to any suggestion.

### Example Input
`apple`
after a round of MD2:
`8015c9542cac74759f9f7196394cc25d`

### Current Output with "To Base64"
`ODAxNWM5NTQyY2FjNzQ3NTlmOWY3MTk2Mzk0Y2MyNWQ=`
(the frequency of the M/N/W characters alone tells you the value has been interpreted as utf-8)

### Desired output
`gBXJVCysdHWfn3GWOUzCXQ==`
(value generated with [this tool](http://tomeko.net/online_tools/hex_to_base64.php?lang=en))

**Comment by n1073645** [comment]
The way we have achieved this functionality in other operations was to add an input format argument. 

![image](https://user-images.githubusercontent.com/57447333/84996491-406d8300-b145-11ea-9555-9ae4c428726a.png)

Would this achieve your desired functionality?

**Comment by leafcutterant** [comment]
I don't know which operations have it so I couldn't try it yet, but yes, I think this would achieve the desired functionality.

**Comment by mattnotmax** [comment]
@leafcutterant if you need a really bad hack in the interim this recipe might suit. Essentially regexing the hash and the converting it back. I do like your idea. 

`[{"op":"MD2","args":[]},{"op":"Regular expression","args":["User defined","([A-Fa-f0-9]{2})",true,true,false,false,false,false,"List matches"]},{"op":"Find / Replace","args":[{"option":"Extended (\\n, \\t, \\x...)","string":"\\n"}," ",true,false,true,false]},{"op":"From Hex","args":["Space"]},{"op":"To Base64","args":["A-Za-z0-9+/="]}]`

**Comment by n1474335** [comment]
There's a reasonably simple solution to this by using From Hex and then To Base64: https://gchq.github.io/CyberChef/#recipe=MD2()From_Hex('Auto')To_Base64('A-Za-z0-9%2B/%3D')&input=YXBwbGU

From Hex will convert the hex string output by the MD2 operation to raw bytes. To Base64 then takes those bytes and represents them as Base64.

Since the Base64 operations are so central to CyberChef, I am wary of bloating them too much with excess options. I think in this case I will close the PR without merging, but thanks to @n1073645 for implementing a solution.
