### ISSUE TITLE
Feature request:  transposition / caesar box ciphers

### ISSUE THREAD

**Issue by chppppp** [gchq/CyberChef#1061]
**Is your feature request related to a problem? Please describe.**
There are no  transposition ciphers available to work with, unlike dcode.fr which does. 

**Describe the solution you'd like**
To be able to decode caesar box /  transposition ciphers. 

**Describe alternatives you've considered**
https://www.dcode.fr/caesar-box-cipher

**Additional context**
This code is unsolvable on cyberchef:

`yvheu vayen snioi ersor sletd nuccs ilill vaeef tltsv nikes avoia hneag nriti omsee dshog chzlt smvii twoii zyoio enaln ilsio ocsra byini onunb tglul saani felfe atetg ntxeo uatno shawh xlfnm idnsi ihexl tdonw lwsne lx`

Thanks!

**Comment by itpropaul** [comment]
Went to CyberChef to look for Caesar cipher encode/decode. Walked away sadly.

**Comment by mattnotmitt** [comment]
Caesar cipher is the same as the ROT-13 operation.

**Comment by itpropaul** [comment]
It encompasses other rotations as well. Such as only rotating 1 character.

**Comment by mattnotmitt** [comment]
Yes, if you tried the operation you would see that you can choose in the range 1-26

**Comment by itpropaul** [comment]
Okay, thanks. Seems like it's inappropriately named then.

**Comment by itpropaul** [comment]
At least we'll avoid this situation now https://xkcd.com/979/

**Comment by n1474335** [comment]
If you search for "caesar" in the operation search box, you'll see a few operations that might solve the problem for you. ROT13 is one (and if you hover over and read the description you'll see that the shift amount can be configured).

Another is the Substitute operation, which allows you to specify a full alphabet of substitutions. This means you aren't restricted to keeping the alphabet in order.

**Comment by n1474335** [comment]
Reopening since this is not the same as a Caesar Box Cipher
