### ISSUE TITLE
Bug report: Rail Fence should remove padding in decode

### ISSUE THREAD

**Issue by maqifrnswa** [gchq/CyberChef#1069]
**Describe the bug**
From https://github.com/gchq/CyberChef/pull/948#issuecomment-603343321
when decoding with rail fence, padding during decoding operation should be dropped.

**To Reproduce**

1. https://gchq.github.io/CyberChef/#recipe=Rail_Fence_Cipher_Encode(7,0)Rail_Fence_Cipher_Decode(7,0)&input=V0FGRkxFUzEyMw 

**Expected behaviour**
Symmetric encoding and decoding should return the same string. It works on other sites, just not cyberchef.

**Debugging/How to fix**
https://github.com/Flavsditz/CyberChef/blob/master/src/core/operations/RailFenceCipherDecode.mjs#L46

The problem comes when the `cipher` is padded with spaces. The decode algorithm then places the pads into the decoded text. The easiest way to fix this may be to make the pad symbols some escaped flag character that is removed later (like `\n` used in the example at https://www.geeksforgeeks.org/rail-fence-cipher-encryption-decryption). It can be done arithmetically, but I think it might get too complicated.

**Desktop (if relevant, please complete the following information):**
 - CyberChef version: 9.21.0

**Comment by maqifrnswa** [comment]
on closer examination, just removing the padding works. The algorithm doesn't need padding to decode! I'll make a pull request later

**Comment by Bihotz** [comment]
Nice work catching this. And go Enlightened!
