### ISSUE TITLE
chr() or char() to ascii

### ISSUE THREAD

**Issue by fkadriver** [gchq/CyberChef#1072]
For certain sql logs (see below) char(ASCII_CODE) or chr(ACSII_CODE) are used for obfuscation.  I have been unable to come up with a recipe to convert these.

(SELECT%20(**CHR(113)**%7C%7C**CHR(107)**%7C%7CCHR(122)%7C%7CCHR(98)%7C%7CCHR(113))%7C%7C(SELECT%20(CASE%20WHEN%20(8656%3D8656)%20THEN%201%20ELSE%200%20END))%3A%3Atext%7C%7C(CHR(113)%7C%7CCHR(120)%7C%7CCHR(113)%7C%7CCHR(122)%7C%7CCHR(113)))
(SELECT%20CHAR(113)%2BCHAR(107)%2BCHAR(122)%2B**CHAR(98)**%2BCHAR(113)%2B(SELECT%20(CASE%20WHEN%20(2131%3D2131)%20THEN%20CHAR(49)%20ELSE%20CHAR(48)%20END))%2BCHAR(113)%2BCHAR(120)%2BCHAR(113)%2BCHAR(122)%2BCHAR(113))

**Comment by n1474335** [comment]
This can be achieved with Subsection, From Charcode, and Find/Replace:

https://gchq.github.io/CyberChef/#recipe=Subsection('CHA?R%5C%5C((%5B%5E)%5D%2B)',true,true,false)From_Charcode('Space',10)Merge()Find_/_Replace(%7B'option':'Regex','string':'CHA?R%5C%5C((%5B%5E)%5D%2B)%5C%5C)'%7D,'$1',true,false,true,false)URL_Decode()&input=KFNFTEVDVCUyMChDSFIoMTEzKSU3QyU3Q0NIUigxMDcpJTdDJTdDQ0hSKDEyMiklN0MlN0NDSFIoOTgpJTdDJTdDQ0hSKDExMykpJTdDJTdDKFNFTEVDVCUyMChDQVNFJTIwV0hFTiUyMCg4NjU2JTNEODY1NiklMjBUSEVOJTIwMSUyMEVMU0UlMjAwJTIwRU5EKSklM0ElM0F0ZXh0JTdDJTdDKENIUigxMTMpJTdDJTdDQ0hSKDEyMCklN0MlN0NDSFIoMTEzKSU3QyU3Q0NIUigxMjIpJTdDJTdDQ0hSKDExMykpKQooU0VMRUNUJTIwQ0hBUigxMTMpJTJCQ0hBUigxMDcpJTJCQ0hBUigxMjIpJTJCQ0hBUig5OCklMkJDSEFSKDExMyklMkIoU0VMRUNUJTIwKENBU0UlMjBXSEVOJTIwKDIxMzElM0QyMTMxKSUyMFRIRU4lMjBDSEFSKDQ5KSUyMEVMU0UlMjBDSEFSKDQ4KSUyMEVORCkpJTJCQ0hBUigxMTMpJTJCQ0hBUigxMjApJTJCQ0hBUigxMTMpJTJCQ0hBUigxMjIpJTJCQ0hBUigxMTMpKQ
