### ISSUE TITLE
Feature request: JSON to Grid Like Visual 

### ISSUE THREAD

**Issue by rams3sh** [gchq/CyberChef#1075]
**Is your feature request related to a problem? Please describe.**
I have always found unstructured JSON to be little tricky to visualize especially to people  (non techie people) who are not familiar with the format. Though every json can be processed in a custom fashion and displayed , but it would be neat to have a generic JSON visualizer. 

**Describe the solution you'd like**
I am looking for a solution that can make the json look like a grid such as [here](https://jsongrid.com/). 

Sample Image below :-
![image](https://user-images.githubusercontent.com/5143597/88478456-15f1bf80-cf66-11ea-8dec-8940ec3502a6.png)

**Describe alternatives you've considered**
I have considered normalising unstructured JSON to a csv or a table to have a neat understandable  format , however the side affect being having lot of redundant columns for each row.

**Additional context**
None

**Comment by n1073645** [comment]
We have a To Table operation already. 
It transforms:
{
    "a": 1,
    "b": 2,
    "c": 3
}

Into:
![image](https://user-images.githubusercontent.com/57447333/88816865-c523d600-d1b4-11ea-9187-9f84fde506cc.png)

You do first have to convert the JSON into CSV format so the To Table operation can read it.
Does this achieve the functionality you are looking for?

**Comment by rams3sh** [comment]
It does !!! Thanks !!!  Didnt check my bad.


I think if  https://github.com/gchq/CyberChef/issues/1076 is done .
```
Unstructured JSON -> CSV -> To Table 
```
should achieve this.
