### ISSUE TITLE
Operation request: Unicode strikethrough 

### ISSUE THREAD

**Issue by themacguffinman** [gchq/CyberChef#1082]
## Summary

Can be useful for sites or forums that don't have strikethrough formatting. Not urgent or important, just wanted to note it down as a tool I have used before. Eg. https://adamvarga.com/strike/

### Example Input

strike it like its hot

### Example Output

s̶t̶r̶i̶k̶e̶ ̶i̶t̶ ̶l̶i̶k̶̶e̶ ̶i̶t̶s̶ ̶h̶o̶t

**Comment by themacguffinman** [comment]
Uh, I just realized this project is made by the actual GCHQ intelligence agency for data analyst work, while this operation is for shitposting. Feel free to close.

**Comment by mattnotmitt** [comment]
@themacguffinman I see your shitposting and raise you a PR :)

**Comment by themacguffinman** [comment]
Thank you, it's more than I could ask for!

**Comment by n1474335** [comment]
M̶̲e̶̲r̶̲g̶̲e̶̲d̶̲
