### ISSUE TITLE
Feature request: Support Six-bit Character Codes (Punchcard, Magnetic Stripe, Braille)

### ISSUE THREAD

**Issue by OscarVanL** [gchq/CyberChef#1091]
**Is your feature request related to a problem? Please describe.**
Six-bit character codes were used in punchcard and magnetic stripe cards for representing a small subset of BCD / ASCII characters.

They are also used in Braille codes.

This [Wikipedia page](https://en.wikipedia.org/wiki/Six-bit_character_code) includes a number of encoding techniques, including CDC1604 Magnetic/Punchcard, CDC1612 Printer codes, DEC SIXBIT, ECMA-1, ICL Mainframes, GOST, and Braille codes.

In addition, attempts so far of using "from binary" to decode 6-bit values have been difficult, I suspect because the tool expects 8-bit values patterns currently.

**Describe the solution you'd like**
The option for 6-bit encodings could be added in the Encoding section and explored in the Magic decoding tool.

**Additional context**
This feature request is to assist in solving a yet-unsolved hidden message in the Halo 3 ODST videogame. This game has been out 11 years and there is an unsolved Easter Egg involving [a number of banners](https://halo.wikibruce.com/images/8/8c/ODST-J-Signs.jpg) suspected to encode a hidden message.

[Members of the community theorise](http://www.gruntspajamas.com/forum/index.php?topic=228.60) the banners, when stacked on top of each other, encode 6-bit characters. Further exploration would be made much easier with these decoding techniques in the CyberChef tool.

**Comment by n1073645** [comment]
I have added arguments to both the ToBinary and the FromBinary operations now, contained in #1087 
It should cover this.

**Comment by OscarVanL** [comment]
That's great. Thanks
