### ISSUE TITLE
Bug report: magic doesn't work on mobile devices 

### ISSUE THREAD

**Issue by Darkcast** [gchq/CyberChef#1099]
**Describe the bug**
While using an android device and chrome if you choose magic you cannot to select the intensive mode or depth 
Also the 

**To Reproduce**
Use chrome select magic try to check the intensive mode check box or select a depth.

**Comment by n1474335** [comment]
We don't support mobile devices at the moment. If the mobile version is ever released it will support Magic. Closing for now.
