### ISSUE TITLE
Bug report: <Help Hyperlink for File Extract points to dead website>

### ISSUE THREAD

**Issue by scotdewerth** [gchq/CyberChef#1101]
**Describe the bug**
When attempting to find out about the Extract Files feature, a user may select the File Carving hyperlink to the ForensicWiki.org website address https://forensicswiki.org/wiki/File_Carving.

As of 2019, the ForensicWiki.org website has been unavailable after the company that acquired it abandoned it.  As of December 2019, this website is available at a different location or on the Internet Archives Wayback machine.

**To Reproduce**
Steps to reproduce the behavior or a link to the recipe / input used to cause the bug:

1. Go to Forensics tab
2. Mouse over 'Extract Files'
3. Click on hyperlink 'File Carving'
4. See error "This site can't be reached'

**Expected behavior**
Information on File Carving.

**Additional context**
A hyperlink to the new site is available at https://forensicswiki.xyz/wiki/index.php?title=File_Carving

or alternatively, a wikipedia page about File Carving could be displayed
https://en.wikipedia.org/wiki/File_carving

**Comment by n1474335** [comment]
Thanks for reporting this, and thanks to @manicgiraffe for implementing the fix!
