### ISSUE TITLE
Bug report: Incorrect Week number in "Parse DateTime"

### ISSUE THREAD

**Issue by EdgeSync** [gchq/CyberChef#1106]
**Describe the bug**
When using the Parse DateTime function, the Week number returns the Year value, not the current week number.

**To Reproduce**

- Drag "Parse DateTime" into Recipe Field

- In Input enter a date time in the specified format of the recipe (i.e. International date and time: 2020-01-01 01:01:01

- See value of "Week Number" in output is 2020

**Expected behaviour**
Should return a value between 1-52 depending on the week the date was in.

**Screenshots**
![image](https://user-images.githubusercontent.com/15020931/93686542-ce436c00-faae-11ea-9703-873b129c548d.png)

**Desktop (if relevant, please complete the following information):**
- OS: Linux Mint 19
 - Browser: Firefox 80.01
 - CyberChef version:  9.21.0

- OS: Windows 10 x64 19-09
- Browser: Chrome 85.0.4183.102
 - CyberChef version:  9.21.0

**Additional context**
Tried on github instance, and local instance:
https://gchq.github.io/CyberChef/#recipe=Parse_DateTime('Standard%20date%20and%20time','DD/MM/YYYY%20HH:mm:ss','UTC')&input=MDEvMDEvMjAyMCAwNjozMDoxMg

**Comment by mattnotmitt** [comment]
Duplicate of #1084

**Comment by EdgeSync** [comment]
Closing as duplicate.
