### ISSUE TITLE
Feature request: LZ4 compression support

### ISSUE THREAD

**Issue by kotori2** [gchq/CyberChef#1116]
**Is your feature request related to a problem? Please describe.**
Recently I'm debugging a program which compress input with LZ4 compression, but CyberChef doesn't support it.

**Describe the solution you'd like**
Add lz4 compress/decompress.

**Describe alternatives you've considered**
There are alternatives for most languages such as [this](https://python-lz4.readthedocs.io/en/stable/)

**Additional context**
N/A

**Comment by wdpless** [comment]
Excellent feature request. I'm doing something similar with firefox and believe lz4 would speed up my analysis. Thanks for all you have done with this project!!!

**Comment by n1474335** [comment]
LZ4 compression and decompression operations have been added in v9.49.0
