### ISSUE TITLE
Question: problem with AES-CBC decryption with Base64 input

### ISSUE THREAD

**Issue by dehqan** [gchq/CyberChef#1118]
Hi,

I have a problem with decoding from base64 and AES-CBC.

The problem is some of the characters from beginning of the output is not decoded.
is there anything that I've missed?

Input(Base64): 
`zZYksTFC3xS8415+Vg0Mu9Xa0TeTo+ndVi0jueSxsVjA1HXxewU+fKtkU2Gu53zA+RtlstITVO2JKkcIH1H48A==`

Key:
`55555555555555555555555555555555`

IV:
`0000000000000000`

Mode:
`CBC`

Input & Output type:
`Raw`

Output:
`K.CDQDEC.
.ubb.b_GENERIC","status_det":"INVALID_INPUT"}`

but it should be:
`{"status":"ERROR_GENERIC","status_det":"INVALID_INPUT"}`

in the live demo try this:

https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)AES_Decrypt(%7B'option':'UTF8','string':'55555555555555555555555555555555'%7D,%7B'option':'UTF8','string':'0000000000000000'%7D,'CBC','Raw','Raw',%7B'option':'Hex','string':''%7D)&input=elpZa3NURkMzeFM4NDE1K1ZnME11OVhhMFRlVG8rbmRWaTBqdWVTeHNWakExSFh4ZXdVK2ZLdGtVMkd1NTN6QStSdGxzdElUVk8ySktrY0lIMUg0OEE9PQ

It works fine on [here](https://encode-decode.com/aes-256-cbc-encrypt-online/)
select supported encryptions as: aes-256-cbc
and try decrypt: 
`zZYksTFC3xS8415+Vg0Mu9Xa0TeTo+ndVi0jueSxsVjA1HXxewU+fKtkU2Gu53zA+RtlstITVO2JKkcIH1H48A==`

with the key:
`55555555555555555555555555555555`

**Comment by mattnotmax** [comment]
It looks like the IV is required to be in hex for this to work: 
![image](https://user-images.githubusercontent.com/39072319/97945301-3b029380-1ddb-11eb-8fcb-b9e1eb995bae.png)
