### ISSUE TITLE
Feature request: Extract hashes

### ISSUE THREAD

**Issue by kulbozz** [gchq/CyberChef#1125]
**Is your feature request related to a problem?**
Similar to the "Extract IP Address" function, I find myself often getting unstructured logs that has file hashes that I'd like to easily be able to extract for further processing and analysis. I've tried a regex and it's not dependable for larger data sets.

**Describe the solution you'd like**
Ability to extract MD5, SHA1, and SHA2 from desperate, unstructured data.

**Describe alternatives you've considered**
Regular expression is not dependable.

**Comment by n1474335** [comment]
Duplicate of #466
