### ISSUE TITLE
Bug report: Haversine Distance has incorrect output

### ISSUE THREAD

**Issue by mattnotmax** [gchq/CyberChef#1141]
**Describe the bug**
Haversine distance operation appears incorrect

**To Reproduce**
Comparing similar JavaScript from https://andrew.hedges.name/experiments/haversine/ is appears that the CyberChef implementation of haversine distance is not correct.

Examples:
Same Lat/Long should produce 0 distance:

![image](https://user-images.githubusercontent.com/39072319/101346371-8c230d00-38dc-11eb-9770-348451948a3d.png)

![image](https://user-images.githubusercontent.com/39072319/101346125-39495580-38dc-11eb-93ed-ede960e8266c.png)

Different Lat/Long does not produce correct distance:

![image](https://user-images.githubusercontent.com/39072319/101346398-95ac7500-38dc-11eb-9dca-55f7b0caec6f.png)

![image](https://user-images.githubusercontent.com/39072319/101346417-9c3aec80-38dc-11eb-8e1a-cd6e051d447a.png)

**Desktop (if relevant, please complete the following information):**
* Version: 9.21.0
* Compile time: 12/06/2020 11:52:36 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Haversine_distance()Convert_distance('Metres%20(m)','Kilometers%20(km)')&input=LTM4LjEsIDE0NC42LCAtMzguMSwgMTQ0LjQ)

**Additional context**
Thanks!

**Comment by mattnotmax** [comment]
Ah, so I'm definitely not a JS anything but I think the values are not being parsed

```
        const lat1 = parseFloat(values[1]);
        const lng1 = parseFloat(values[3]);
        const lat2 = parseFloat(values[6]);
        const lng2 = parseFloat(values[8]);
```
Should be 


```
        const lat1 = parseFloat(values[1]);
        const lng1 = parseFloat(values[3]);
        const lat2 = parseFloat(values[5]);
        const lng2 = parseFloat(values[7]);
```

**Comment by n1474335** [comment]
Good spot! Thanks for raising this, and thanks very much to @mattnotmax for sorting it out.
