### ISSUE TITLE
Bug report: <Error while loading to webpage>

### ISSUE THREAD

**Issue by reyabel** [gchq/CyberChef#1143]
Uncaught SyntaxError: Unexpected token ';'
Filename: blob:http://icyberchef.com/4b117850-5ed8-4808-acc7-27f82dd08ae1
Line: 1010
Column: 57316
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
CyberChef version: 9.12.0

**Comment by mt3571** [comment]
Hi, could you give some more information about how to reproduce this? The link you have provided doesn't seem to work for me. What recipe had you written for this to occur?
