### ISSUE TITLE
Bug report: "Unsupported browser" error when using supported browsers

### ISSUE THREAD

**Issue by valdaarhun** [gchq/CyberChef#1147]
**Describe the bug**
Though I have the latest versions of cyberchef, firefox and chrome, when I try to run `grunt dev`, I get an "unsupported browser" error.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Follow installation procedure given in the wiki pages.
2. Run `grunt dev` in the terminal.
3. Go to localhost on port 8080.

**Expected behaviour**
Expected to see cyberchef running successfully on localhost.

**Screenshots**
Firefox window
![Screenshot from 2020-12-21 19-27-04](https://user-images.githubusercontent.com/39989901/102785591-3d896e80-43c4-11eb-9032-ba1adfc41f95.png)

Chrome window
![Screenshot from 2020-12-21 19-26-41](https://user-images.githubusercontent.com/39989901/102785582-3b271480-43c4-11eb-8ebc-75a7c1907e59.png)

Terminal window
![image](https://user-images.githubusercontent.com/39989901/102785046-4e85b000-43c3-11eb-98cd-99af58ce941a.png)

**Desktop (if relevant, please complete the following information):**
 - OS: Ubuntu  18.04.5 LTS
 - Browser: Chrome Version 87.0.4280.88, Firefox Version 84.0 (64-bit)
 - CyberChef version: V9.21.0

**Comment by causeImCloudy** [comment]
What node version are you running?

**Comment by valdaarhun** [comment]
> What node version are you running?

I am using v15.4.0

**Comment by causeImCloudy** [comment]
running the dev version only works in node 10. I was having the same problem and used Pythons virtual node environment to install the LTS of node 10, heres the docs i used on to get it set up and running. 
https://pypi.org/project/nodeenv/

It appears it may also be possible to install multiple versions of node and specify the running version according to this website. https://heynode.com/tutorial/install-nodejs-locally-nvm

**Comment by valdaarhun** [comment]
@causeImCloudy  I created a virtual node environment and installed node v10.19.0. However, this gives me a new compilation error whenever I run `grunt dev`. I tried running `node rebuild node-sass` but that doesn't solve the problem. It says it might be because the environment changed after running `npm install`. But I don't understand how to correct this issue.

![Screenshot from 2021-01-21 13-57-54](https://user-images.githubusercontent.com/39989901/105324214-24f1bb80-5bf1-11eb-806b-ed6a99abb34f.png)

**Comment by mattnotmitt** [comment]
Please could you try deleting your node_modules and then npm install - there might just be some build artefacts lying around

**Comment by valdaarhun** [comment]
Hi. I am sorry for the extremely late response. I thought I would try and install this from scratch and it worked like a charm. As suggested by causelmCloudy, I created a virtual node environment and installed node-10.24.1. With this, the installation ran smoothly and `grunt dev` no longer gives errors.

Thanks @causeImCloudy  and @mattnotmitt for helping me out!
