### ISSUE TITLE
Drag and drop from operation not working

### ISSUE THREAD

**Issue by Tzion0** [gchq/CyberChef#1153]
I trying to drag the "Magic" from operation to recipe but it doens't work. it only work when i refresh the website plus only work once. (Means i can't add more than ONE recipe).

Cyberchef version : 9.21
Browser: Firefox 83.0

**Comment by n1474335** [comment]
Seems to be working ok for me. I'll close this for now since no one else is reporting the same thing but if anyone else is having this issue, comment here and we will reopen it.
