### ISSUE TITLE
BUG: Possible misnaming of XOR Output Differential and perhaps input differential (9.7.9)

### ISSUE THREAD

**Issue by j3dw4rds** [gchq/CyberChef#1155]
Hi, I was working to re-implement a CyberChef recipe in python as I am decrypting some strings; part of the encryption fell away as I used the XOR output differential recipe option (I'm on 9.7.9 so this may be fixed) however,

When I implemented output differential in python, the decryption didn't work. After some testing, the CyberChef operation actually appears to be doing XOR input differential. The following screenshot should elaborate. If it were output differential, the 5th byte in the output, 0xe9, should be 0xf2^0xc7, which would be 0x35. Instead, it's 0xf2^0x1b. This shows the key is the previous unprocessed byte, AKA input differential. 
![xor](https://user-images.githubusercontent.com/25807782/103581456-0d54cc00-4eaa-11eb-8fb8-f1bab042a12e.PNG)

**Comment by n1474335** [comment]
You're absolutely right. I had the input and output differential logic swapped. This has now been fixed in v9.32.3. Thanks for spotting and raising this!
