### ISSUE TITLE
Bug report: UI broken with Firefox 84.0.2 on Fedora 33

### ISSUE THREAD

**Issue by MandyFIS** [gchq/CyberChef#1157]
**Describe the bug**
UI is broken on latest vanilla Fedora33/Firefox 84.0.2 versions (with no Add Ons/Extensions). 

UI throws the following error in the console:

Uncaught TypeError: o[s].querySelector(...) is null
    value https://gchq.github.io/CyberChef/assets/main.js:464
    value https://gchq.github.io/CyberChef/assets/main.js:459
    value https://gchq.github.io/CyberChef/assets/main.js:459
    value https://gchq.github.io/CyberChef/assets/main.js:464
    value https://gchq.github.io/CyberChef/assets/main.js:464
    value https://gchq.github.io/CyberChef/assets/main.js:464
    L/</k[n]< https://gchq.github.io/CyberChef/assets/main.js:20
    setTimeout handler*L/< https://gchq.github.io/CyberChef/assets/main.js:20
    value https://gchq.github.io/CyberChef/assets/main.js:464
main.js:464:4506

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Enter any input into the input pane. 
2. Drag any recipe into the recipe window. For example, 'To Hex'.
3. Error is thrown in web console when Auto Bake is selected, or when Bake is clicked.
4. Following the thrown exception, the recipe pane becomes unusable and recipes cannot be added nor removed. (Including via the clear recipe button)

**Expected behaviour**
Output.

**Screenshots**

**Desktop (if relevant, please complete the following information):**
 - OS: Fedora 33
 - Browser: 84.0.2 (64-bit)
 - CyberChef version: 9.21.0

**Additional context**
* Version: 9.21.0
* Compile time: 12/06/2020 12:53:19 UTC
* User-Agent:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
* [Link to reproduce](https://gchq.github.io/CyberChef/#input=null)

**Comment by n1474335** [comment]
Closing since no one else is reporting the error. Comment here if you are seeing the same thing and we will reopen.
