### ISSUE TITLE
Misc:Is CyberChef support RSA?

### ISSUE THREAD

**Issue by SuperMaskv** [gchq/CyberChef#1160]
I can't find anything titled "RSA" in menu. Is CyberChef support RSA ?

**Comment by mattnotmitt** [comment]
PR #652 has been pending for a little while, should hopefully be merged soon now that @n1474335 has returned

**Comment by mt3571** [comment]
If you are just looking to generate an RSA key pair, this can already be done by using the `Generate PGP Key Pair` operation. If you are looking for something more complex it would be worth checking out @mattnotmitt's branch and trying to run things locally, the instructions for how to do that can be found [here](https://github.com/gchq/CyberChef/wiki/Getting-started).

**Comment by SuperMaskv** [comment]
@mattnotmitt @mt3571  thx guys

**Comment by n1474335** [comment]
#652 has now been merged.
