### ISSUE TITLE
Unzip Operation returning unknown BTYPE:3 error

### ISSUE THREAD

**Issue by Cyber00011011** [gchq/CyberChef#1161]
**Describe the bug**
Unzipping a malware sample from virusshare.com returned a compression.js unknown BTYPE: 3 error

**To Reproduce**
I was looking at a malware sample referenced in this post:
https://twitter.com/DidierStevens/status/1353751902354350086

I found the sample on virusshare by searching for the hash and when loaded into CyberChef it produced an error. Spot checked a couple other sample from virusshare and some unzipped fine, and some others gave the same error as well.

![Capture](https://user-images.githubusercontent.com/78022701/105851707-5b597d00-5fdb-11eb-8fa8-c729bde05179.PNG)

**Comment by n1474335** [comment]
We use zlib.js for our Unzip operation and this is a problem in that library. I'll close this issue for now since there isn't much we can do in CyberChef to solve it without moving to an entirely different library or implementing zlib from scratch (not a priority at the moment).
