### ISSUE TITLE
Rail fence decode does not appear to work as expected

### ISSUE THREAD

**Issue by alblue** [gchq/CyberChef#1163]
**Describe the bug**

Text created with the 'Rail Fence Encode' does not appear to be decodable with 'Rail Fence Decode' with the same key and offset.

**To Reproduce**

Click on https://gchq.github.io/CyberChef/#recipe=Rail_Fence_Cipher_Encode(3,0)Rail_Fence_Cipher_Decode(3,0)&input=Sm9sbHlCcm9rZW4 to load it in the simulator, or alternatively:

1. Add a *Rail Fence Encode* with key 3 and offset 0
2. Add a *Rail Fence Decode* with key 3 and offset 0
3. Enter "JollyBroken" into the encode
4. The output does not contain "JollyBroken" but rather "JorlyBnoke l"

**Expected behaviour**

When using the same cipher to encode and decode data, I would expect to see the plaintext in the result unchanged.

**Screenshots**
<img width="918" alt="Screenshot 2021-01-31 at 21 54 31" src="https://user-images.githubusercontent.com/76791/106399303-bc37e980-640f-11eb-8bd7-be14b3bb208f.png">

**Additional context**
Taken on the version on the website at time of raising bug, 

Version 9.21.4
Compile time: 22/01/2021 19:00:54 UTC

**Comment by alblue** [comment]
What's odd is that the input length is 11; if the decode is a key length of 2 then the length is 11, but if the key length is 3 then the decode length is 12 and an extra space appears.

If I use "JollyBroken " with a space afterwards, the decode works as expected.

**Comment by mt3571** [comment]
Could #1069 be related to your problem? If so, there is a pull request in to fix that so if you are building locally you could try and apply those changes 🙂 #1108 may also be related

**Comment by alblue** [comment]
It’s the same issue as #1108 but I don’t know that #1069 will solve the problem. When encoding “JollyBroken” it gets displayed as “JykolBoelrn” with no spaces, but although the output of encode says “Length: 11” for the text, it also says “Length: 12” for the output of the cipher, which I suspect is where the space is coming from.

Simply deleting spaces isn’t going to fix the problem — if you type “JykolBoelrn” (no spaces) into a Rail Fence decode with key 3, it produces the incorrect output whether or to the space is there in the output. The issue seems to be that the decode is ‘rounding up’ the length of the string (11) to the nearest multiple of the key (12) which then affects the algorithm.

**Comment by mt3571** [comment]
I have just run #1071 against this example and it works. The PR is removing the rounding in the decode operation and so no additional spaces are being introduced, so the right output is achieved. Please let me know if you find any examples that this doesn't fix! 🙂

**Comment by alblue** [comment]
Yup, looks like #1071 will fix this issue as well.

**Comment by alblue** [comment]
BTW this came up because one of the questions in https://www.ncsc.gov.uk/cyberfirst/girls-competition uses a rail fence encoding and my daughter found this issue in CyberChef. Reproduced here with a different example so as not to give the game away :)

**Comment by n1474335** [comment]
This should be closed by #1071

**Comment by alblue** [comment]
This works now on the website as of the build an hour ago
