### ISSUE TITLE
Latest releases?

### ISSUE THREAD

**Issue by Prinzhorn** [gchq/CyberChef#1164]
In the last 24 hours there have been a couple of releases, mostly done by github-actions.
Can someone explain what's up with that? There has been no update to https://github.com/gchq/CyberChef/blob/master/CHANGELOG.md and the releases don't contain any notes.

**Comment by n1474335** [comment]
Apologies for not updating the CHANGELOG, that's my mistake. I will rectify that.

I have been merging a bunch of PRs recently so the versions have been bumping. We go up a new minor version when new operations are added and a new patch level when bugs are fixed or small new features are implemented. Have a look at the [commit history](https://github.com/gchq/CyberChef/commits/master) if you want a detailed log (although I accept that this can be confusing!).

**Comment by Prinzhorn** [comment]
Thanks for clarifying!
