### ISSUE TITLE
Bug report: CyberChef encountered an error while loading.

### ISSUE THREAD

**Issue by zer-far** [gchq/CyberChef#1165]
**Describe the bug**
Error: Cannot find module './config/modules/OpModules.mjs'
Filename: blob:https://cyberchef.abdullah.cloud/80d6c055-130f-4f76-a36c-95acd9f9f27a line 220 > eval
Line: 8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
CyberChef version: 9.23.1

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Go to 'https://cyberchef.abdullah.cloud'

**Expected behaviour**
I expected CyberChef to load.

**Screenshots**

**Desktop:**
 - OS: Manjaro XFCE
 - Browser: FireFox 85.0
 - CyberChef version: 9.23.1

**Comment by mt3571** [comment]
What version of Node are you using? This can sometimes happen if you are using a version higher than v10 (see #575).

**Comment by zer-far** [comment]
I am using Node v12.16.1.
