### ISSUE TITLE
Bug report: Possibly incorrect Year on latest Changelog entries

### ISSUE THREAD

**Issue by aussieklutz** [gchq/CyberChef#1168]
**Describe the bug**
The latest two version tags in the changelog cite 2020 instead of 2021

**To Reproduce**
1. Review the changelog
2. Profit

**Expected behaviour**
2021 on the latest two changelog entries

**Screenshots**
NA

**Desktop (if relevant, please complete the following information):**
NA

**Additional context**
NA

**Comment by n1474335** [comment]
Good spot! Thanks for raising this.
