### ISSUE TITLE
Bug report: Checkbox state not shown on macOS/Safari

### ISSUE THREAD

**Issue by alblue** [gchq/CyberChef#1172]
Checkboxes (such as 'auto bake') do not show whether they are selected or not on Safari on macOS Bug Sur (11.2).

This shows the state of 'auto bake' when navigating to the home app:
<img width="369" alt="before selecting" src="https://user-images.githubusercontent.com/76791/107271512-4271b280-6a44-11eb-8fb0-fc2c004c9d75.png">

This shows the image after clicking on 'auto bake' so that it is selected:
<img width="368" alt="after selecting" src="https://user-images.githubusercontent.com/76791/107271541-4dc4de00-6a44-11eb-98cb-bf97d3689aef.png">

Checking into the HTML suggests that the input type is indeed checked:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/76791/107271654-74831480-6a44-11eb-9b5b-7a6d6b42914b.png">

Images captured with build 6b10f61e11b357bc429753af2a9f11f4c7f68f2a

**Comment by n1474335** [comment]
This looks like a problem with [Bootstrap Material Design](https://github.com/mdbootstrap/bootstrap-material-design) which is the library we use for the UI. It could be worth raising this on their repository and we'll pull any updates through as they are made.

Safari is not technically one of our [supported browsers](https://github.com/gchq/CyberChef/blob/master/package.json#L33). I would recommend using Chrome or Firefox instead.

**Comment by alblue** [comment]
Looks like the checkbox works in the V5 bootstrap on Safari.

**Comment by n1474335** [comment]
We use a modified version of Bootstrap that implements Material Design. It is still on v4.
