### ISSUE TITLE
Feature request: Multiple regex

### ISSUE THREAD

**Issue by atheus13** [gchq/CyberChef#1175]
I'm trying to use regex to pull multiple items from a report, but I can't seem to get it to work.
For example if I have the input:
Cows moo
Sheep baa
Cats meow

I'd like to have use regex operations pull (Cows)[A-z]{0,10} and (Cats)[A-z]{0,10}. Then I might try find and replace to only keep the end, or the sound in this example.

Thanks.

**Comment by mattnotmax** [comment]
With capture groups perhaps?

`Regular_expression('User defined','^(?:Cows|Cats)\\s([a-zA-Z]{1,100})',true,true,false,false,false,false,'List capture groups')
`

**Comment by atheus13** [comment]
Awesome, thank you!
