### ISSUE TITLE
Bug report: Save recipe button broken

### ISSUE THREAD

**Issue by mattnotmax** [gchq/CyberChef#1176]
**Describe the bug**
Seems that the 'save recipe' icon button for web-based versions of CyberChef no longer works. A locally saved copy brings up the save box while the web version doesn't. 

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

Click save icon in the recipe pane. Nothing happens

**Expected behaviour**
Save recipe box should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/39072319/107931804-e32a1a00-6fd0-11eb-93ec-363ad2b4b4e9.png)

vs

![image](https://user-images.githubusercontent.com/39072319/107931833-efae7280-6fd0-11eb-9e08-a3208ec48fc6.png)

**Desktop (if relevant, please complete the following information):**
I've tried on Firefox/Chrome/Edge with same results. 

**Additional context**
It might be me? Seems weird. Thanks for taking a look.

**Comment by DiegoTheWolf** [comment]
Same problem here, just a quick add:
You get this error in Chrome, when clicking on it.
<img width="316" alt="2021-02-15 19_55_48-Remove whitespace, From Hex, Gunzip - CyberChef" src="https://user-images.githubusercontent.com/12967418/107984298-ef5da980-6fc7-11eb-8454-c64f5195546f.png">

**Comment by sganson-tss** [comment]
Not sure if this is related (or just me) or not, but the “highlights” functionality wasn’t working on the latest build; e.g. To/From Base64 Input and Output.

Following the code in Firefox Web Console shows pos[0] is undefined.

[cid:image001.png@01D703A5.F2EA2F80]

Sebastian
