### ISSUE TITLE
Operation request: <Working with hundreds or thousands of find / replace functions.>

### ISSUE THREAD

**Issue by SalviaSage** [gchq/CyberChef#1177]
## Summary
Hi there. I am trying to create what are called "automatic transliterators".
The idea is, you type or paste a text written in another script, and they get turned into certain specified characters of the Unicode.

### Example Input
हालाँकि सूर के जीवन के बारे
### Example Output
haːlaŋkɩ suːɹ ke ʓɩːvan ke baːɹe

As can be seen in the example, depending on what we are working with we may need hundreds of separate find / replace functions, which gives us a very long URL and long wait times on loading. the last time I tried this, the whole page would freeze after reaching something like 300-400 find / replace functions.

Desiring to develop such tools, I thought CyberChef would be the perfect tool for the job. I still think it is.
Sadly, I can't develop what it is that I am trying to do. I know it wasn't necessarily designed for this task but since it does exist,
perhaps it can be used for this friendly, academic task.

Otherwise, it would take so much more programming before I can even get anywhere.
Do you have any suggestions for me?

Thank you.

**Comment by mt3571** [comment]
Where do you get the translations from? Would any of the options in `DecodeText` operation work for you?

**Comment by n1474335** [comment]
For something like this where single characters are being replaced, the 'Substitute' operation would probably be more suitable: https://gchq.github.io/CyberChef/#recipe=Substitute('ABCDEFGHIJKLMNOPQRSTUVWXYZ','XYZABCDEFGHIJKLMNOPQRSTUVW')

Which languages would you want to see transliterated? This may be worth a dedicated operation.

**Comment by SalviaSage** [comment]
Thank you for letting me know of the substitute operation.

I can see that this is a powerful operation and it is what I was looking for.
However, I have some questions regarding "Warning: Plaintext and Ciphertext lengths differ"

Do they have to be the same length and why so?
Sometimes I may have to replace one letter with two letters.
In what way is this a problem? The find and replace operation does not give that warning.

**Comment by n1474335** [comment]
If you need to replace one letter with two letters, the Substitute operation won't work for you unfortunately. It is really intended as a kind of Caesar cipher, where you find the current letter in the plaintext string, and then substitute it for the character at the same position in the ciphertext string. That's why they need to be the same length.

I am not against creating a number of dedicated transliteration operations. Which languages are of interest?

**Comment by SalviaSage** [comment]
In the example above, I am dealing with a syllabary alphabet.
That means, every letter represents a syllable, which gives us many different, possibly thousands of different combinations.

Transliterating from a syllabary alphabet to a non-syllabary alphabet means one letter has to become 2 or more letters.

For example (1 letter): च्चा is supposed to become ʆʆa

if I do च्चा = ʆ it gives  me ʆ्ʆा
If I do च्चा = ʆʆ (which seems to be the right thing to do) it gives me ʆʆʆा

So, I get an extra output that I am not supposed to get.
And those circles that you see is because there is an inherent vowel that is present there within the च्चा .

This is one area in computational linguistics where there is potential, but not much is done I think due to its complexity,
I can't do it either as you see.

CyberChef just can't account for this kind of thing appropriately. It's not its fault, but perhaps it can handle this kind of thing
better in the future.
