### ISSUE TITLE
Bug report: Missing validation in "From Binary" option

### ISSUE THREAD

**Issue by yoyrandao** [gchq/CyberChef#1178]
**Describe the bug**
Negative byte length in "From Binary" operation

**To Reproduce**
Steps to reproduce:

1. Go to 'From Binary'
2. Enter some binary text
2. Set byte length to a negative value
3. Wait

**Expected behaviour**
Problem in the **src/core/lib/Binary.mjs**. Loop iterator goes to wrong value, that causes wrong substring extraction

**Screenshots**
![image](https://user-images.githubusercontent.com/35937082/108734855-f002bc80-7540-11eb-9603-1ddacf1ac9ae.png)

![image](https://user-images.githubusercontent.com/35937082/108734245-52a78880-7540-11eb-8fef-4a49de0dcaf5.png)

**Desktop (if relevant, please complete the following information):**
 - OS: Windows
 - Browser: Edge 88.0.705.74
 - CyberChef version:  9.27.3

**Comment by n1474335** [comment]
Thanks for raising this. I've fixed it both by preventing the user from entering a value lower than `1`, and by adding a check in the function that throws an exception if the value is invalid. I also found a couple of other places that had the same issue so I've fixed them as well.
