### ISSUE TITLE
Thing

### ISSUE THREAD

**Issue by AstroOrbis** [gchq/CyberChef#1188]
I actually started writing something EXACTLY LIKE THIS in python (AstroOrbis/PuzzleHacker)! I was just wondering if I should just implement my python code into pull requests here...

**Comment by mt3571** [comment]
New contributions are welcome!🙂  Most of the code is in Javascript here, and you can checkout the [issues](https://github.com/gchq/CyberChef/issues) to see specifically what needs implementing.

**Comment by AstroOrbis** [comment]
Thanks! I'll work on my python version on my [repo](github.com/AstroOrbis/PuzzleHacker)...
