### ISSUE TITLE
Bug report: sanitisation concern leading to self-persistent XSS

### ISSUE THREAD

**Issue by ys-240417** [gchq/CyberChef#119]
Hi @n1474335 and team,

First, thanks for releasing CyberChef on GitHub – it's a very useful toolkit.

I came across a sanitisation issue while exploring recipe save/load functionality, which at present can lead to self-persistent XSS. Just wanted to check if it's okay to proceed with reporting here.

**Comment by n1474335** [comment]
Hi @ys-240417, thanks very much for getting in contact. If you'd like to send me the details in an email (n1474335@gmail.com) then I'll roll out a patch asap. We can post the details in this thread after it's been fixed.

**Comment by yasinS** [comment]
@n1474335 Sent a Markdown-formatted email four minutes ago detailing the full issue, along with information regarding my GitHub accounts. Thanks!

**Comment by ys-240417** [comment]
@n1474335 Sent a Markdown-formatted email five minutes ago detailing the full issue, along with information regarding my GitHub accounts. Thanks!

**Comment by n1474335** [comment]
Taking a look now.

**Comment by n1474335** [comment]
Thanks very much for reporting this @ys-240417. As you explained in your email, it isn't possible to trigger the XSS with a crafted URL string as it relies on the recipe name, however it's still a bug and needed fixing. Versions from 5.2.1 onward include the fix. Please let us know if you find anything else.

The details as provided by @ys-240417 were as follows:

## Steps to reproduce
1. Set up a new CyberChef recipe, then select **Save Recipe**
2. Populate the **Recipe Name** field with the following: `'"><Img src=x onerror=confirm(localStorage.favourites)>`
3. Finally, select the **Save** option

#### Success modal (via output)
In the first instance, the JavaScript payload will execute upon clicking **Save**. This is rendered in the DOM as follows:

```
<span id="alert-content">[2:11:39 PM] Recipe saved as "'"&gt;<img src="x" onerror="confirm(localStorage.favourites)">".</span>
```

#### Recipe loading (via localStorage)
Furthermore, the `savedRecipes` key in Local Storage is updated upon saving the Recipe. As such, the JavaScript payload will persist and execute when the user selects **Load Recipe**. An example savedRecipe key is:

```
[{"id":14,"name":"'\"><Img src=x onerror=confirm(localStorage.favourites)>","recipe":"[]"}]
```

The `load-name` form element is rendered in the DOM as follows:

```
<select class="form-control" id="load-name"><option value="14">'"&gt;<img src="x" onerror="confirm(localStorage.favourites)"></option></select>
```

## Affected source
The aforementioned issues can be traced to this snippet from [ControlsWaiter.js](https://github.com/gchq/CyberChef/blob/master/src/web/ControlsWaiter.js):

```
[...]
/**
 * Saves the recipe specified in the save textarea to local storage.
 */
ControlsWaiter.prototype.saveButtonClick = function() {
    var recipeName = document.getElementById("save-name").value,
        recipeStr  = document.getElementById("save-text").value;

    if (!recipeName) {
        this.app.alert("Please enter a recipe name", "danger", 2000);
        return;
    }

    var savedRecipes = localStorage.savedRecipes ?
            JSON.parse(localStorage.savedRecipes) : [],
        recipeId = localStorage.recipeId || 0;

    savedRecipes.push({
        id: ++recipeId,
        name: recipeName,
        recipe: recipeStr
    });

    localStorage.savedRecipes = JSON.stringify(savedRecipes);
    localStorage.recipeId = recipeId;

    this.app.alert("Recipe saved as \"" + recipeName + "\".", "success", 2000);
};

[...]
```

## Environment
The following tests were conducted with:

* Windows 7 x64
* Latest stable Chrome build (57.0.2987.133)
