### ISSUE TITLE
Bug report: Brave browser cannot drag-and-drop operations

### ISSUE THREAD

**Issue by atoponce** [gchq/CyberChef#1196]
**Describe the bug**
The Brave browser cannot drag-and-drop operations into the recipe column. They can be double-clicked. However, operations in the recipe cannot be reordered without removing the operations, and double-clicking them in the correct order in Brave.

**To Reproduce**

1. Go to https://gchq.github.io/CyberChef
2. Paste "Q3liZXJDaGVm" into the Input
3. Try to drag-and-drop the "From Base64" operation into the recipe
4. The "From Base64" operation does not drop into the recipe box.

**Desktop (if relevant, please complete the following information):**
 - OS: Debian Linux, unstable
 - Browser: Brave 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
 - CyberChef version: 9.28.0

**Comment by mt3571** [comment]
As Brave is not listed as one of the [supported browsers](https://github.com/gchq/CyberChef#browser-support) I don't think this is a bug. It might be a good feature request to support this browser though!

**Comment by atoponce** [comment]
Fair enough. If I can find some time, I'll look into it, and see if I can find the problem and submit a PR. Seeing that Brave is just using Blink with V8 like Chrome, I would *expect* that they would behave differently, but perhaps the Brave developers have made some changes that would be causing the difference here.

**Comment by n1474335** [comment]
I'll close this since we don't officially support Brave, but if anyone wants to spend the time to make it work and submit a PR we would be happy to merge it.
