### ISSUE TITLE
Bug report: TypeError: i[s].querySelector(...) is null

### ISSUE THREAD

**Issue by trondd555** [gchq/CyberChef#120]
### Summary
With Auto Bake enabled and dragging a new operation into the recipe, a TypeError is thrown.
TypeError: i[s].querySelector(...) is null

### Example

This does not happen with Auto Bake disabled nor when manually running Bake after.

This seems to have been introduced in release 5.1.2

Release 5.1.1 does not throw this error.

Replicated with FIrefox 53, 45.8.0 ESR and Chrome 57.0.2987.133
Also replicated in both a self-hosted release and the live demo.

**Comment by n1474335** [comment]
Thanks very much for raising this, it has now been fixed.
