### ISSUE TITLE
Bug report: CyberChef flags Windows Defender SmartScreen

### ISSUE THREAD

**Issue by dsmackie** [gchq/CyberChef#1210]
**Describe the bug**
Navigating to https://gchq.github.io/CyberChef/ results in a Windows Defender SmartScreen warning. This was not the case a couple of days ago. Suspect it is a Microsoft issue so reporting for visibility.

**To Reproduce**
Navigate to https://gchq.github.io/CyberChef/

**Expected behaviour**
CyberChef loads without warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/48046804/121822154-abac4f80-ccdc-11eb-89bf-1fa2ac22f66b.png)

**Desktop (if relevant, please complete the following information):**
 - OS: Windows
 - Browser: Edge - 91.0.864.48 (Official build) (64-bit)
 - CyberChef version: 9.28.0

**Additional context**
http://icyberchef.com/ has the same warning.

**Comment by sebastianganson** [comment]
Haters gonna hate.

From the MSFT Defender SmartScreen FAQ
  Click the link for More information then click Report that this site does
not contain threats. Follow the instructions on the feedback site to
complete this process.

**Comment by dsmackie** [comment]
Submitted feedback at the time of appearance as suggested by the warning. One man can make a difference!

But it probably needs more clicks 😁
