### ISSUE TITLE
Feature request: Ability to force every character to be encoded into utf-7

### ISSUE THREAD

**Issue by maple3142** [gchq/CyberChef#1221]
**Is your feature request related to a problem? Please describe.**
Current utf-7 encoder will not encode ascii characters into utf-7, I think there should be an option to force every character to be encoded.
Example: `+AEg-+AGU-+AGw-+AGw-+AG8-+ACA-+AFc-+AG8-+AHI-+AGw-+AGQ-+ACE-` is a valid utf-7 representation of `Hello World!`, but using CyberChef's utf-7 encoder only gets `Hello+ACA-World+ACE-`.

**Describe the solution you'd like**
Add an option to `Encode Text` if encoding is utf-7.

**Describe alternatives you've considered**
Have an new operation dedicated for encoding text into utf-7 with more settings, because there a may ways to represent a string in utf-7.

**Additional context**
utf-7 is useful when you need to bypass some filtering using character encoding.

**Comment by n1474335** [comment]
I think what you're trying to achieve is actually decoding from UTF-7 rather than encoding into it, which gives the desired result: https://gchq.github.io/CyberChef/#recipe=Decode_text('UTF-7%20(65000)')&input=K0FFZy0rQUdVLStBR3ctK0FHdy0rQUc4LStBQ0EtK0FGYy0rQUc4LStBSEktK0FHdy0rQUdRLStBQ0Ut

**Comment by JorianWoltjer** [comment]
This feature is still missing, they are talking about *encoding* plain text into UTF-7. I am also facing the same issue in CyberChef.
It would be useful to be able to encode every character into UTF-7, even if not strictly necessary by the standard. Decoders will often decode any characters and similar to URL-encoding, this can allow for some filter bypasses.
