### ISSUE TITLE
Bug report: npm install --save cyberchef failled

### ISSUE THREAD

**Issue by QKSword** [gchq/CyberChef#1227]
**I want to use Node API，but ”npm install --save cyberchef“ face the problem**

`npm ERR! cyberchef@9.27.6 postinstall: npx grunt exec:fixCryptoApiImports`
`npm ERR! Exit status 3`

environment：System：ubutun:20.04.2；nodejs：v10.19.0；npm：6.14.4

**Comment by n1474335** [comment]
Duplicate of #1166
