### ISSUE TITLE
Bug report: Replace module, ---  \. cannot  dot

### ISSUE THREAD

**Issue by wgf4242** [gchq/CyberChef#1231]
**Describe the bug**
Replace `\.` cannot match `.`

Version 9.21.0

![Snipaste_2021-08-07_15-47-26](https://user-images.githubusercontent.com/3336626/128593037-a3821640-1680-4746-8b2e-90a4993374a4.png)

**Comment by mattnotmax** [comment]
Hey @wgf4242 , based on the above I'm guessing that this data is encoded (perhaps UTF-16 LE). Which means the `.` isn't actually a dot but a representation of data that doesn't have a printable character. 

CyberChef can find/replace and regex `.` 

![image](https://user-images.githubusercontent.com/39072319/130779304-4e7b83c3-3898-4c06-9b95-98d44ee8ee3c.png)

But if the data is something like UTF-16 then this regex won't work: 

![image](https://user-images.githubusercontent.com/39072319/130779440-224b89eb-a273-460a-920c-2625eb6a8e93.png)

You can see the difference if you use hexdump and view a row of `.` which have been converted to UTF-16 LE. Here the `.` is 0x20 and there is a 0x00 inserted as part of the encoding. 

![image](https://user-images.githubusercontent.com/39072319/130779721-b7b7be0d-c8fb-4cb7-8e39-3b5a2f77da4d.png)

Let me know if I've misunderstood!

**Comment by n1474335** [comment]
@mattnotmax is correct here. Some potential solutions would be to use 'Encode text' or 'Decode text' with the correct character encoding selected (probably UTF16 by the looks of it), or a quick hack might be to use 'Remove null bytes' which often has the same effect. It's not quite as "correct" though!
