### ISSUE TITLE
Feature request: Size in bytes of an input

### ISSUE THREAD

**Issue by Sim4n6** [gchq/CyberChef#1235]
Is there a way to count the number of bytes/characters in an input text ? 

count the characters for instance while omitting "\n" or with "\r\n".  

count characters in hexa for instance combined to hex ....

**Comment by n1474335** [comment]
Yes, you can either look at the length indicator on the top right of the input box which gives you the total number of characters, or you can use the 'Count occurrences' operation which takes a regex. Here's an example that counts everything that isn't a newline: https://gchq.github.io/CyberChef/#recipe=Count_occurrences(%7B'option':'Regex','string':'%5B%5E%5C%5Cn%5D'%7D)&input=VGVzdAoxMjMKSGVsbG8KV29ybGQ
