### ISSUE TITLE
NEED CRYPTO PADDING OPTIONS

### ISSUE THREAD

**Issue by b1gcat** [gchq/CyberChef#1237]
Sometime I see java code :
` Cipher.getInstance("AES/CBC/PKCS5Padding");`

i try use cc to decrypt, but it only support pkcs7padding.

so it's possible to support padding options?

**Comment by n1474335** [comment]
Duplicate of #416.

Also, there's no need to shout :)

**Comment by Burgerd4sh** [comment]
Now the newest version is v10.19.2
I still can't find PKCS5Padding support, and all issues that mentioned this problem have been closed.
Does anyone know why?
