### ISSUE TITLE
Feature request: Shifting characters in a string

### ISSUE THREAD

**Issue by itsaphel** [gchq/CyberChef#1248]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to shift characters in a string. e.g. say you have a string `def`, and you want to shift this with an offset of -4 to `abc`.

**Describe the solution you'd like**
A function to shift characters in a string.

**Comment by mt3571** [comment]
This feature already exists as part of the ROT13 operation - [here](https://gchq.github.io/CyberChef/#recipe=ROT13(true,true,false,-3)&input=ZGVm) is a recipe that shows how to do it :)

**Comment by n1073645** [comment]
As mentioned by @mt3571 this functionality is already implemented. I will close this issue.
