### ISSUE TITLE
Feature request: Reverse Defang Domain/IP

### ISSUE THREAD

**Issue by milannshrestha** [gchq/CyberChef#1249]
**Is your feature request related to a problem? Please describe.**
CyberChef has helped me in my research and analysis with Defanging the domain/IPs, but for the bulk inputs, reverse defang operations seem missing. 

**Describe the solution you'd like**
Add Reverse Defang / "Fang".

**Describe alternatives you've considered**
Been doing manually but for the bulk inputs, adding a new operation is a must, imo.

**Additional context**
anexample[.]com -> anexample.com
A[.]B[.]C[.]D -> A.B.C.D

**Comment by mt3571** [comment]
Does the find/replace operation work for this, or do you need something more complicated? [Here](https://gchq.github.io/CyberChef/#recipe=Find_/_Replace(%7B'option':'Simple%20string','string':'%5B.%5D'%7D,'.',true,false,true,false)&input=YW5leGFtcGxlWy5dY29t) is an example of what I mean

**Comment by milannshrestha** [comment]
Oh Yes! Thank. 

But a separate op would be nice. :D
