### ISSUE TITLE
Feature request: To/From Octal like BurpSuite

### ISSUE THREAD

**Issue by ruant** [gchq/CyberChef#1253]
I can't find a method of being able to do the same `Octal` transformation as how BurpSuite does it.

BurpSuite:
Original text: `5257356a62325270626d6367513268686247786c626d646c`
Octal encoded: `24034214a720270024142d541357471232250253552c1162d1206c`
Looks like Burp only touches the digits, not chars.

CyberChef:
Original text: `5257356a62325270626d6367513268686247786c626d646c`
`To Octal` encoded: `65 62 65 67 63 65 66 141 66 62 63 62 65 62 67 60 66 62 66 144 66 63 66 67 65 61 63 62 66 70 66 70 66 62 64 67 67 70 66 143 66 62 66 144 66 64 66 143`
https://gchq.github.io/CyberChef/#recipe=To_Octal('Space')&input=NTI1NzM1NmE2MjMyNTI3MDYyNmQ2MzY3NTEzMjY4Njg2MjQ3Nzg2YzYyNmQ2NDZj

Would be nice to be able to have the option to have both options.
Or am I just using the wrong operation?

**Comment by mikecat** [comment]
Try this for this specific case:

[Subsection, To Base - CyberChef](https://gchq.github.io/CyberChef/#recipe=Subsection%28%27%5B0-9%5D%2B%27,true,true,false%29To_Base%288%29&input=NTI1NzM1NmE2MjMyNTI3MDYyNmQ2MzY3NTEzMjY4Njg2MjQ3Nzg2YzYyNmQ2NDZj)
