### ISSUE TITLE
Cannot extract .webp file

### ISSUE THREAD

**Issue by Anonymous2716** [gchq/CyberChef#1274]
I have tried extracting images from a .PCAP file and pasting raw data. This tool successfully extracts other image types but how do I extract .WEBP files. It's not in the file extracting description too. TIA

**Comment by n1073645** [comment]
Hello,

For the WEBP signature, the extractor is currently null as there isn't currently an extractor implemented for it [https://github.com/gchq/CyberChef/blob/ae1b12c1208365eefa9f556ba91f0cebfdf28857/src/core/lib/FileSignatures.mjs#L73](url). A quick glance at the header seems to suggest that the file size is stored in the header so it shouldn't be a complex extractor.

I will open a Feature Request issue for you to make sure it gets done.

**Comment by Anonymous2716** [comment]
Thanks it should be great to have more useful features.

**Comment by Anonymous2716** [comment]
I am having issues installing cyber chef using npm. Where can I find the file signatures in the zip version that I can just download?

**Comment by n1073645** [comment]
Hello,

The path of FileSignatures.mjs in the zip is CyberChef-master -> src -> core -> lib -> FileSignatures.mjs

**Comment by Anonymous2716** [comment]
Actually I'm talking about the zip that I downloaded from cyber chefs demo page.

**Comment by n1073645** [comment]
Unfortunately FileSignatures.mjs is not in that zip.

It is present in the zip you can download from this repository on the main page under "code".

**Comment by Anonymous2716** [comment]
I know thanks.

**Comment by Anonymous2716** [comment]
Haven't fiend the solution so reopened.

**Comment by Anonymous2716** [comment]
Thanks for implementing Webp extraction. Reading the code as far as I understand is by reading the file size in the header it extracts. I just want to know which encoding is that file size of that 4 bytes? How do I compare to to the file size originally in disk?
