### ISSUE TITLE
Gunzip - invalid file signature

### ISSUE THREAD

**Issue by furier** [gchq/CyberChef#1278]
**Describe the bug**
Gunzip - invalid file signature:72,52

but https://codebeautify.org/gzip-decompress-online is perfectly able to gunzip the string. 🤷‍♂️

**To Reproduce**

[Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Gunzip()&input=SDRzSUFBQUFBQUFBQ3MxYTIyN2JPQkQ5RnowN0J1OGk5V1lrdlFHYnk5WnBIN3BZTEZTSlRiU1ZKYTlFdGMwRytmY2QraUk3TWUyU2tMRjFFYUMyZUVTZkdjN01FVFY4akQ3cSt5SXI5YnM4U2lnV2FoVGROSFdtMjFibnQ4Vk1SMGxFRU1GbkdKOFJmb3R4UW1WQzZaamltRExGUGtXajZMWkpzOFhkMFp0NWV3azNwbmY2YlZybHBXNysraExuaEdDZW55R0UrUm5Mc3V4TWFvVE9Qb3M4SXpubmltVXBUREUxcWRHWGFYWmZWSHJ4R1NhN2JZbzVEUDJXbXNKME9Wemhhb3c0RnBUVDFUOFlyS3U3OWVoWUVmZ1JSRGVqTjNWYm1LS3ViaC9tZHNJM045TUZXNWcyZVZ6OGIwa0x6T0F1SkViUkpEUEZOMzJ4L1BVdG14RktGbi9XMXZONk5rK3JoNnR1OWxrMzRDOUVSdEdWL21HbXBwNVA5VCtkcmpMTFpYTng0WmVyNmZ2azl5NTlTSmlrU3NFMEY3cE1INkpFQXRDQzJpajU0ekhhaFlNMWlNWFdQNnVwcjV2Yy9peUdLOW05enJ0UzU1T21LYjZscFh1cCtJcDJqNzdRODdReFhhTVA0dzlPQ3I3QVl5R0ZvRWhhOEUvbnBHUXNJTEE0alQ5RlR5T1hvU3dtak8zYVNYenRGSUYycnZFSEo0MFRCbllxeENuMnNSUGdITnpDQ2VGcXI1MEtFN1JySi8zRmRuSXhodFZVR0NzUE95WE1PUmFjeFRHbWUrMFVTRG5zWkw1MnhvRjJydkVISjVVSmxtQm5yQ1R5czVQQWVvbzRSb3pzdFhPVnp5L3M1UCtyblZWWGxqdlcySXQ3T01QS09YSk5uRFRubUdGSEhZeDlPY3RBenZJWW5Ea1hmSmV6UEduT0VuRkgzcXFUNWh4TDZmQXpScjZrVlNCcGRaVGdvTXFSaE5oWDJSa0pJOTNqaDVHV1NqaEkrOG8wbzRHazZWRkNXaXJzSU8ycnVZd0ZrbVpIaVdrbFhhUjlCWlFGUHZqMStJR2VkaVlpUDJuU1RDSHBJQzFPbWpSbmpEcEkrK29oQzlUd0hqL00wN0JsY0pEMkZVUWVtSWc5ZmdocGpJaVFydmp3bFVRZUdCLzhPSmxJdWFOOEVGOUo1SUh4d1k4VUg5enhMRTM4Sk5IcVd3anBMZndnMHJDZGNEd3dFVDlKQkJJNGtEUStEbWxKSEtUOUpCRklCRDE4Yk9HSGtuYW9DL0dUUkdBUTlQQ3hoUjlHbW1CSG9TWitrZ2drZ2piOFcvaWhwRjB4N1NlSlFDSm9GN0NGSDByYXNVTWs4VW1UWnRJWkhuNlNTRUNkd2tqMytHSGl3cFdyZXZncElwQUlUTVFlUHl3OEtIV1FwbjZLQ0NRQ0U3SEhEeU1OcjdvZHBIMFZFUWZHZEk4ZlJocUMya0hhVnhGeDBIWjhDejl3TzQ0YzIzSGJSRGh0MGk1UCt5b2lDYXdlUFg0WTZkaTFDNkQ4cEVsTDVsSkU2cXVJSkxEazlmaUJubzRkT3hmcXE0Z2thTCsxaFI5R0dnbFhuZlpWUkJKWXAzdjgwRTBpY3dXMXJ5U1N3UExSNHdmR2gzU29DL09WUk5zSERDSGQ0ejFKL3drTjNOVGNyOXJCcm9idGRXVUJVV0thVHR0ZWNHdnM5NGxaejdxNXNta2k3NHhzT3NqTElYdjV2YzdxcXRLWmdXWncydCtUdHVZeU5kWllhSkQvRGFQd1lkVmh0dngyRzlXVUVLSTRVc3JScUVaWVlWZ0FxQ3NRMm0vcnB2aTNya3hhVHJLc2czWTY5SWFqcS9RS25QVlJONmJJSEFQVHVkWjUvKzI4N3BwVzkxL2Z0UitxcjFYOUhZaDlTY3NXdkRNcDErd1drS2VsUGRDd0IxdnVHbWphZjVqbk81M3ZWYmNmMnJmd1FwSXJiRmR2amJlYlhNckdERkV3RWQ2UkNNYkZNeWR0dDhUdHVvRXNuWGROb3l2emNtVFh2M2JkdHdDS0F0OXBNZXRLOEhGZDlTR3hjZjl5Q2pEbi9GNW5YK2QxVVpubG1oeVlzL2NoRTJObTN3Y1BPR3B3bmRjemJXeitvREVra0x0eDhOeVZUNy9RbDNaOHVlRDU0aWpDUHI2SWpTSFZZbVViNEUvTFF3MlR0aTN1cWhuODlMT2taSWlBVDhqUFQxSFkwRFdRN000YTBiOUllbFc1RHA5UWVKbThBT3h3V1JsejZNQUNncGIxc3NGdHJiY0hPVXBZc2R4YTRQNjFyWkpsNzRDaW9NR3lmSFBJeFRyZ1JRaXQ4NURhcDdERElYTXcybDRYUDVhblZwYWZvV0NYaFlIa0J3ZnZITmU1ME4rSzFRRWNLZWxyTnBGS01mWEtPaHJZMlBNbzBSMGNNUmxGbDdVdDAvWnJCVEUzaW15Wmc2Sy8vNWpQODJoOTVnVHc5dmYwNFhER09QQUhQUEwwSHpjYXVTeUtKQUFB)

**Expected behaviour**

```
{"VehicleId":3169,"ProcessedTime":"2021-11-25T11:38:33.3173494Z","TraceId":"GpsMessageHandler_f7d2215d-0015-4ccc-8e00-b6dc2d5594ca","StateMachineState":"Trip","Latitude":59.05163533333333,"Longitude":5.920010333333333,"PositionType":"GPS","Trip":{"TripId":61401006,"ActiveDate":"2021-11-25T00:00:00Z","CompanyNumber":302,"NextStopSequence":5,"NextStopId":"NSR:Quay:48399","Delay":85,"Stops":[{"StopId":"NSR:Quay:103047","SequenceOrder":1,"ScheduledArrivalTime":"2021-11-25T11:35:00Z","ScheduledDepartureTime":"2021-11-25T11:35:00Z","ArrivalTime":"2021-11-25T11:30:01.6866308Z","DepartureTime":"2021-11-25T11:35:32.6169537Z"},{"StopId":"NSR:Quay:47244","SequenceOrder":2,"ScheduledArrivalTime":"2021-11-25T11:36:00Z","ScheduledDepartureTime":"2021-11-25T11:36:00Z","ArrivalTime":"2021-11-25T11:37:41.6905318Z","DepartureTime":"2021-11-25T11:37:45.6852259Z"},{"StopId":"NSR:Quay:49120","SequenceOrder":3,"ScheduledArrivalTime":"2021-11-25T11:36:00Z","ScheduledDepartureTime":"2021-11-25T11:36:00Z","ArrivalTime":"2021-11-25T11:37:56.6639119Z","DepartureTime":"2021-11-25T11:38:00.6547713Z"},{"StopId":"NSR:Quay:46090","SequenceOrder":4,"ScheduledArrivalTime":"2021-11-25T11:37:00Z","ScheduledDepartureTime":"2021-11-25T11:37:00Z","ArrivalTime":"2021-11-25T11:38:18.6679809Z","DepartureTime":"2021-11-25T11:38:25.6677042Z"},{"StopId":"NSR:Quay:48399","SequenceOrder":5,"ScheduledArrivalTime":"2021-11-25T11:37:00Z","ScheduledDepartureTime":"2021-11-25T11:37:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:44774","SequenceOrder":6,"ScheduledArrivalTime":"2021-11-25T11:37:00Z","ScheduledDepartureTime":"2021-11-25T11:37:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:47417","SequenceOrder":7,"ScheduledArrivalTime":"2021-11-25T11:38:00Z","ScheduledDepartureTime":"2021-11-25T11:38:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45565","SequenceOrder":8,"ScheduledArrivalTime":"2021-11-25T11:38:00Z","ScheduledDepartureTime":"2021-11-25T11:38:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48050","SequenceOrder":9,"ScheduledArrivalTime":"2021-11-25T11:38:00Z","ScheduledDepartureTime":"2021-11-25T11:38:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:47885","SequenceOrder":10,"ScheduledArrivalTime":"2021-11-25T11:39:00Z","ScheduledDepartureTime":"2021-11-25T11:39:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45394","SequenceOrder":11,"ScheduledArrivalTime":"2021-11-25T11:42:00Z","ScheduledDepartureTime":"2021-11-25T11:42:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45896","SequenceOrder":12,"ScheduledArrivalTime":"2021-11-25T11:43:00Z","ScheduledDepartureTime":"2021-11-25T11:43:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48891","SequenceOrder":13,"ScheduledArrivalTime":"2021-11-25T11:44:00Z","ScheduledDepartureTime":"2021-11-25T11:44:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:47981","SequenceOrder":14,"ScheduledArrivalTime":"2021-11-25T11:45:00Z","ScheduledDepartureTime":"2021-11-25T11:45:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48885","SequenceOrder":15,"ScheduledArrivalTime":"2021-11-25T11:45:00Z","ScheduledDepartureTime":"2021-11-25T11:45:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:44908","SequenceOrder":16,"ScheduledArrivalTime":"2021-11-25T11:45:00Z","ScheduledDepartureTime":"2021-11-25T11:45:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45443","SequenceOrder":17,"ScheduledArrivalTime":"2021-11-25T11:47:00Z","ScheduledDepartureTime":"2021-11-25T11:47:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:44866","SequenceOrder":18,"ScheduledArrivalTime":"2021-11-25T11:54:00Z","ScheduledDepartureTime":"2021-11-25T11:54:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:102688","SequenceOrder":19,"ScheduledArrivalTime":"2021-11-25T11:55:00Z","ScheduledDepartureTime":"2021-11-25T11:55:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48351","SequenceOrder":20,"ScheduledArrivalTime":"2021-11-25T11:57:00Z","ScheduledDepartureTime":"2021-11-25T11:57:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:44859","SequenceOrder":21,"ScheduledArrivalTime":"2021-11-25T12:00:00Z","ScheduledDepartureTime":"2021-11-25T12:00:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46790","SequenceOrder":22,"ScheduledArrivalTime":"2021-11-25T12:01:00Z","ScheduledDepartureTime":"2021-11-25T12:01:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46782","SequenceOrder":23,"ScheduledArrivalTime":"2021-11-25T12:02:00Z","ScheduledDepartureTime":"2021-11-25T12:02:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46785","SequenceOrder":24,"ScheduledArrivalTime":"2021-11-25T12:03:00Z","ScheduledDepartureTime":"2021-11-25T12:03:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46213","SequenceOrder":25,"ScheduledArrivalTime":"2021-11-25T12:06:00Z","ScheduledDepartureTime":"2021-11-25T12:06:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46210","SequenceOrder":26,"ScheduledArrivalTime":"2021-11-25T12:08:00Z","ScheduledDepartureTime":"2021-11-25T12:08:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46217","SequenceOrder":27,"ScheduledArrivalTime":"2021-11-25T12:08:00Z","ScheduledDepartureTime":"2021-11-25T12:08:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:44813","SequenceOrder":28,"ScheduledArrivalTime":"2021-11-25T12:10:00Z","ScheduledDepartureTime":"2021-11-25T12:10:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48592","SequenceOrder":29,"ScheduledArrivalTime":"2021-11-25T12:13:00Z","ScheduledDepartureTime":"2021-11-25T12:13:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46332","SequenceOrder":30,"ScheduledArrivalTime":"2021-11-25T12:16:00Z","ScheduledDepartureTime":"2021-11-25T12:16:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46533","SequenceOrder":31,"ScheduledArrivalTime":"2021-11-25T12:18:00Z","ScheduledDepartureTime":"2021-11-25T12:18:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:46481","SequenceOrder":32,"ScheduledArrivalTime":"2021-11-25T12:19:00Z","ScheduledDepartureTime":"2021-11-25T12:19:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45304","SequenceOrder":33,"ScheduledArrivalTime":"2021-11-25T12:19:00Z","ScheduledDepartureTime":"2021-11-25T12:19:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45301","SequenceOrder":34,"ScheduledArrivalTime":"2021-11-25T12:20:00Z","ScheduledDepartureTime":"2021-11-25T12:20:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45766","SequenceOrder":35,"ScheduledArrivalTime":"2021-11-25T12:20:00Z","ScheduledDepartureTime":"2021-11-25T12:20:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:48410","SequenceOrder":36,"ScheduledArrivalTime":"2021-11-25T12:23:00Z","ScheduledDepartureTime":"2021-11-25T12:23:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45778","SequenceOrder":37,"ScheduledArrivalTime":"2021-11-25T12:24:00Z","ScheduledDepartureTime":"2021-11-25T12:24:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45062","SequenceOrder":38,"ScheduledArrivalTime":"2021-11-25T12:26:00Z","ScheduledDepartureTime":"2021-11-25T12:26:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:102646","SequenceOrder":39,"ScheduledArrivalTime":"2021-11-25T12:29:00Z","ScheduledDepartureTime":"2021-11-25T12:29:00Z","ArrivalTime":null,"DepartureTime":null},{"StopId":"NSR:Quay:45783","SequenceOrder":40,"ScheduledArrivalTime":"2021-11-25T12:30:00Z","ScheduledDepartureTime":"2021-11-25T12:30:00Z","ArrivalTime":null,"DepartureTime":null}],"PathState":{"TripId":61401006,"OnPath":true,"LostPathAt":null,"LostPathAtLatitude":null,"LostPathAtLongitude":null,"PathReconnectData":null,"LastMatchedProjectedPosition":{"Latitude":59.05163322295099,"Longitude":5.920001915784108,"HorizontalAccuracy":"NaN","VerticalAccuracy":"NaN","Speed":"NaN","Course":"NaN","IsUnknown":false,"Altitude":"NaN"},"LastGpsProgressUpdate":"2021-11-25T11:38:32.6479591Z","Progress":2234.4039506886456,"LastMatchedStopSequenceId":4,"CurrentStopSequenceId":null,"LastMatchedPathSequenceId":93},"SimulationState":{"Position":null,"GpsCheckpoint":{"LastMatchedPathSequenceId":93,"Speed":46.413,"Latitude":59.05163533333333,"Longitude":5.920010333333333,"Odometer":0.0,"Time":"2021-11-25T11:38:32.6479591Z"},"Progress":2234.4039506886456,"LastMatchedStopSequenceId":4,"CurrentStopSequenceId":null,"LastMatchedPathSequenceId":93},"LastUpdatedDelayTime":"2021-11-25T11:38:04.1007918Z"},"NextAssignment":{"TripId":64022002,"ActiveDate":"2021-11-25T00:00:00","StartTime":"2021-11-25T12:57:00Z","EndTime":"2021-11-25T13:15:00Z"},"NextAssignmentUpdatedTime":"2021-11-25T11:30:01.6054719Z","LastCompletedTripEndTime":"2021-11-25T12:30:00Z","LastReceivedGpsMessage":{"Speed":46.413,"Course":334,"Longitude":5.920010333333333,"Latitude":59.05163533333333,"FixType":3,"FixQuality":2,"VehicleId":3169,"DeviceId":"883F4A89949E","Source":"gps","Module":"gnss","RecordedTime":"2021-11-25T11:38:32.6479591Z"},"LastReceivedGatewayLatitude":59.05163533333333,"LastReceivedGatewayLongitude":5.920010333333333}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/776919/143437284-f65614cc-cba4-447e-87ea-e75be76e08e0.png)
![image](https://user-images.githubusercontent.com/776919/143437252-1ca51556-217a-4577-9475-a20965f4a318.png)

**Env**

* Version: 9.32.3
* Compile time: 03/09/2021 14:01:00 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

**Comment by mikecat** [comment]
It looks like you forgot to decode base64 before gunzipping.

[From Base64, Gunzip - CyberChef](https://gchq.github.io/CyberChef/#recipe=From_Base64%28%27A-Za-z0-9%2B/%3D%27,true%29Gunzip%28%29&input=SDRzSUFBQUFBQUFBQ3MxYTIyN2JPQkQ5RnowN0J1OGk5V1lrdlFHYnk5WnBIN3BZTEZTSlRiU1ZKYTlFdGMwRytmY2QraUk3TWUyU2tMRjFFYUMyZUVTZkdjN01FVFY4akQ3cSt5SXI5YnM4U2lnV2FoVGROSFdtMjFibnQ4Vk1SMGxFRU1GbkdKOFJmb3R4UW1WQzZaamltRExGUGtXajZMWkpzOFhkMFp0NWV3azNwbmY2YlZybHBXNysraExuaEdDZW55R0UrUm5Mc3V4TWFvVE9Qb3M4SXpubmltVXBUREUxcWRHWGFYWmZWSHJ4R1NhN2JZbzVEUDJXbXNKME9Wemhhb3c0RnBUVDFUOFlyS3U3OWVoWUVmZ1JSRGVqTjNWYm1LS3ViaC9tZHNJM045TUZXNWcyZVZ6OGIwa0x6T0F1SkViUkpEUEZOMzJ4L1BVdG14RktGbi9XMXZONk5rK3JoNnR1OWxrMzRDOUVSdEdWL21HbXBwNVA5VCtkcmpMTFpYTng0WmVyNmZ2azl5NTlTSmlrU3NFMEY3cE1INkpFQXRDQzJpajU0ekhhaFlNMWlNWFdQNnVwcjV2Yy9peUdLOW05enJ0UzU1T21LYjZscFh1cCtJcDJqNzdRODdReFhhTVA0dzlPQ3I3QVl5R0ZvRWhhOEUvbnBHUXNJTEE0alQ5RlR5T1hvU3dtak8zYVNYenRGSUYycnZFSEo0MFRCbllxeENuMnNSUGdITnpDQ2VGcXI1MEtFN1JySi8zRmRuSXhodFZVR0NzUE95WE1PUmFjeFRHbWUrMFVTRG5zWkw1MnhvRjJydkVISjVVSmxtQm5yQ1R5czVQQWVvbzRSb3pzdFhPVnp5L3M1UCtyblZWWGxqdlcySXQ3T01QS09YSk5uRFRubUdGSEhZeDlPY3RBenZJWW5Ea1hmSmV6UEduT0VuRkgzcXFUNWh4TDZmQXpScjZrVlNCcGRaVGdvTXFSaE5oWDJSa0pJOTNqaDVHV1NqaEkrOG8wbzRHazZWRkNXaXJzSU8ycnVZd0ZrbVpIaVdrbFhhUjlCWlFGUHZqMStJR2VkaVlpUDJuU1RDSHBJQzFPbWpSbmpEcEkrK29oQzlUd0hqL00wN0JsY0pEMkZVUWVtSWc5ZmdocGpJaVFydmp3bFVRZUdCLzhPSmxJdWFOOEVGOUo1SUh4d1k4VUg5enhMRTM4Sk5IcVd3anBMZndnMHJDZGNEd3dFVDlKQkJJNGtEUStEbWxKSEtUOUpCRklCRDE4Yk9HSGtuYW9DL0dUUkdBUTlQQ3hoUjlHbW1CSG9TWitrZ2drZ2piOFcvaWhwRjB4N1NlSlFDSm9GN0NGSDByYXNVTWs4VW1UWnRJWkhuNlNTRUNkd2tqMytHSGl3cFdyZXZncElwQUlUTVFlUHl3OEtIV1FwbjZLQ0NRQ0U3SEhEeU1OcjdvZHBIMFZFUWZHZEk4ZlJocUMya0hhVnhGeDBIWjhDejl3TzQ0YzIzSGJSRGh0MGk1UCt5b2lDYXdlUFg0WTZkaTFDNkQ4cEVsTDVsSkU2cXVJSkxEazlmaUJubzRkT3hmcXE0Z2thTCsxaFI5R0dnbFhuZlpWUkJKWXAzdjgwRTBpY3dXMXJ5U1N3UExSNHdmR2gzU29DL09WUk5zSERDSGQ0ejFKL3drTjNOVGNyOXJCcm9idGRXVUJVV0thVHR0ZWNHdnM5NGxaejdxNXNta2k3NHhzT3NqTElYdjV2YzdxcXRLWmdXWncydCtUdHVZeU5kWllhSkQvRGFQd1lkVmh0dngyRzlXVUVLSTRVc3JScUVaWVlWZ0FxQ3NRMm0vcnB2aTNya3hhVHJLc2czWTY5SWFqcS9RS25QVlJONmJJSEFQVHVkWjUvKzI4N3BwVzkxL2Z0UitxcjFYOUhZaDlTY3NXdkRNcDErd1drS2VsUGRDd0IxdnVHbWphZjVqbk81M3ZWYmNmMnJmd1FwSXJiRmR2amJlYlhNckdERkV3RWQ2UkNNYkZNeWR0dDhUdHVvRXNuWGROb3l2emNtVFh2M2JkdHdDS0F0OXBNZXRLOEhGZDlTR3hjZjl5Q2pEbi9GNW5YK2QxVVpubG1oeVlzL2NoRTJObTN3Y1BPR3B3bmRjemJXeitvREVra0x0eDhOeVZUNy9RbDNaOHVlRDU0aWpDUHI2SWpTSFZZbVViNEUvTFF3MlR0aTN1cWhuODlMT2taSWlBVDhqUFQxSFkwRFdRN000YTBiOUllbFc1RHA5UWVKbThBT3h3V1JsejZNQUNncGIxc3NGdHJiY0hPVXBZc2R4YTRQNjFyWkpsNzRDaW9NR3lmSFBJeFRyZ1JRaXQ4NURhcDdERElYTXcybDRYUDVhblZwYWZvV0NYaFlIa0J3ZnZITmU1ME4rSzFRRWNLZWxyTnBGS01mWEtPaHJZMlBNbzBSMGNNUmxGbDdVdDAvWnJCVEUzaW15Wmc2Sy8vNWpQODJoOTVnVHc5dmYwNFhER09QQUhQUEwwSHpjYXVTeUtKQUFB)

**Comment by furier** [comment]
> It looks like you forgot to decode base64 before gunzipping.

Hmmm so the other site i used magically did that on top of it all? and I could not see anything in the code that gzips and gunzips the json doing any base64 convertion 🤷‍♂️

**Comment by n1073645** [comment]
@mikecat is correct. I will close this for now.
