### ISSUE TITLE
Feature request: Provide Dockerfile for easier development and production deployment

### ISSUE THREAD

**Issue by nileshtrivedi** [gchq/CyberChef#1280]
It'd be really convenient to deploy CyberChef - either for development or in containerized environments like ECS/CapRover/GCP - using a Dockerfile.

Previous relevant issues and PRs are:
- #474 
- #1215
- #1140 
- #670
- #675 
- #677 
- #178

**Comment by loganmarchione** [comment]
Would also really like Docker support. Even if images aren't published to DockerHub or GHCR, an official Dockerfile would be nice (I could build the container myself with Compose).

It seems silly (and kind of a potential security issue) that I'm running code from GCHQ, but having to rely on random third-party images (or make my own). 

Searching on DockerHub, there are a ton of images, but nothing official. 

https://hub.docker.com/search?q=cyberchef

**Comment by a3957273** [comment]
We now support dev containers and automatically build images to GCHR.
