### ISSUE TITLE
Feature request: New padding in AES encrypt and decrypt

### ISSUE THREAD

**Issue by fabio-neo** [gchq/CyberChef#1283]
**Is your feature request related to a problem? Please describe.**

I am trying to use the AES encrypt and decrypt but the system I am testing uses different padding , because of this characteristic my crypt and decrypt are different from what I wish.

**Describe the solution you'd like**

i would like this data **3030303030303030303030303030303030303030303033030303030303030303** 
turn this data **3F 50 8C AC B4 5D 6D 9A  58 7B 56 8D 48 40 F1 D6 88 2B 3A 96 9A 48 AF DD  EE 0D 3E F8 22 CF B4 05**
and not this one  **E1 25 00 FD 5C 98 CF 26  5F D8 BA 4B 60 26 29 4E 90 4A B0 8D 27 2B 9C A8  61 79 59 D5 DE 8E 81 B9 
D2 FF F4 14 94 FF 3D C2  88 7A 1B C9 5E 3D 6C DB**

**Describe alternatives you've considered**
I think that link help to understand what I would be implemented 

**Additional context**
I am using AES-CBC and AES-ECB encrypted methods.
I follow this link help me to discover different padding methods: 
https://the-x.cn/en-us/cryptography/Aes.aspx

![image](https://user-images.githubusercontent.com/54117032/145392505-68698c2f-2f66-4558-95d6-34ab501b7a6b.png)

**Comment by mt3571** [comment]
Could you provide a link to a recipe in CyberChef that recreates this issue? I am unable to recreate it without some more details e.g. the key you are using

**Comment by fabio-neo** [comment]
hello @mt3571  you check the key in the PrintScreen it is **0x0100000000000000000000000000000**
if you need IV could use **0x0100000000000000000000000000000**
the recipe follows in the link 

https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'010000000000000000000000000000000000000000000000000000000000000'%7D,%7B'option':'Hex','string':'0100000000000000000000000000000'%7D,'OFB','Hex','Raw',%7B'option':'Hex','string':''%7D)To_Hexdump(16,true,false,true)&input=MzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMzAzMDMwMzAzMDMwMzAzMDMwMw

**Comment by mikecat** [comment]
How to reproduce "not this one" looks like:

[AES Encrypt, To Hexdump - CyberChef](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt%28%7B%27option%27:%27Hex%27,%27string%27:%270100000000000000000000000000000000000000000000000000000000000000%27%7D,%7B%27option%27:%27Hex%27,%27string%27:%27%27%7D,%27ECB%27,%27Hex%27,%27Raw%27,%7B%27option%27:%27Hex%27,%27string%27:%27%27%7D%29To_Hexdump%2816,true,false,true%29&input=MzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMzAzMDMwMzAzMDMwMzAzMDMwMw)

How did you create the expected data `3F 50 ... B4 05`?
The image doesn't look related to this (at least for me).

**Comment by fabio-neo** [comment]
i would like this data **3030303030303030303030303030303030303030303033030303030303030303**
turn this data **E1 25 00 FD 5C 98 CF 26 5F D8 BA 4B 60 26 29 4E 90 4A B0 8D 27 2B 9C A8 61 79 59 D5 DE 8E 81 B9**
and not this one **E1 25 00 FD 5C 98 CF 26 5F D8 BA 4B 60 26 29 4E 90 4A B0 8D 27 2B 9C A8 61 79 59 D5 DE 8E 81 B9
D2 FF F4 14 94 FF 3D C2 88 7A 1B C9 5E 3D 6C DB**

this time i double checked : [LINK](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'0100000000000000000000000000000000000000000000000000000000000000'%7D,%7B'option':'Hex','string':''%7D,'ECB','Hex','Raw',%7B'option':'Hex','string':''%7D)To_Hexdump(64,true,false,true)&input=MzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMzAzMDMwMzAzMDMwMzAzMDMwMw)

**Comment by n1474335** [comment]
NoPadding options have been added for CBC and ECB modes in AES, DES and Triple DES Decrypt operations in v9.37.0 #1189
