### ISSUE TITLE
Operation request: AES-CMAC algorithm recipe

### ISSUE THREAD

**Issue by Deejuha** [gchq/CyberChef#1284]
Hello,
First of all thanks for this great tool!

**Is your feature request related to a problem? Please describe.**
I've met the `AES-CMAC` algorithm in many places in automotive world.
I think the great idea is to add it into CyberChef!

**Describe the solution you'd like**
Add new recipe - `AES-CMAC` standarized with [this document](https://datatracker.ietf.org/doc/html/rfc4493). Here is a working [example](https://artjomb.github.io/cryptojs-extension/) how could we use it.

**Describe alternatives you've considered**
Well, no alternatives really.

**Additional context**
[Here](https://datatracker.ietf.org/doc/html/rfc4493#section-4) you can find some test vector for unit tests.

Stay healthy!

**Comment by mikecat** [comment]
Implemented! I hope you like this.
