### ISSUE TITLE
Some XML utils, e.g. XPath queries?

### ISSUE THREAD

**Issue by strawp** [gchq/CyberChef#13]
Would be cool to be able to have an ingredient which can do XPath queries

**Comment by Mikescher** [comment]
Yeah I missed XPath (and perhaps [JSoup-like CSS queries](https://jsoup.org/cookbook/extracting-data/selector-syntax)) too.
If I find some time this afternoon I will probably try to implement it and make an pull request :)

**Comment by strawp** [comment]
Nice one :)
