### ISSUE TITLE
Bug report: <Find/Replace do not support replace . to other character when used after From Base64>

### ISSUE THREAD

**Issue by lucyel** [gchq/CyberChef#1301]
**Describe the bug**
When i tried to use the find/replace op to replace all the character . to none character in the string.
It only replace the . character that inside two other . character.
The problems only happen when find/replace used after from base64.
When i only use find/replace the . got replaced without issue

**To Reproduce**
1. Use the from base64 op
2. Then use the find/replace op
3. On the find box put the . char and choose simple string
4. on the replace box leave empty.
5. imput a base64 that decoded back to . character

**Expected behaviour**
Only the . character in the middle of 2 other . got replaced

**Screenshots**
![ảnh](https://user-images.githubusercontent.com/32479481/148031652-8b718ef0-f4f4-4a68-812b-5075d4b0aa21.png)

**Comment by mikecat** [comment]
Non-printable characters (for example, NUL) can be displayed as `.`.
Try using "To Hexdump" after "From Base64" to see what is the real character code.

In this case, you may want to do "Decode text" with Encoding "UTF-16LE (1200)" instead of "Find / Replace" after "From Base64".

**Comment by lucyel** [comment]
Yeah you're right, use "Decode text" with Encoding "UTF-16LE (1200)" sovle the problems.
