### ISSUE TITLE
Feature request: How much effort will it take to bundle it as an electron app?

### ISSUE THREAD

**Issue by jampack** [gchq/CyberChef#1323]
I was wondering if this could be bundled as an electron app so that executing the UI will be more user friendly.

**Comment by a3957273** [comment]
There's a couple of PRs to build the website into a 'Tauri' application, which is a lighter-weight version of Electron.  See https://github.com/gchq/CyberChef/pull/1712 and https://github.com/gchq/CyberChef/pull/1495.  Both got closed, but we'll see if we can re look into this.

**Comment by a3957273** [comment]
Closing this in favour of duplicate issue: https://github.com/gchq/CyberChef/issues/1074
