### ISSUE TITLE
Bug report: Answer field in json format

### ISSUE THREAD

**Issue by povilassl** [gchq/CyberChef#1330]
**Describe the bug**
The answer field shows a json format instead of a table with answers / entropies

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. add magic
2. add rot13
3. works with any text

**Expected behaviour**
Should rotate the characters of the magic output

**Screenshots**

* Version: 9.37.0
* Compile time: 29/03/2022 17:07:59 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Magic(2,false,false,'')ROT13(true,true,false,21)&input=YW55IHRleHQ)

![Capture](https://user-images.githubusercontent.com/78279117/161454990-37267a77-d8b0-473c-a211-9343e4d3c13c.JPG)
![Capture](https://user-images.githubusercontent.com/78279117/161455056-5dfa203b-a3fb-4a81-a12a-00fd9908e893.JPG)

**Comment by mattnotmitt** [comment]
`Magic` outputs a JSON object under the hood which is then rendered to the HTML table you'll see if it's the final stage of a recipe. What are you trying to achieve?

**Comment by povilassl** [comment]
Okay, thank you. My magic had a single output, thought I could simply pass it to Rot. Just looked kind of weird when I first encountered that answer
