### ISSUE TITLE
Feature request: Unique Count Operation

### ISSUE THREAD

**Issue by d-Rickyy-b** [gchq/CyberChef#1334]
**Is your feature request related to a problem? Please describe.**
Often I come across lists of data for which I need to create a unique list from. That can easily be done with the "Unique" operation.
But every now and then I find myself in a situation where I need to create a unique list but at the same time count the occurrences of each unique item. I was not able to find an existing operation for this.

**Describe the solution you'd like**
Take this input for example:
```
Hello
Hello
Hello
World
Foo
Bar
Foo
```

After running the "Unique Count" operation on it, this should be the output:
```
3 Hello
1 World
2 Foo
1 Bar
```

**Describe alternatives you've considered**
I have not found any alternatives or existing workarounds yet.

**Additional context**
N/A

**Comment by n1474335** [comment]
Added in v9.37.3: https://gchq.github.io/CyberChef/#recipe=Unique('Line%20feed',true)&input=SGVsbG8KSGVsbG8KSGVsbG8KV29ybGQKRm9vCkJhcgpGb28
