### ISSUE TITLE
Bug report: Optical Character Recognition (OCR) not working

### ISSUE THREAD

**Issue by mattnotmax** [gchq/CyberChef#1344]
**Describe the bug**
Current version 9.37.3 the OCR operation stalls at the 'finding text' stage. This is for Firefox and Chrome tested against the GCHQ github instance.

However, if I run a Docker version of 9.37.3 I can get OCR to work, **but only on Firefox.**

I have downgraded to 9.32.0 on another webserver (as I saw that tesseract was updated from 2.1.1 -> 2.1.5 in 9.32.1). I can get OCR to work but again only in Firefox and Chrome has the same issue. 

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Load a PNG image with text
2. Apply OCR operation
3. OCR generation starts and stalls at 'finding text'
4. OCRed text does not appear

**Expected behaviour**
The text should be OCRed.

**Screenshots**

Chrome - current version - GCHQ github
![image](https://user-images.githubusercontent.com/39072319/165500535-e80b2340-094c-494f-a99f-82d025691f1a.png)

Firefox 9.32.0 working
![9 32 0-firefox](https://user-images.githubusercontent.com/39072319/165499348-d41b26dd-7917-4ffb-be99-5be3fee4e9eb.PNG)

Docker current version - working
![9 37 3-docker](https://user-images.githubusercontent.com/39072319/165499363-ed8b64c4-9ce6-4770-a198-2a043787227a.PNG)

**Desktop (if relevant, please complete the following information):**
Tested Chrome Version 100.0.4896.127 (Official Build) (64-bit) and Chrome Version 101.0.4951.41 (Official Build) (64-bit) with same results. 

Tested Firefox 99.0.1 (64-bit)

**Additional context**
Thanks as always for a great tool.

**Comment by madeinoz67** [comment]
yes confirming same issue with Edge
