### ISSUE TITLE
Recipe changes not autobaked for multiple inputs

### ISSUE THREAD

**Issue by john19696** [gchq/CyberChef#1346]
**Describe the bug**
Only the input in focus is autobaked on recipe change

**To Reproduce**
Add 2nd input tab by pressing '+' on the Input menu bar
Add a generate operation from 'Other' category

**Expected behaviour**
All output tabs contain generated data

**Screenshots**
N/A

**Desktop (if relevant, please complete the following information):**
 - OS: MacOS Monterey 12.3.1
 - Browser: Safari 15.4
 - CyberChef version: 9.37.3

**Additional context**

**Comment by n1474335** [comment]
This is intended behaviour. Clicking 'Bake' will bake all the inputs. Auto-bake will only bake the active input.

The reasoning for this is that CyberChef can support hundreds of thousands of inputs. Baking all of those at once every time you type a single character in the input might not be desirable! In theory we could add some logic to check how many inputs there are and auto-bake if it's a low number, but I would rather we act consistently.
