### ISSUE TITLE
Bug report: X509 cert parsing fails for a valid cert input

### ISSUE THREAD

**Issue by James-ZHANG** [gchq/CyberChef#1355]
When I parse an X509 cert in DER hex format. The parsing fails with `Parse X.509 certificate - checking tag doesn't match: A0!=02`.

```
* Version: 9.7.1
* Compile time: 08/10/2019 20:43:46 UTC
* User-Agent:
Mozilla/5.0 (X11; CrOS x86_64 14753.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.9999.0 Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Parse_X.509_certificate('DER%20Hex')&input=MzA4MjAxMjYzMDgxQ0VBMDAzMDIwMTAyMDIwMTAwMzAwQTA2MDgyQTg2NDhDRTNEMDQwMzAyMzAwRjMxMEQzMDBCMDYwMzU1MDQwMzEzMDQ2MzcyMzUzMDMwMjIxODBGMzIzMDMwMzAzMDMxMzAzMTMwMzAzMDMwMzAzMDVBMTgwRjMyMzAzOTM5MzEzMjMzMzEzMjMzMzUzOTM1Mzk1QTMwMEYzMTBEMzAwQjA2MDM1NTA0MDMxMzA0NjM3MjM1MzAzMDU5MzAxMzA2MDcyQTg2NDhDRTNEMDIwMTA2MDgyQTg2NDhDRTNEMDMwMTA3MDM0MjAwMDQ0MkI4RUI1M0FFRUE2REI1RkYyMUNGRkI3NzlENzI4RkY3NjZGNzAzQzI4ODlFMjlFNzJCNjkzMkUzRkMwNDczMjM0QjlFMUMxOEQwNjUwMkVGOEY2MzI2NjRDMjhCRTI2MDY5Qzg1NjFBNkNCQ0I1MkI2RTcxMzk3NzQ3MEEwQUEzMTczMDE1MzAxMzA2MEIyQjA2MDEwNDAxODJFNTFDMDIwMTAxMDQwNDAzMDIwMzA4MzAwQTA2MDgyQTg2NDhDRTNEMDQwMzAyMDM0NzAwMzA0NDAyMjAyN0NENkI2MzY5RTQ3QzI5QkJGQzAzN0I1NUMwQUIwODA4MTQ5MTZDNDlEQUVGNEY5NTJDMDcxQ0E0NkE1NDQ4MDIyMDZFQTQzQUZFOEVBNEI0MUVDQ0IwRkI3MkZBREQ0NzE5NjE5NEI1NDUzQTExNzgwOUUxN0U0OEZBM0JGQTQxNkQ)
```

Interestingly, if I convert the input with "hex to PEM" recipe into a cert in PEM format, and then parse that with "Parse X509 (PEM)". The parsing succeeds.

**Comment by mikecat** [comment]
current version

```
Version 9.48.0
Compile time: 14/10/2022 23:17:50 UTC
```

yielded:

```
Parse X.509 certificate - Error in https://gchq.github.io/CyberChef/modules/PublicKey.js on line 2.<br><br>Message: improper ASN.1 parsed X500Name: Error: improper ASN.1 parsed RDN: TypeError: t.set is undefined
```

More interestingly, when the input is converted to lowercase (via "To Lower case" operation or directly pasting lowercase version as input), the "Parse X.509 certificate" operation looks succeeding.

[To Lower case, Parse X.509 certificate - CyberChef](https://gchq.github.io/CyberChef/#recipe=To_Lower_case%28%29Parse_X.509_certificate%28%27DER%20Hex%27%29&input=MzA4MjAxMjYzMDgxQ0VBMDAzMDIwMTAyMDIwMTAwMzAwQTA2MDgyQTg2NDhDRTNEMDQwMzAyMzAwRjMxMEQzMDBCMDYwMzU1MDQwMzEzMDQ2MzcyMzUzMDMwMjIxODBGMzIzMDMwMzAzMDMxMzAzMTMwMzAzMDMwMzAzMDVBMTgwRjMyMzAzOTM5MzEzMjMzMzEzMjMzMzUzOTM1Mzk1QTMwMEYzMTBEMzAwQjA2MDM1NTA0MDMxMzA0NjM3MjM1MzAzMDU5MzAxMzA2MDcyQTg2NDhDRTNEMDIwMTA2MDgyQTg2NDhDRTNEMDMwMTA3MDM0MjAwMDQ0MkI4RUI1M0FFRUE2REI1RkYyMUNGRkI3NzlENzI4RkY3NjZGNzAzQzI4ODlFMjlFNzJCNjkzMkUzRkMwNDczMjM0QjlFMUMxOEQwNjUwMkVGOEY2MzI2NjRDMjhCRTI2MDY5Qzg1NjFBNkNCQ0I1MkI2RTcxMzk3NzQ3MEEwQUEzMTczMDE1MzAxMzA2MEIyQjA2MDEwNDAxODJFNTFDMDIwMTAxMDQwNDAzMDIwMzA4MzAwQTA2MDgyQTg2NDhDRTNEMDQwMzAyMDM0NzAwMzA0NDAyMjAyN0NENkI2MzY5RTQ3QzI5QkJGQzAzN0I1NUMwQUIwODA4MTQ5MTZDNDlEQUVGNEY5NTJDMDcxQ0E0NkE1NDQ4MDIyMDZFQTQzQUZFOEVBNEI0MUVDQ0IwRkI3MkZBREQ0NzE5NjE5NEI1NDUzQTExNzgwOUUxN0U0OEZBM0JGQTQxNkQ)

#1203 might be related?
