### ISSUE TITLE
Feature request: Refang

### ISSUE THREAD

**Issue by jethrop** [gchq/CyberChef#1358]
A tool that reverts defanged urls back to usable fanged urls. A defang decoder if you will.

**Comment by mattnotmax** [comment]
https://github.com/gchq/CyberChef/pull/654 Looks like your answer! 👍

**Comment by a3957273** [comment]
Merged in a 'Fang URL', [example](https://gchq.github.io/CyberChef/#recipe=Fang_URL(true,true,true)&input=aHh4cHNbOi8vXWV4YW1wbGVbLl1jb20)

**Comment by mr-r3b00t** [comment]
> Merged in a 'Fang URL' operation, [example](https://gchq.github.io/CyberChef/#recipe=Fang_URL(true,true,true)&input=aHh4cHNbOi8vXWV4YW1wbGVbLl1jb20)

Thank you so much :) 

https://x.com/UK_Daniel_Card/status/1781688362170008005
