### ISSUE TITLE
Bug report: 32 and 64-bit fletcher checksums are incorrect

### ISSUE THREAD

**Issue by nolanhergert** [gchq/CyberChef#1377]
**Describe the bug**
Fletcher32 and Fletcher64 algorithms use bytes for summation instead of uint16 or uint32, respectively. They don't match wikipedia: https://en.wikipedia.org/wiki/Fletcher%27s_checksum#Test_vectors

**To Reproduce**
(https://gchq.github.io/CyberChef/#recipe=Fletcher-64_Checksum()&input=YWJjZGVmZ2g)

**Expected behaviour**
Expected output: 0x312E2B28CCCAC8C6
Actual output:      0x00000df800000324

**Additional context**

Please see this issue I submitted with another repo for some refactored example code that fixes the issue. I don't know the details of your implementation. https://github.com/GRISHNOV/Fletcher_checksum/issues/2

**Comment by nolanhergert** [comment]
Similar issue: https://github.com/gchq/CyberChef/issues/51

**Comment by n1073645** [comment]
This is further explained in #1316 . It is a known bug and hopefully will be fixed soon.

**Comment by nolanhergert** [comment]
Sounds good to me, closing.
