### ISSUE TITLE
This is strange.

### ISSUE THREAD

**Issue by ThienVie** [gchq/CyberChef#1389]
Can you help me? Somehow it can't load.![image](https://user-images.githubusercontent.com/98856248/181666220-e955a054-481e-4a14-8ce1-ec0df07a3225.png)

**Comment by n1073645** [comment]
What browser and what version of browser are you using?

We only support newer Chrome and Firefox.

**Comment by ThienVie** [comment]
Oh... Now I understand. I use Safari.
