### ISSUE TITLE
Bug report: New Encode/Decode text incorrect handles some encodings

### ISSUE THREAD

**Issue by u0m3** [gchq/CyberChef#139]
### Summary

The new blocks used for encoding/decoding text do not correctly handle Windows Unicode (UTF16LE) and maybe other encodings.

### Example

I found this while playing with PowerShell encoded commands.

In order to generate a PowerShell encoded in Base64 one needs to apply this procedure:

```powershell
$command = 'dir "c:\program files" '
$bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
$encodedCommand = [System.Convert]::ToBase64String($bytes)
```

Now in order to decode the command one needs to apply the following (reverse) transformations:

```powershell
$bytes = [System.Convert]::FromBase64String($encodedCommand)
$command = [System.Text.Encoding]::Unicode.GetString($bytes)
```

The problem was encountered when I attempted to decode the `$encodedCommand` in **CyberChef** as I was unable to change the encoding. Just applying the **From Base64** block produces **UTF-16LE** bytes.

With the old block from `Compile time: 18/05/2017 23:24:36 UTC` called **Text encoding** I could have decoded this using **UTF-8** as input type and **UTF-16LE** as output type.

But with the new **Decode text** block I can not find a way to properly decode it.

Take the Base64 string `JAA=` witch was obtained with

```powershell
[System.Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes('$'))
```

In **CyberChef** passing it through **From Base64** -> **To Hex** yelds `24 00` witch is the **UTF-16LE** code for **$**.

Now I expected that using a chain like **From Base64** -> **Decode text** (*Encoding*: UTF16LE(1200)) -> **To Hex** would yeld `24` but instead it yealds `ef bf bd ef bf bd` [Link to recipe](https://gchq.github.io/CyberChef/cyberchef.htm?recipe=%5B%7B%22op%22%3A%22From%20Base64%22%2C%22args%22%3A%5B%22A-Za-z0-9%2B%2F%3D%22%2Ctrue%5D%7D%2C%7B%22op%22%3A%22Decode%20text%22%2C%22args%22%3A%5B%22UTF16LE%20(1200)%22%5D%7D%2C%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=SkFBPQ).

But funny enough if I use a chain like **From Base64** -> **Decode text** (*Encoding*: ISO-8859-16 Latin 10 (28606)) -> **To Hex** it almost yelds the correct answer (there is an extra null byte at the end). You can't tell from the **$** example but [here](https://gchq.github.io/CyberChef/cyberchef.htm?recipe=%5B%7B%22op%22%3A%22Fork%22%2C%22args%22%3A%5B%22%5C%5Cn%22%2C%22%5C%5Cn%22%2Cfalse%5D%7D%2C%7B%22op%22%3A%22From%20Base64%22%2C%22args%22%3A%5B%22A-Za-z0-9%2B%2F%3D%22%2Ctrue%5D%7D%2C%7B%22op%22%3A%22Decode%20text%22%2C%22args%22%3A%5B%22ISO-8859-16%20Latin%2010%20(28606)%22%5D%7D%2C%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=SkFBPQpaQUJwQUhJQUlBQWlBR01BT2dCY0FIQUFjZ0J2QUdjQWNnQmhBRzBBSUFCbUFHa0FiQUJsQUhNQUlnQWdBQT09) is a recipe that illustrates it.

### Possible solutions

I have not had time to analyze the issue but looking at the commit, **src/core/lib/codepage.js** jumps out at me as the general area of the issue.

### Environment

* CyberChef compile time: 19/05/2017 14:21:44 UTC

* User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* [Link to reproduce](https://gchq.github.io/CyberChef/cyberchef.htm?recipe=%5B%7B%22op%22%3A%22From%20Base64%22%2C%22args%22%3A%5B%22A-Za-z0-9%2B%2F%3D%22%2Ctrue%5D%7D%2C%7B%22op%22%3A%22Encode%20text%22%2C%22args%22%3A%5B%22UTF16%20(1201)%22%5D%2C%22disabled%22%3Atrue%7D%2C%7B%22op%22%3A%22Decode%20text%22%2C%22args%22%3A%5B%22UTF16LE%20(1200)%22%5D%7D%2C%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=WkFCcEFISUFJQUFpQUdNQU9nQmNBSEFBY2dCdkFHY0FjZ0JoQUcwQUlBQm1BR2tBYkFCbEFITUFJZ0FnQUE9PQ)

**Comment by tlwr** [comment]
Thanks for this detailed bug report, I am looking into it now.
