### ISSUE TITLE
Feature request: Rabbit Stream Cipher

### ISSUE THREAD

**Issue by jiayuqi7813** [gchq/CyberChef#1404]
**Is your feature request related to a problem? Please describe.**
When I was trying to decrypt some Rabbit stream passwords, online sites would not be able to decrypt the data because of salt, and when the data is too large, it will also be unable to decrypt the data, hopefully CyberChef will add Rabbit decryption

**Describe the solution you'd like**
Added encryption and decryption support for Rabbit Stream Chiper

**Describe alternatives you've considered**
Other tools can decrypt Rabbit data, but not when the amount of data is too large or when there is VI

**Comment by Lazzzaro** [comment]
And it would be better if with-salt and no-salt Rabbit Stream Cipher are both supported.

**Comment by mikecat** [comment]
I tried implementing that.

My implementation processed 100MB (100,000,000B) input in about 20 seconds  
on Firefox 106.0.2 and Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz.  
However, processing larger input looked difficult.

Does this satisfy your requirements, especially being able to handle large data?
