### ISSUE TITLE
Bug report: Offline Version Load Forever

### ISSUE THREAD

**Issue by JohnKIMMI** [gchq/CyberChef#1424]
I'm trying to use CyberChef in Window Device where it is not connected to internet.
I downloaded the latest version(v9.46.5) of CyberChef zip file and transfered it using non-network related method.
But when I try to open it, it stays in the pre-loading  screen.

**Comment by mattnotmax** [comment]
Hi @JohnKIMMI , it would be useful to provide more information like the OS and browser version. CyberChef is designed to be run offline so, I'd re-download if possible and use the latest supported browsers: Firefox or Chrome.

**Comment by drifter75** [comment]
having the same issue. deployed with internal network access only and some or most of the functions are not working.

**Comment by a3957273** [comment]
I'm going to close this as we've had several individuals separately confirm it can run offline.  Feel free to give us more details and we'll re-open this.
