### ISSUE TITLE
Unicode encode support

### ISSUE THREAD

**Issue by 0xdevalias** [gchq/CyberChef#145]
It would be great to be able to unicode encode data. For 'special characters' and just all characters. Ability to pick the output format (java escaping, javascript, %, etc) would be a bonus.

**Comment by n1474335** [comment]
This would be the sister operation to [Unescape Unicode Characters](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22Unescape%20Unicode%20Characters%22%2C%22args%22%3A%5B%22%5C%5Cu%22%5D%7D%5D). Good idea. If anyone wants to have a stab at it, please go ahead.
