### ISSUE TITLE
Operation request: RESTful API operation

### ISSUE THREAD

**Issue by Antelox** [gchq/CyberChef#146]
I have put _Misc_ prefix as it's a kind of _Feature request_ and a general question.
I would like to know if it's possible to create a new operation with which I could contact a domain, get the response and pass it to the other recipe(s).

Example:
I have a pastebin link which contains a base64 encoded text. Then I would like to create a kind of new operator called for example _Make request_ which take as argument the URL to be contacted. I will add the recipe From Base64 and i will get the response decoded.

Of course if there is another way to accomplish this kind of task I would like to hear from you. =)

Thanks in advance for your time.

**Comment by n1474335** [comment]
I have been considering for a while adding a new operation to make generic RESTful API requests. I believe this would cover what you're asking for. Now that we can support asynchronous operations, this should be relatively simple to implement.

**Comment by sroberts** [comment]
@n147335 That would be pretty insane.
