### ISSUE TITLE
Bug report: Regex issue with negated character class before end of line

### ISSUE THREAD

**Issue by Peterl777** [gchq/CyberChef#1471]
**Describe the bug**
There appears to be some mistake in the regex matching of the last line of some input, when using a negated character class.

**To Reproduce**
Input:
```
abc
de
def
ghi
```
(Note: cr on last line)

Recipe of Regular expression: User defined: Regex `.[^ie]$`, (that is, any character, not an i nor e, then the end of the line)
Highlight matches.

**Expected behaviour**
Expected it to highlight like this:
```
a<blue>bc<blue />
de
d<yellow>ef<yellow />
ghi
```
Actually got:
```
a<blue>bc<blue />
de                                <-- Correctly not highlighted.
d<yellow>ef<yellow />
gh<blue>i<blue />                 <--- Didn't expect this to be highlighted.
```

**Desktop:**
 - OS: Windows 10 Home
 - Browser: FF 106.0.5, also tried on Edge 107.0.1418.35 (Official build) (64-bit)
 - CyberChef version: 9.48.0. Also tried with 9.32.3

**Other content**
Perhaps there is some issue with regex that I am not aware of? Maybe a JS regex engine issue?

But I tried the same regex in Python, and it worked as expected:
```python
import re
s = """abc
de
def
ghi
"""
for line in s.splitlines():
    if re.search(r'.[^ie]$', line):
        print(line)
```

Output:
```
abc
def
```

**Comment by mikecat** [comment]
I don't think this is a bug.

At the end of input, there are characters `'g', 'h', 'i', '\n'`.

Therefore, the `i` is highlignted because `.` matches `'i'`, `[^ie]` matches `'\n'`, and `$` matches at the end of input.

In your Python example, `s.splitlines()` doesn't include `'\n'` in the result, so this doesn't happen.

```
>>> import re
>>> s = """abc
... de
... def
... ghi
... """
>>> s
'abc\nde\ndef\nghi\n'
>>> list(s.splitlines())
['abc', 'de', 'def', 'ghi']
>>>
```

**Comment by Peterl777** [comment]
Ahh. Interesting. Yes, you're right about `splitlines`. But I was still unclear about the `de\n` "correctly" not being highlighted, when `ghi\n` is being `<strikethrough>`incorrectly`</strikethrough>` highlighted.

I've added my understanding below, to help anyone else stumbling across this issue.

I'm assuming that ticking "^ and $ match at newlines" in CC is the equivalent to Python's re.MULTILINE mode. Python's help says "$ Matches the end of the string or just before the newline at the end of the string, and in MULTILINE mode **also** matches before a newline" (My emphasis). (I know CC is in JS, but this behaviour appears to be the same).

I think the key word there is "**also**". So `$` is actually hitting twice at the end - once for the end of line, and then again for end of string. Which is why `de\n` in my example is not being highlighted: `$` matches end-of-line, and `e` is failing the not-i-or-e. 
But for `ghi\n<end-of-string>`, `.` is matching the `i`, `[^ie]` is matching the `\n`, and `$` is matching end-of-string.

This made it clearer for me:
```python
>>> re.findall(r'.[^ie]$', 'abc\nde\ndef\nghi\n', re.MULTILINE)
['bc', 'ef', 'i\n']
```

So this is not a bug with CyberChef, and the issue can be closed. Thanks for your insights.
