### ISSUE TITLE
Bug report: To Base 16, From Hex and To Hex give same outputs for different inputs

### ISSUE THREAD

**Issue by pacorrop** [gchq/CyberChef#1479]
**Describe the bug**
The title is self explanatory.

**To Reproduce**
For an input of 512 the output is incorrectly 0x2000 https://gchq.github.io/CyberChef/#recipe=To_Base(16)From_Hex('Auto')To_Hex('Space',0)&input=NTEy
For an input of 8192 the output is correctly 0x2000 https://gchq.github.io/CyberChef/#recipe=To_Base(16)From_Hex('Auto')To_Hex('Space',0)&input=ODE5Mg

**Expected behaviour**
512 in hex is 02 00, not 20 00

**Screenshots**
N/A

**Desktop (if relevant, please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mikecat** [comment]
You can mitigate this by adding an operation to add a padding zero if the data has odd number of digits.

[To Base, Find / Replace, From Hex, To Hex - CyberChef](https://gchq.github.io/CyberChef/#recipe=To_Base%2816%29Find_/_Replace%28%7B%27option%27:%27Regex%27,%27string%27:%27%5E%28.%29%28%28..%29%2A%29$%27%7D,%270$1$2%27,false,false,false,true%29From_Hex%28%27Auto%27%29To_Hex%28%27Space%27,0%29&input=NTEy)

**Comment by pacorrop** [comment]
Thanks for your prompt reply!

Whereas this works, it does not look good. Just showing an idempotent function like From Hex and then To Hex gives also zero padding issues:
From Hex -> To Hex. Input 32f, output is 32 0f: https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')To_Hex('Space',0)&input=MzJm
From Hex -> To Hex. Input 32f, output is 32 0f: https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')To_Hex('Space',0)&input=MDMyZg
Using regex expressions to solve this is a bit of overwhelming as a user. Maybe insert this regex function on the affected function (From Hex, To Hex) in the backend?

**Comment by mikecat** [comment]
"To/From Base" is for converting presentation of **integers**.
"To/From Hex" is for encoding/decoding **bytes** as hexadeximal strings.

I don't think it is good for "To Base" to add an extra (trailing) zero by default.
Also, if "To Hex" were changed to emit "32 f" for this latter case, it will also output "32 f" for an input "320f" and the output becomes differ from the input.

If you want identical output as input, I think it is good not to apply any operations.

**Comment by pacorrop** [comment]
I see. You are right, and indeed the regex step does the job.

Thanks for your work!
