### ISSUE TITLE
Feature request: RSA extract params from Public key

### ISSUE THREAD

**Issue by sichej** [gchq/CyberChef#1481]
**Is your feature request related to a problem? Please describe.**
I need to extract modules and exponent from Public key RSA

**Describe the solution you'd like**
From string/file to module and exponent

**Describe alternatives you've considered**
using OpenSSL, but is easier for everybody here.

**Comment by cplussharp** [comment]
You can use [PEM_to_Hex] + [Parse_ASN.1_hex_string]

Or if it gets merged sometimes the conversion from PEM to JSON Web Key (see #1794 )

**Comment by a3957273** [comment]
Closed by https://github.com/gchq/CyberChef/pull/1277, which returns a list of parameters from within a public key.
