### ISSUE TITLE
Bug report: <Add text to generated qr code got error>

### ISSUE THREAD

**Issue by alifazl3** [gchq/CyberChef#1503]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. generete a qr code from any simple link or etc...
2. try to add text on it 
3. See error

**Comment by mikecat** [comment]
Looks working in my environment.

[Generate QR Code, Add Text To Image - CyberChef](https://gchq.github.io/CyberChef/#recipe=Generate_QR_Code%28%27PNG%27,5,4,%27Medium%27%29Add_Text_To_Image%28%27hoge%27,%27None%27,%27None%27,0,0,32,%27Roboto%27,255,255,255,255%29&input=aHR0cHM6Ly9leGFtcGxlLmNvbS8)

* Version: 9.55.0
* Compile time: 09/12/2022 11:42:13 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Generate_QR_Code('PNG',5,4,'Medium')Add_Text_To_Image('hoge','None','None',0,0,32,'Roboto',255,255,255,255)&input=aHR0cHM6Ly9leGFtcGxlLmNvbS8)

What error do you get and what is your environment (browser, etc.)?

**Comment by alifazl3** [comment]
this is what i get:
![Uploading Screenshot 2023-12-19 at 7.54.25 PM.jpg…]()

**Comment by alifazl3** [comment]
this is what i get:
![Screenshot 2023-12-19 at 7 54 25 PM](https://github.com/gchq/CyberChef/assets/76215649/83d06157-9604-40ac-ada2-bbf6c9f84006)

**Comment by a3957273** [comment]
The 'Add Text to Image' component has now been updated and I can no longer reproduce this issue.  Hopefully fixed, feel free to request I reopen this if not!
