### ISSUE TITLE
Feature request: Refang URLs and IP addresses

### ISSUE THREAD

**Issue by sscoconutree** [gchq/CyberChef#1513]
**Describe the solution you'd like**
Looking for refang feature of URLs and IP addresses. It appears to be the Fang URL/IP functionality is not there.

Examples:

Defang URL input: hxxps[://]google[.]com
Refang URL output: https://google.com

Defang IP address input: 10[.]10[.]10[.]10
Refang IP address output: 10.10.10.10

**Comment by aaronquiamco** [comment]
![image](https://user-images.githubusercontent.com/59388557/219581740-c2619a5b-d00e-4191-b610-c2b11399f7d6.png)

**Comment by a3957273** [comment]
Supported as part of the new 'Fang' operation.
