### ISSUE TITLE
Feature request: reverse operation

### ISSUE THREAD

**Issue by Grafenea** [gchq/CyberChef#1516]
**Is your feature request related to a problem? Please describe.**
In CyberChef most of the coding and encryption tools have a version for coding and decoding, however it is a bit laborious to configure the reverse way of the process.

**Describe the solution you'd like**
It could have an auto reverse option, which would create a recipe to decode that process.

**Describe alternatives you've considered**
None.

**Additional context**
For example, I set it to encode from XOR to RC4, clicking on the reverse option automatically switches to RC4 for XOR, including the settings values ​​within the "ingredients" of the recipe.

**Comment by mattnotmax** [comment]
+1. Similar discussion at https://github.com/gchq/CyberChef/issues/1263
