### ISSUE TITLE
Bug report: RTLO Unicode Character (U+202E) not properly handled in output

### ISSUE THREAD

**Issue by 0xv1n** [gchq/CyberChef#1535]
**Describe the bug**
When pasting a string with a RTLO character, CyberChef represents it as `â®` now. In prior builds, the RTLO was properly represented in the Output box.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Enter any string containing RTLO (U+202E) in the Input box
2. Observe the Output

**Expected behaviour**
Unicode character should be represented accurately in the Output box.

**Screenshots**

![image](https://user-images.githubusercontent.com/11021725/227342752-ad6afb61-e069-46a6-a23c-520ba0a97716.png)

**Desktop (if relevant, please complete the following information):**
 - OS: Windows
 - Browser: 111.0.1
 - CyberChef version: Version 10.2.0

**Additional context**

**Comment by n1474335** [comment]
This is expected behaviour if your Output character encoding is set to 'Raw bytes'. Setting the Output character encoding to 'UTF-8' renders this character as a control character: https://gchq.github.io/CyberChef/#input=SGVsbG/igK5Xb3JsZA&oenc=65001
