### ISSUE TITLE
Feature request: System Requirements

### ISSUE THREAD

**Issue by tbennett6421** [gchq/CyberChef#1558]
**Is your feature request related to a problem? Please describe.**
No, documentation related

**Describe the solution you'd like**
Are there any minimum/recommended hardware/software requirements? Or any suggestions regarding sizing?

**Comment by a3957273** [comment]
Whilst some operations can be CPU intensive (e.g. calculating RAKE probabilities), the CyberChef application itself should be very light weight on both memory and CPU.  We have minimum browser requirements, but no minimum specs.
