### ISSUE TITLE
Bug report: method undefined & UTF-8 charactors display incorrectly

### ISSUE THREAD

**Issue by Cnily03** [gchq/CyberChef#1560]
## Describe the bug
`self.xxx = function(...){...}` in [`src/core/ChefWorker.js`](https://github.com/gchq/CyberChef/blob/master/src/core/ChefWorker.js) is not effective in [`src/core/Utils.mjs`](https://github.com/gchq/CyberChef/blob/master/src/core/Utils.mjs), which directly makes [`src/core/Utils.mjs:642`](https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/Utils.mjs#L642) trigger error and fails to display UTF-8-decoded str.

See: https://gchq.github.io/CyberChef/#input=5rWL6K%2BV5paH5pys. Empty Recipe:

![tTst-1](https://user-images.githubusercontent.com/56472849/232556490-045fb6ee-6935-4ca5-aac9-6352dfcb0fa4.png)

See: https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)&input=NXJXTDZLK1Y1cGFINXB5cw. `5rWL6K+V5paH5pys` is the Base64 format of `测试文本`:

![Test-2](https://user-images.githubusercontent.com/56472849/232557299-450d6da5-466e-49f6-a8ad-c3bf03c2f8d2.png)

## To Reproduce

0. run `npm run start` **before editing**

2. Insert
    ```javascript
    console.log("Self:", self.loadRequiredModules, self.sendStatusMessage, self.sendProgressMessage, self.setOption, self.setRegisters)
    ```
    after https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/Utils.mjs#L8-L13
    ![image-self](https://user-images.githubusercontent.com/56472849/232558040-9a910071-20d3-4fe9-8579-e84b9893689e.png)

3. Insert
    ```javascript
    console.log("self.setOption in Utils.mjs", self.setOption)
    ```
    after https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/Utils.mjs#L640
    Insert
    ```javascript
    console.error(err)
    ```
    after https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/Utils.mjs#L649
    ![image-byteArrayToUtf8](https://user-images.githubusercontent.com/56472849/232560545-faf11a74-d0a0-4a8d-be17-0eef69cd1079.png)

4. Insert `console.log("ChefWorker Loading")` and `console.log("ChefWorker Loaded")` into the head and the end of file [`src/core/ChefWorker.js`](https://github.com/gchq/CyberChef/blob/master/src/core/ChefWorker.js) respectively
    ![image-chefworker](https://user-images.githubusercontent.com/56472849/232560730-21ad4d23-419b-4cba-a40e-5e34fb5cb2ba.png)

5. Visit http://localhost:8080/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)&input=NXJXTDZLK1Y1cGFINXB5cw

## Reproduced Screenshots

![reproduced -screenshots](https://user-images.githubusercontent.com/56472849/232561884-5880d3e6-fbf9-4f83-b987-37b995134f58.png)

## Possible Courses

The calling stack is from `eval`

![courses-stack](https://user-images.githubusercontent.com/56472849/232564602-18b18357-1884-401d-80a7-810ef63d26e4.png)

And `Utils.mjs` didn't preload `ChefWorker`. See:

https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/ChefWorker.js#L9
https://github.com/gchq/CyberChef/blob/1bc88728f04135aa99f4126e839d62cc8291056b/src/core/Chef.mjs#L10

Then `ChefWorker.js` defines `self.xxx`. But at the very beginning, `self` of functions in `Utils.mjs` doesn't has method `xxx`, it's declared after quoting and running `Utils.mjs`!

```plain
1. [eval] call baking...
2. loading ChefWorker
3. set self.setOptions
4. ChefWorker loaded
5. [eval] call self.setOptions
6. [eval] bake complete
```

`self` in eval is delivered from 1.

## Desktop

 - **Sever OS:** Ubuntu 22.10
 - **Browser OS:** Windows 11
 - **Browser:** Edge 114.0.1788.0 Dev
 - **CyberChef Version:** 10.4.0

## Addition

This way it will display normally:

![addition-code](https://user-images.githubusercontent.com/56472849/232562960-6fde7d1e-427c-42e6-8b6b-a2942d67dcc1.png)

But it didn't disable highlighting:

![addition-screenshot](https://user-images.githubusercontent.com/56472849/232563683-dd9005d8-1ce8-4fdc-9445-161603962b6c.png)

**Comment by Raka-loah** [comment]
This is the new `output character encoding` feature in v10, by default it will be set to `Raw Bytes` so it will show UTF-8 characters in raw byte format. You can simply click `Raw Bytes` in the status bar of Output Panel and set it to `UTF-8`.

**Comment by all1ta** [comment]
You must change charset/encoding.

![image](https://github.com/gchq/CyberChef/assets/6318198/52b5a332-ba64-4ce7-af12-f15ea5c53ba2)

**Comment by Cnily03** [comment]
thank you.
