### ISSUE TITLE
Cyberchef - Snapcraft

### ISSUE THREAD

**Issue by Flagelmann** [gchq/CyberChef#1588]
Hello all,

just few several questions about installing Cyberchef using Snapcraft:

- Is there a way to check and start the web interface of Cyberchef, after installing/downloading it with snap?
- Is there any documentation about it?
- I see that, after installing it with snap on a Raspberry Pi, there is a "cyberchef" command line available, but again, no info about the syntax to use or available. Again, is there any documentation of it or is it all trial an error?

P.S: in addition, if this will ever work installing it with snap, what is the default URL (with or without custom port) to access it (if any)?

Many thanks

**Comment by a3957273** [comment]
I have no information about a snap version of CyberChef.  You'd likely have to contact the Snap / Canonical team about that.

**Comment by a3957273** [comment]
But note that installing it yourself is super easy.

1. Go to our latest release: https://github.com/gchq/CyberChef/releases/tag/v10.17.0
2. Download the 'CyberChef_v10.17.0.zip' file.
3. Unzip it, and open 'CyberChef_v10.17.0.html'.

Tada, a working local copy of CyberChef!
