### ISSUE TITLE
HTML entity decoder is buggy

### ISSUE THREAD

**Issue by mathiasbynens** [gchq/CyberChef#16]
HTML-encoded astral Unicode symbols are incorrectly decoded.

E.g. `&#x1D306;` becomes `팆` instead of `𝌆`.

https://gchq.github.io/CyberChef/?recipe=%5B%7B"op"%3A"From%20HTML%20Entity"%2C"args"%3A%5B%5D%7D%5D&input=Zm9vICYjeDFEMzA2OyBiYXI

Perhaps you could use https://github.com/mathiasbynens/he for HTML entity encoding/decoding.

**Comment by n1474335** [comment]
Linked to #15 and fixed in #155.
