### ISSUE TITLE
Bug report: Decode text is damage

### ISSUE THREAD

**Issue by whwlsfb** [gchq/CyberChef#1608]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

use this recipe
`#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)Decode_text('Simplified%20Chinese%20GB18030%20(54936)')&input=dWY2NS9ybis`
on CyberChef V9.55.0, would output correctly "哈哈哈"，on V10.5.2(latest)，output error text "ååå"

**Expected behaviour**
This feature should be fallback to an earlier version.

**Screenshots**

N/A

**Desktop (if relevant, please complete the following information):**
 - OS: Windows
 - Browser: Chrome 115.0.5790.131
 - CyberChef version: [e.g. 10.0 and newer, including newest 10.5.2]

**Additional context**

N/A

**Comment by whwlsfb** [comment]
> Hey, I want to work on this, can you share screenshots or provide link where exaclty the bug is I am finding it difficult being a beginner Thanks

ok!, screenshots in here，but link is localfile.


<img width="1134" alt="20230812085701" src="https://github.com/gchq/CyberChef/assets/8212964/d2f66ea9-9c9d-4117-96df-744cdc970b8f">

**Comment by GoForceX** [comment]
Hi, it is likely not a bug, but a "**feature**" introduced in v10.

According to [CHANGELOG](https://github.com/gchq/CyberChef/blob/master/CHANGELOG.md#1000---2023-03-22)

> Character encoding selection added to the Input and Output

Which means the default encoding used will be **Raw Bytes**.

![图片](https://github.com/gchq/CyberChef/assets/67143590/272006ec-3159-408c-aaf0-3036856694fb)

You can change this setting at the bottom-right corner to whatever encoding you want, including GB18030.

**Comment by whwlsfb** [comment]
> Hi, it is likely not a bug, but a "**feature**" introduced in v10.
> 
> According to [CHANGELOG](https://github.com/gchq/CyberChef/blob/master/CHANGELOG.md#1000---2023-03-22)
> 
> > Character encoding selection added to the Input and Output
> 
> Which means the default encoding used will be **Raw Bytes**.
> 
> ![图片](https://private-user-images.githubusercontent.com/67143590/304685905-272006ec-3159-408c-aaf0-3036856694fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTYwMjgsIm5iZiI6MTcwODY1NTcyOCwicGF0aCI6Ii82NzE0MzU5MC8zMDQ2ODU5MDUtMjcyMDA2ZWMtMzE1OS00MDhjLWFhZjAtMzAzNjg1NjY5NGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NDZkM2FhZmMwZWU3MGJhYmFmMmQ4Y2Q4YjE5YjYwNDM4M2ExZWJkMDhkYTdiOTg2NzhhZGU5Y2JlYzRiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ce-ilG5K3qX1zbWrDapSC5nNWgMAbIDP8uBEpXEIYD4)
> 
> You can change this setting at the bottom-right corner to whatever encoding you want, including GB18030.

Okay, forgive my negligence. Thank you for reminding me!
