### ISSUE TITLE
Feature request: Support zbase32 ecnoding

### ISSUE THREAD

**Issue by BANOnotIT** [gchq/CyberChef#1632]
As a developer working with things encoded I found [zbase32](http://philzimmermann.com/docs/human-oriented-base-32-encoding.txt) encoding very useful. But CyberChef does not support it.

**Describe the solution you'd like**
Support both encoding and decoding of [zbase32](http://philzimmermann.com/docs/human-oriented-base-32-encoding.txt)

**Comment by corgeman** [comment]
It does, you just have to set the alphabet in 'From Base32' to zbase32's, `ybndrfg8ejkmcpqxot1uwisza345h769`. Like so:
https://gchq.github.io/CyberChef/#recipe=From_Base32('ybndrfg8ejkmcpqxot1uwisza345h769',true)&input=cHR6czY0M2I
