### ISSUE TITLE
Bug report: testui keep failing with Chromedriver version error

### ISSUE THREAD

**Issue by jpledref** [gchq/CyberChef#1638]
**Describe the bug**
UI tests with nightwatch fail by raising this message:
```
message: 'session not created: This version of ChromeDriver only supports Chrome version 114\n' +
         'Current browser version is 117.0.5938.88 with binary path /usr/bin/google-chrome',
```

This issue may block the merge of PRs. (See #1631 #1626 #1623)

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Create a new PR (or trigger github actions again)
2. pull_request jobs will run and this error will be shown

**Expected behaviour**
A job ending with a success.

**Screenshots**
![image](https://github.com/gchq/CyberChef/assets/37375827/c624257e-fbe0-461f-b5b9-13a0ea738981)

**Additional context**

The problem comes from an incompatibility between chromedriver npm package version and installed chromium version into the runner. Into [pull_requests.yml](.github/workflows/pull_requests.yml), **ubuntu-latest** image is used.

=> We shall either pin this ubuntu version or install a pinned version of chromium into the job. Upgrading periodically chromedriver will tire us out.

**Comment by a3957273** [comment]
Fixed in #1700
