### ISSUE TITLE
Bug report: Version checking is broken.

### ISSUE THREAD

**Issue by mrcbax** [gchq/CyberChef#1640]
**Describe the bug**
CC seems to not want to load on high version number browsers. If you paid attention to your eslint outputs you'd find the issue plain as day: 
```
Running "eslint:configs" (eslint) task
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Try to load the page
2. ...
3. ...

**Expected behaviour**
The page loads.

**Screenshots**
![image](https://github.com/gchq/CyberChef/assets/5545218/7a216732-0efd-440e-9266-ac08da52e651)

**Desktop (if relevant, please complete the following information):**
 - OS: Linux
 - Browser: Firefox Developer Edition 119.0b5
 - CyberChef version: 10.5.2

**Additional context**
```
TypeError: can't access property "addEventListener", document.querySelector(...) is null
Filename: https://cyberchef.doslabelectronics.com/assets/main.js
Line: 19
Column: 688018
Error: TypeError: can't access property "addEventListener", document.querySelector(...) is null
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
CyberChef version: 10.5.2
```

How about the CyberChef project moves to "best effort" loading instead of flat out refusing to load.

**Comment by a3957273** [comment]
Resolved in #1700
