### ISSUE TITLE
url decode 中文显示乱码

### ISSUE THREAD

**Issue by dev4mobile** [gchq/CyberChef#1646]
url decode 中文显示乱码

![image](https://github.com/gchq/CyberChef/assets/6851386/062a6bb3-9ed0-4e56-b8be-a9f85cf1727a)

**Comment by shinohara-rin** [comment]
# What probably happened

![image](https://github.com/gchq/CyberChef/assets/25588514/e74483c2-13de-44bb-8da1-aa5f7370be4e)
By default, cyberchef shows the output as raw bytes

# How to solve this problem

![2](https://github.com/gchq/CyberChef/assets/25588514/896fba43-1587-4320-9bdc-c36637bf269d)
You can click on the encoding to choose a proper encoding for your output

**Comment by dev4mobile** [comment]
ok, thx
