### ISSUE TITLE
Feature Request: Jscript.Encode Decoder

### ISSUE THREAD

**Issue by schrodyn** [gchq/CyberChef#165]
### Summary
Request to add a feature to decode Javascript encoded with https://en.wikipedia.org/wiki/JScript.Encode

### Example
https://www.cylance.com/en_us/blog/threat-spotlight-the-truth-about-fileless-malware.html

### Possible solutions
C implementation for reference:

https://gist.github.com/bcse/1834878

**Comment by n1474335** [comment]
Closed by #183
