### ISSUE TITLE
Misc: What am I doing wrong?

### ISSUE THREAD

**Issue by Bussy5429** [gchq/CyberChef#1652]
Whenever I try to put unicode values through the unescape unicode command for some reason I get garble that I can't turn into actual text as required. Could anyone tell me what I am doing wrong? See attached photo.
![Screenshot 2023-11-13 171648](https://github.com/gchq/CyberChef/assets/150716553/a8282ad5-c9ad-4fb5-9050-925e64cefb52)

**Comment by corgeman** [comment]
At the bottom right of your screen, the text encoding needs to be changed from "Raw Bytes" to "UTF-8".

**Comment by a3957273** [comment]
Closing this, as @corgeman have given the correct answer! 👍
