### ISSUE TITLE
Bug report: Skynet Initialisation

### ISSUE THREAD

**Issue by AK47-2020** [gchq/CyberChef#1662]
**Describe the bug**
In the **"initialising Skynet"** phase, the power went down in the building.

**To Reproduce**
Refresh/upload Cyberchef using a low bandwidth internet connection.

**Expected behaviour**
Normal power consumption in the building.

**Screenshots**
SPECTRE employees are not allowed to provide screenshots of the office building.

**Desktop (if relevant, please complete the following information):**
 - OS: Windows 95 (prior to Skynet deployment)
 - Browser: firechromera 6.6.6 "inferno"
 - CyberChef version: cooked

**Additional context**
Switch to 3V devices for Skynet?

**Comment by a3957273** [comment]
Please report this to your local [Cyberdyne Systems](https://en.wikipedia.org/wiki/Skynet_(Terminator)) success associate to resolve this.

<sub>This is a joke.  Closing this ticket.</sub>

**Comment by AK47-2020** [comment]
Cyberdyne went bankrupt because of Brexit (out of electronic components)!
