### ISSUE TITLE
Bug report: Malicious Help Link in Extra Files Section

### ISSUE THREAD

**Issue by Taikor-coder** [gchq/CyberChef#1668]
**Describe the bug**
The following link is present in the ExtractFiles.mjs-  "https(colon)//forensicswiki(dot)xyz/wiki/index.php?title=File_Carving" it is currently redirecting users to randomized malicious sites including scam/malware/downloaders etc.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Extra files Section
2. Click the more info/help link

**Expected behaviour**
linking to a non malicious domain with actual help information. Something more like this " https://forensics.wiki/file_carving/ "

Cheers

**Comment by a3957273** [comment]
Fixed in https://github.com/gchq/CyberChef/pull/1701
