### ISSUE TITLE
My deep link is not working

### ISSUE THREAD

**Issue by Rooby8383** [gchq/CyberChef#1691]
**Describe the bug**
The deeplink is not generating well

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

**Expected behaviour**

**Screenshots**

**Desktop (if relevant, please complete the following information):**
 - OS: [e.g. Windows] 
 - Browser: [e.g. chrome 72, firefox 60]
 - CyberChef version: [e.g. 9.7.14]

**Additional context**

**Comment by a3957273** [comment]
Hey, are you able to fill out the rest of the issue template?  Your ticket is not clear.  Are you talking about an Android deeplink?

**Comment by a3957273** [comment]
Ah, I assume you're talking about links of the `https://gchq.github.io/CyberChef/#recipe=Operation()&input=`.  If so, can you give an example link that doesn't work for you?  The feature seems to continue to work for me.
