### ISSUE TITLE
Folder folding is not working in Firefox

### ISSUE THREAD

**Issue by PatrLind** [gchq/CyberChef#1707]
**Describe the bug**
Folder folding is not working in Firefox

**To Reproduce**

1. Using Firefix, go to https://gchq.github.io/CyberChef/#recipe=JSON_Beautify('%20%20%20%20',false,true)&input=eyJTdWIxMSI6eyJTdWIxMiI6eyJLZXkxMSI6IlZhbHVlMTEifX0sIlN1YjIxIjp7IlN1YjIyIjp7IktleTIxIjoiVmFsdTIxIn19fQ
2. Click on the arrows to fold a sub tree
3. Notice it doesn't fold

**Expected behaviour**
The folders should fold (hide) the same way as they do in Chrome.

**Desktop (if relevant, please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser: Firefox 122.0, Chomium 121.0.6167.139
 - CyberChef version: 10.6.0

**Comment by a3957273** [comment]
This issue seems easily reproducible, thanks for the clear bug report! :)

**Comment by GoForceX** [comment]
Changing

```
.json-summary {
    display: contents;
}
```

into 

```
.json-summary {
    display: inline;
    list-style: none;
}
```

works on my side in Firefox and Edge.

If this works, I will be happy to create a pull request.
