### ISSUE TITLE
Bug report: v10.8.1

### ISSUE THREAD

**Issue by huyz** [gchq/CyberChef#1717]
**Describe the bug**
Incorrect release asset version number

**To Reproduce**

1. Go to https://github.com/gchq/CyberChef/releases
2. Look at assets under  v10.8.1 

**Expected behaviour**
Obvious

**Screenshots**
![screenshot 2024-02-13T071453Z](https://github.com/gchq/CyberChef/assets/128394/31605c04-9e58-409f-95a8-e0b1fe423fad)

**Comment by a3957273** [comment]
Our releases are added automatically by GitHub Actions, I don't even know how this can happen! 😕

**Comment by huyz** [comment]
Must be a GitHub action bug: because 10.8.1 came out so soon after 10.8.0, workspaces collided?

**Comment by a3957273** [comment]
Fixed now, apologies for the issue @oh2fih .
