### ISSUE TITLE
Bug report: base64 encode/decode with emoji

### ISSUE THREAD

**Issue by codexss** [gchq/CyberChef#1755]
* Version: 10.8.2
* Compile time: 22/02/2024 01:17:08 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=To_Base64('A-Za-z0-9%2B/%3D')From_Base64('A-Za-z0-9%2B/%3D',false,false/disabled)From_Base64('A-Za-z0-9%2B/%3D',true,false)&input=8J%2BqmfCfjKHvuI/wn5Of8J%2BTiPCfjqg)

**Comment by Suyun114** [comment]
Just set the encoding from `Raw Bytes` to `UTF-8` in the bottom-right corner.
