### ISSUE TITLE
Releases v10.12.1 and v10.12.0 don't have a proper zip files

### ISSUE THREAD

**Issue by huyz** [gchq/CyberChef#1760]
**Describe the bug**
The Zip files for the last 2 releases are missing

**To Reproduce**
Go to https://github.com/gchq/CyberChef/releases/

![screenshot 2024-03-29T135420Z](https://github.com/gchq/CyberChef/assets/128394/8cecce8f-901d-4c9e-a62b-ca60df91bd03)

**Additional context**
Similar to https://github.com/gchq/CyberChef/issues/1717

**Comment by oh2fih** [comment]
Similar to recent https://github.com/gchq/CyberChef/issues/1717

The automation should be revised as it regularly makes mistakes.

**Comment by a3957273** [comment]
Read through the existing pipelines and found out I was releasing in the wrong way.  Pushing a tag seems to automatically trigger the creation of the 'release' artifact.

Apologies for any downstream issues people have been seeing! :)
