### ISSUE TITLE
Operation request: Convert JSON Web Key (JWK) from/to PEM

### ISSUE THREAD

**Issue by cplussharp** [gchq/CyberChef#1794]
## Summary
Convert a Public or Private Key provided as PEM into a JSON Web Key.
Convert a JSON Web Key to the corresponding PEM version

### Example Input
1: PublicKey PEM or PrivateKey PEM 
2: JSONWebKey

### Example Output
1: JSONWebKey
2: PublicKey PEM or PrivateKey PEM

**Comment by a3957273** [comment]
Closed by https://github.com/gchq/CyberChef/pull/1277
