### ISSUE TITLE
Feature request: Line operations

### ISSUE THREAD

**Issue by PatrLind** [gchq/CyberChef#1809]
**Describe the solution you'd like**
I would like to have the possibility to do line operations. The most simple operation that I needed (but couldn't find) was to remove all empty lines of a text file. 

**Describe alternatives you've considered**
Regex, but it gets complicated fast

**Additional context**
Notepad++ have a nice set of line operations that can be used for inspiration

**Comment by Gunnar50** [comment]
I was looking for something like that last week too, I wanted to convert a multiline text into one line.

I would like to try and contribute to that.

**Comment by Gunnar50** [comment]
Looking a bit deeper on this, there is indeed a operation called Remove whitespace that can be used to remove empty lines.

**Comment by PatrLind** [comment]
Oh, you are right! I didn't see that one, Thanks!
And sorry for the unnecessary feature request

**Comment by levid0s** [comment]
Sorry, how can the "Remove whitespace" operation be used to remove all empty lines?

example:
```
hello

world


hi
```
==>
```
hello
world
hi
```

I only know about this solution for removing empty lines: https://ittavern.com/cyberchef-how-to-remove-empty-lines/

**Comment by PatrLind** [comment]
When I closed this task I was sure it was possible to do what you want to do, but now that I tried it again it seems it's not possible.
If someone can confirm this is the case, I think I should reopen this again because it's a common task I think.
