### ISSUE TITLE
Bug report: <Insert title here>

### ISSUE THREAD

**Issue by mscroggi** [gchq/CyberChef#1833]
**Describe the bug**
I upgraded from 9.55.0 to the latest 10.18.8
upon loading the page I am now getting this - 
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
I am using a chrome based browser - Vivaldi.

**To Reproduce**
Access the latest package in the browser

**Expected behaviour**
cyberchef worked for me in an older version.  

**Desktop (if relevant, please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser: Vivaldi 
 - CyberChef version: 10.18.8
 - Your user agent is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Additional context**
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
Filename: https://asttools.gtl.net/tools/cyberchef/assets/main.js
Line: 2
Column: 5243064
Error: TypeError: Cannot read properties of null (reading 'addEventListener')
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
CyberChef version: 10.18.8

**Comment by suraj-9849** [comment]
I would like to work on this Issue. please assign this to me..

**Comment by n1474335** [comment]
Vivaldi is not one of our [supported browsers](https://github.com/gchq/CyberChef?tab=readme-ov-file#browser-support), sorry.
