### ISSUE TITLE
Bug report: Save to file not working in Edge browser

### ISSUE THREAD

**Issue by RickZeeland** [gchq/CyberChef#184]
### Summary
Save to file not working in Edge browser, but it works in Chrome.

### Environment
Windows 10 Pro
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by n1474335** [comment]
This seems to be a known bug in Microsoft Edge as reported here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4282810/

It's not clear when it will be fixed, but there's not a lot we can do about it unfortunately.
