### ISSUE TITLE
Misc: Bundlesize plugin

### ISSUE THREAD

**Issue by tlwr** [gchq/CyberChef#189]
I came across [siddharthkp/bundlesize](https://github.com/siddharthkp/bundlesize) in my GH feed. It allows you to cap the size of your project's bundled artifacts, either for use in CLI scripts, or in a CI pipeline.

For example (from their readme):
![](https://camo.githubusercontent.com/d3906ea9d5a3dcfd57d1d9ea4b87dc799910fd03/68747470733a2f2f63646e2e7261776769742e636f6d2f7369646468617274686b702f62756e646c6573697a652f6d61737465722f6172742f7374617475732e706e67)

Given that everything goes through Travis, and we've frequently discussed artifact sizes, it would make sense for us to have a helper that clarified the current situation. I think bundlesize would be a good solution.

If we want this added then I'll do it and make a PR.

**Comment by n1474335** [comment]
@tlwr Good suggestion. There is also [Size Limit](https://evilmartians.com/chronicles/size-limit-make-the-web-lighter) which is an npm module that we could work into the build process.

I think there is a lot to be gained from analysing our dependencies, but I don't really want to enforce a hard size limit. Depending on the benefits, a large set of dependencies might be worth it. I would rather build an architecture that allows for lots of dependencies but doesn't load them all at once, like the module system in #173. It would be good to run these size tests over each of the compiled modules though, as they may be importing more than they need.

Let's wait until #173 is merged and then look into this.

**Comment by n1474335** [comment]
I'm going to close this for now as I don't want to restrict module sizes at the moment. Code weight is still an important aspect for this project, but I don't want to set specific limits. Each new library needs to be considered on its merits.
