### ISSUE TITLE
Suggestion/Enhancement: Auto-deploy gh-pages on commit to master

### ISSUE THREAD

**Issue by WrathZA** [gchq/CyberChef#19]
It's likely worthwhile to keep the live demo inline with the master branch.

Based off of some quick research, the preferred mechanism seems to leverage travis-ci

Links:
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example

**Comment by n1474335** [comment]
I've added a Grunt task which pushes the `build/prod` directory to the `gh-pages` branch. It's not a full solution to this but it makes it a lot easier than previously. This may be revisited in future but I'll close it for now.
