### ISSUE TITLE
Bug report: regexps does not respect non capturing groups

### ISSUE THREAD

**Issue by Jiehong** [gchq/CyberChef#1948]
**Describe the bug**
When given a regexp with a non capturing group, the group is shown as a capture group

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Go to https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5E%5C%5Cd(:?%5C%5C.%5C%5Cd)$',true,true,false,false,false,false,'List%20matches%20with%20capture%20groups')&input=MS4x
2. select 'List matches with capture groups'
3. see Group 1 containing '.1' as a matched value

**Expected behaviour**

The input regexp is `^\d(:?\.\d)$`, which contains 4 parts:

1. `^`: match beginning of string
2. `\d`: match a single digit
3. `(:?\.\d)` non-capturing group matching a dot `.` and a single digit
4. `$`: match the end of string

The non capturing group should not be considered a captured group, and only a full match should be shown for input `1.1`.

The same example works fine in https://regex101.com/ for example.

**Screenshots**
<img width="543" alt="image" src="https://github.com/user-attachments/assets/07a8d156-828e-4069-9afd-6307b054438d">

**Desktop (if relevant, please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox 133 and Safari 18.1.1
 - CyberChef version: 10.19.4

**Additional context**
It seems that named groups are only considered by number, and not by name, but that's another bug (to test, change the regexp to `^\d(?<hello>\.\d)$`)

**Comment by kryptokazz** [comment]
shouldn't it be ^\d(?:\.\d)$ not ^\d(:?\.\d)$ seems you swapped the ? and : by mistake so it won't work as a non capturing group

**Comment by Jiehong** [comment]
> shouldn't it be ^\d(?:.\d)$ not ^\d(:?.\d)$ seems you swapped the ? and : by mistake so it won't work as a non capturing group

You are absolutely correct, and I apologize for not noticing earlier 🤦
