### ISSUE TITLE
Use a modern library management system

### ISSUE THREAD

**Issue by graingert** [gchq/CyberChef#2]
Currently all your libs are manually specified:

https://github.com/gchq/CyberChef/blob/master/Gruntfile.js#L46-L125

This is a DRY violation and a pain to maintain.

Choose a modern module bundler: webpack, rollup, bunch etc: https://webpack.js.org/get-started/why-webpack/#comparison

**Comment by n1474335** [comment]
This will now be the master ticket for library management queries and updates.

Details from #43:

> Library management is something that I hope to improve in the coming months. At the moment, any libraries used in the app itself (as opposed to those used in the build process) should be stored in `src/js/lib` or `src/css/lib` and then added to `Gruntfile.js` to get incorporated into the build.
> 
> Ultimately we'll probably use some sort of bundler like webpack, but there are various considerations to be made before we decide which route to go down.
> 
> I've written up some [Design Principals](https://github.com/gchq/CyberChef/wiki/Contributing#design-principals) and one of them centres around not using too many libraries unless absolutely necessary. If you're going to utilise every feature available in the library, it's probably worthwhile, but if not it can lead to bloat which everyone will have to download even if they never touch that operation. Vanilla JS is preferred if reasonable.

**Comment by graingert** [comment]
Do not store libraries in src/js/lib or src/css/lib this unnecessarily separates file types and keeps the libraries in the code base.  All libraries should go in node_modules and be managed by npm/yarn

**Comment by graingert** [comment]
@n1474335 re design principals underscore_lower_case is not recommended in JavaScript projects.

**Comment by n1474335** [comment]
Completed in #95
