### ISSUE TITLE
Misc: JSON viewer feature request

### ISSUE THREAD

**Issue by dpanic** [gchq/CyberChef#203]
### Summary
Hello it will be good to have JSON viewer for nice UI rendering of JSON, example http://json.parser.online.fr/

**Comment by n1474335** [comment]
There is already a basic [JSON beautifier operation](https://gchq.github.io/CyberChef/#recipe=JSON_Beautify('%20%20%20%20')&input=eyJnbG9zc2FyeSI6eyJ0aXRsZSI6ImV4YW1wbGUgZ2xvc3NhcnkiLCJHbG9zc0RpdiI6eyJ0aXRsZSI6IlMiLCJHbG9zc0xpc3QiOnsiR2xvc3NFbnRyeSI6eyJJRCI6IlNHTUwiLCJTb3J0QXMiOiJTR01MIiwiR2xvc3NUZXJtIjoiU3RhbmRhcmQgR2VuZXJhbGl6ZWQgTWFya3VwIExhbmd1YWdlIiwiQWNyb255bSI6IlNHTUwiLCJBYmJyZXYiOiJJU08gODg3OToxOTg2IiwiR2xvc3NEZWYiOnsicGFyYSI6IkEgbWV0YS1tYXJrdXAgbGFuZ3VhZ2UsIHVzZWQgdG8gY3JlYXRlIG1hcmt1cCBsYW5ndWFnZXMgc3VjaCBhcyBEb2NCb29rLiIsIkdsb3NzU2VlQWxzbyI6WyJHTUwiLCJYTUwiXX0sIkdsb3NzU2VlIjoibWFya3VwIn19fX19), however I agree that it could be improved upon. There are various libraries available if anyone wants to take a look.

**Comment by dpanic** [comment]
This one https://github.com/abodelot/jquery.json-viewer is quite good

**Comment by edwardwall** [comment]
I think this would have to be a new operation.
`JSON Beautify` outputs a string but this would have to output html.

**Comment by n1474335** [comment]
@edwardwall We could use the `present` capability. The `run` function would return a string, but if it's the final operation in the recipe, the `present` function would transform that into full HTML markup. [See here for more details.](https://github.com/gchq/CyberChef/wiki/Adding-a-new-operation#presenting-complex-data)
