### ISSUE TITLE
Operation request: Number parsing and Arithmetic operations

### ISSUE THREAD

**Issue by AndreFlakowski** [gchq/CyberChef#208]
### Summary
After filtering down a text to numbers, add arithmetic operations on the filtered results. to produce a single result output.

I often see textual stats from e. g. CLI output that I want to process a little further to get a mean or a sum.
Possible issues are handling of commutative and associative properties of subtraction division.

### Example
Input:
Bananas: 50 pcs.
Apples: 5 pcs.
Oranges 2.5 pcs.

Recipe: 
Regex(\d+(?:[.,]\d+)*)
New Feature: sum(lines)
or: mean(lines)
or: multiply(lines)
etc.

[Example](https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5C%5Cd%2B(?:%5B.,%5D%5C%5Cd%2B)*',true,true,false,'List%20matches')&input=QmFuYW5hczogNTAgcGNzLgpBcHBsZXM6IDUgcGNzLgpPcmFuZ2VzIDIuNSBwY3Mu)

Hope you find the Idea feasible for CyberChef.

Regards,
André

**Comment by n1474335** [comment]
I would see this as a set of operations that perform arithmetic on the input. The delimiter can be set either as a newline, a comma, a tab etc. in much the same way as the [Unique](https://gchq.github.io/CyberChef/#recipe=Unique('Line%20feed')&input=MQoyCjQKMwozCjIKMQ) operation.

Some operation ideas:
- Sum
- Mean
- Median
- Product (or multiply)

We could even support more statistical functions like standard deviation.

If someone would like to have go at this, it shouldn't be too hard. Perhaps if you've been looking for something easy to get started on, this could be a good candidate. Feel free to ask for help and advice here or in the Gitter chat room: https://gitter.im/gchq/CyberChef

**Comment by n1474335** [comment]
Closed in #215.

[Example](https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5C%5Cd%2B(?:%5B.,%5D%5C%5Cd%2B)*',true,true,false,'List%20matches')Multiply('Line%20feed')&input=QmFuYW5hczogNTAgcGNzLgpBcHBsZXM6IDUgcGNzLgpPcmFuZ2VzIDIuNSBwY3Mu)
