### ISSUE TITLE
Bug report: Can't input square brackets or braces with Icelandic keyboard layout

### ISSUE THREAD

**Issue by Dagur** [gchq/CyberChef#209]
Hi
On an Iceland keyboard you use the following keyboard combinations to write brackets:

- [ AltGr+8
- ] AltGr+9
- { AltGr+7
- } AltGr+0

The german layout is the same I think.
Anyway, when I try to use that in CyberChef, nothing happens. This is annoying when writing regular expressions (I have to copy+paste those symbols)

**Comment by vince-nayal** [comment]
Hi, 

I had the same problem on several layouts using AltGr + Num for special chars.

Cyberchef's default keybinding for shortcuts is Ctrl+Alt and [Windows allows the emulation of AltGr with Ctrl-Alt](https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute). Therefore it seems to hijack the insertion of chars using AltGr+num.

One workaround is to substitute this default binding with the Ctlr+Win in the top right options menu

![image](https://user-images.githubusercontent.com/6689144/44088964-5cdd38ca-9fc5-11e8-99ae-19d1cec9dcc8.png)

**Comment by oppiman** [comment]
Similar problem here with 8.1.4.

I can't input any characters on the German keyboard that need [AltGr]
These are e.g. { [ ] } \

I tested this with W10 and Firefox 61.0. and the "replace" operation
- won't work, even with a fresh FF profile

It does work on Linux MINT and Firefox.
It does work on W10 with Opera.
