### ISSUE TITLE
Bug report: Netbios Decode is broke

### ISSUE THREAD

**Issue by bwhitn** [gchq/CyberChef#211]
### Summary

Netbios decode name spits out garbage and appears to have consistency issues as the string will change with every bake. 

### Example
[(https://gchq.github.io/CyberChef/#recipe=Unescape_string()Decode_NetBIOS_Name(0)&input=XHg0Nlx4NDVceDQ1XHg0Nlx4NDZceDQ0XHg0NVx4NDVceDQ2XHg0NVx4NDVceDQ1XHg0NVx4NDVceDQ2XHg0NFx4NDZceDQ0XHg0Nlx4NDRceDQzXHg0MVx4NDNceDQxXHg0M1x4NDFceDQzXHg0MVx4NDNceDQxXHg0M1x4NDE)]

**Comment by n1474335** [comment]
Fixed in #212
