### ISSUE TITLE
Feature request: Operations request: Multiple extractions

### ISSUE THREAD

**Issue by wurhzwj0dt** [gchq/CyberChef#234]
is there a way to run for example on 1 input 
Extract Email addresses
Extract IP addresses
the output pane would contain IP's and Emails
I would like to run several extract methods on 1 piece of data. 
Currently it would extract emails then look in the emails for IP's doesn't work

**Comment by wurhzwj0dt** [comment]
never mind using fork works had to remove the merge

**Comment by wurhzwj0dt** [comment]
feel free to delete or close this issue/request

**Comment by n1474335** [comment]
Hi @wurhzwj0dt, I'm afraid that currently there is no way to do this, you'll have to run the operations separately.

We may revisit this in future - it could make a good new Flow Control operation. I'll close this for now, but watch this space.
