### ISSUE TITLE
Bug report: can not save output into a file

### ISSUE THREAD

**Issue by SkyCrawl** [gchq/CyberChef#241]
### Summary

* Version: 6.3.0
* Compile time: 28/10/2017 08:00:00 UTC
* User-Agent: 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)Decode_text('UTF-8%20(65001)')&input=TUlJRnFEQ0NCSkNnQXdJQkFnSUVBS25YNmpBTkJna3Foa2lHOXcwQkFRc0ZBRENCdHpFTE1Ba0dBMVVFQmhNQ1Exb3hPakE0QmdOVkJBTU1NVWt1UTBFZ0xTQlJkV0ZzYVdacFpXUWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrc0lEQTVMekl3TURreExUQXJCZ05WQkFvTUpGQnlkbTdEclNCalpYSjBhV1pwYTJIRWpXN0RyU0JoZFhSdmNtbDBZU3dnWVM1ekxqRTlNRHNHQTFVRUN3dzBTUzVEUVNBdElFRmpZM0psWkdsMFpXUWdVSEp2ZG1sa1pYSWdiMllnUTJWeWRHbG1hV05oZEdsdmJpQlRaWEoyYVdObGN6QWVGdzB4TmpBMU1EUXhNVEU0TkRkYUZ3MHhOekExTURReE1URTRORGRhTUg0eEN6QUpCZ05WQkFZVEFrTmFNUjB3R3dZRFZRUUREQlJKYm1jdUlGSmhaRzl0dzYxeUlNV2dhVzFsYXpFM01EVUdBMVVFQ2d3dVRXbHVhWE4wY25rZ2IyWWdkR2hsSUVsdWRHVnlhVzl5SUc5bUlIUm9aU0JEZW1WamFDQlNaWEIxWW14cFl6RVhNQlVHQTFVRUJSTU9TVU5CSUMwZ01UQXpOekUyT1RFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNUK0JOV0RoUXdDZGVzdE1sb21Dck1yZHE0Nm8yV05WcVZEZXJsbFp3TGQ0WjdzL1NqaXB0SjlRRlFoclIzeE10SWFnNHQ4VUE4RURMK1VxRWZpdUxOd3lxSXFhdWNCNW1SdXprVXNsaFFuTGR1RkZUMXRzWUdYTjVKb3FTbkUrTGxvTEhQV2NGZ1BrUi9oRksvR0pGbmJPYnJqWGZFSGFRRTlMdTlQWkZyUHVpY0pRVytydDlGbjFEa0JQd0pnWktlakJYRmtOUFBKKzg2TnBSN2t3b2phL3NFNjI2TDlCSjk5ejdtckFGbmNzMjY1Y0RjbnZaa0NDNGdoZ2NveHlZdTlSMkVVU0pXQnBDL1J4Y3l0NzdnUjJYZXVqaWgwcUplb0JqYVdsamNZUkUrTTh3c25BcWlJYkl6SlJvTGYvMnRLZUg4T1ZRUGZGRnZMOGJhSjloSkFnTUJBQUdqZ2dIeU1JSUI3akFSQmdOVkhTVUVDakFJQmdZRUFKRTNBd0F3Z2Q4R0ExVWRJQVNCMXpDQjFEQ0IwUVlOS3dZQkJBR0J1RWdCQVI0REFUQ0J2ekNCdkFZSUt3WUJCUVVIQWdJd2dhOGFnYXhVWlc1MGJ5QnJkbUZzYVdacGEyOTJZVzU1SUdObGNuUnBabWxyWVhRZ2FtVWdkbmxrWVc0Z2NHOWtiR1VnZW1GcmIyNWhJRU5sYzJ0bElISmxjSFZpYkdscmVTQmpMaUF5TWpjdk1qQXdNQ0JUWWk0Z2RpQndiR0YwYm1WdElIcHVaVzVwTDFSb2FYTWdhWE1nY1hWaGJHbG1hV1ZrSUdObGNuUnBabWxqWVhSbElHRmpZMjl5WkdsdVp5QjBieUJEZW1WamFDQkJZM1FnVG04dUlESXlOeTh5TURBd0lFTnZiR3d1TUlHQkJnTlZIUjhFZWpCNE1DYWdKS0FpaGlCb2RIUndPaTh2Y1dOeWJHUndNUzVwWTJFdVkzb3ZjV2xqWVRBNUxtTnliREFtb0NTZ0lvWWdhSFIwY0RvdkwzRmpjbXhrY0RJdWFXTmhMbU42TDNGcFkyRXdPUzVqY213d0pxQWtvQ0tHSUdoMGRIQTZMeTl4WTNKc1pIQXpMbWxqWVM1amVpOXhhV05oTURrdVkzSnNNQWtHQTFVZEV3UUNNQUF3RGdZRFZSMFBBUUgvQkFRREFnWkFNQmdHQ0NzR0FRVUZCd0VEQkF3d0NqQUlCZ1lFQUk1R0FRRXdId1lEVlIwakJCZ3dGb0FVZWN2UUkrazZaM0NSZEUvVFVlTGdJUDNoS1Bzd0hRWURWUjBPQkJZRUZCSW9WR3ZucldXM3BNcWtFY0ZyUmd6dWcyeWZNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNOTXBBaW00cUFsU3BHdGR0Mk45c0Rkc3hCRHlCVTdHR0hBcWQ4Z2dySnVPUDNpL2daVkZBL1RYNks1VUQ1aWlsWTFKU3VFcXVuOTVHRTRpcC8ySnVJSTNsa1FPMkhxR1NyczdvbWtOME9vZWdOT256WVRFSFRERHIxTTJZSStLejR5RlBUTVZDTkpQenJteTFWWDlxY2ZLb1VoL0YzdTEvcXhlY0lHTWdzYlFUOVd6RjJDY1NRc0F0QmswUlpuajFqeXNQTXFTSm1Ycm1PTzVkVlhHemxqR2V1N3JBTUttclQwenFSSiszaFluOXlQbWhLb1MrZjJyblRwTGs0Z25ZSGQ1VFhjekJkNVl2OFBNb0NVeWRiamc2ZTZ0ZGxtNWJQREhnTFJrcGlVVm9YYi9mR1pTVmtoa2gwUFhtTW1oR1lsRUhIZWRsNGl6UDFjZ1h2ZnM4WA)

Recipe:
1. From Base64
2. Decode text (as UTF-8)
3. Input:
```
MIIFqDCCBJCgAwIBAgIEAKnX6jANBgkqhkiG9w0BAQsFADCBtzELMAkGA1UEBhMCQ1oxOjA4BgNVBAMMMUkuQ0EgLSBRdWFsaWZpZWQgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHksIDA5LzIwMDkxLTArBgNVBAoMJFBydm7DrSBjZXJ0aWZpa2HEjW7DrSBhdXRvcml0YSwgYS5zLjE9MDsGA1UECww0SS5DQSAtIEFjY3JlZGl0ZWQgUHJvdmlkZXIgb2YgQ2VydGlmaWNhdGlvbiBTZXJ2aWNlczAeFw0xNjA1MDQxMTE4NDdaFw0xNzA1MDQxMTE4NDdaMH4xCzAJBgNVBAYTAkNaMR0wGwYDVQQDDBRJbmcuIFJhZG9tw61yIMWgaW1lazE3MDUGA1UECgwuTWluaXN0cnkgb2YgdGhlIEludGVyaW9yIG9mIHRoZSBDemVjaCBSZXB1YmxpYzEXMBUGA1UEBRMOSUNBIC0gMTAzNzE2OTEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCT+BNWDhQwCdestMlomCrMrdq46o2WNVqVDerllZwLd4Z7s/SjiptJ9QFQhrR3xMtIag4t8UA8EDL+UqEfiuLNwyqIqaucB5mRuzkUslhQnLduFFT1tsYGXN5JoqSnE+LloLHPWcFgPkR/hFK/GJFnbObrjXfEHaQE9Lu9PZFrPuicJQW+rt9Fn1DkBPwJgZKejBXFkNPPJ+86NpR7kwoja/sE626L9BJ99z7mrAFncs265cDcnvZkCC4ghgcoxyYu9R2EUSJWBpC/Rxcyt77gR2Xeujih0qJeoBjaWljcYRE+M8wsnAqiIbIzJRoLf/2tKeH8OVQPfFFvL8baJ9hJAgMBAAGjggHyMIIB7jARBgNVHSUECjAIBgYEAJE3AwAwgd8GA1UdIASB1zCB1DCB0QYNKwYBBAGBuEgBAR4DATCBvzCBvAYIKwYBBQUHAgIwga8agaxUZW50byBrdmFsaWZpa292YW55IGNlcnRpZmlrYXQgamUgdnlkYW4gcG9kbGUgemFrb25hIENlc2tlIHJlcHVibGlreSBjLiAyMjcvMjAwMCBTYi4gdiBwbGF0bmVtIHpuZW5pL1RoaXMgaXMgcXVhbGlmaWVkIGNlcnRpZmljYXRlIGFjY29yZGluZyB0byBDemVjaCBBY3QgTm8uIDIyNy8yMDAwIENvbGwuMIGBBgNVHR8EejB4MCagJKAihiBodHRwOi8vcWNybGRwMS5pY2EuY3ovcWljYTA5LmNybDAmoCSgIoYgaHR0cDovL3FjcmxkcDIuaWNhLmN6L3FpY2EwOS5jcmwwJqAkoCKGIGh0dHA6Ly9xY3JsZHAzLmljYS5jei9xaWNhMDkuY3JsMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgZAMBgGCCsGAQUFBwEDBAwwCjAIBgYEAI5GAQEwHwYDVR0jBBgwFoAUecvQI+k6Z3CRdE/TUeLgIP3hKPswHQYDVR0OBBYEFBIoVGvnrWW3pMqkEcFrRgzug2yfMA0GCSqGSIb3DQEBCwUAA4IBAQCNMpAim4qAlSpGtdt2N9sDdsxBDyBU7GGHAqd8ggrJuOP3i/gZVFA/TX6K5UD5iilY1JSuEqun95GE4ip/2JuII3lkQO2HqGSrs7omkN0OoegNOnzYTEHTDDr1M2YI+Kz4yFPTMVCNJPzrmy1VX9qcfKoUh/F3u1/qxecIGMgsbQT9WzF2CcSQsAtBk0RZnj1jysPMqSJmXrmOO5dVXGzljGeu7rAMKmrT0zqRJ+3hYn9yPmhKoS+f2rnTpLk4gnYHd5TXczBd5Yv8PMoCUydbjg6e6tdlm5bPDHgLRkpiUVoXb/fGZSVkhkh0PXmMmhGYlEHHedl4izP1cgXvfs8X
```

### Example

With the above setup, I can not save the output into a file. When I open the web console, it says:
```
URIError: malformed URI sequence [Learn More]          main.js:5106:43
parse                                                  http://icyberchef.com/main.js:5106:43
strToUtf8ByteArray                                     http://icyberchef.com/main.js:20267:25
strToByteArray                                         http://icyberchef.com/main.js:20248:33
toBase64                                               http://icyberchef.com/main.js:20420:20
OutputWaiter.prototype.saveClick                       http://icyberchef.com/main.js:52223:16
<anonymous>                                            self-hosted:951:17
```

**Comment by n1474335** [comment]
Hi @SkyCrawl,

This [works](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)Decode_text('UTF-8%20(65001)')&input=TUlJRnFEQ0NCSkNnQXdJQkFnSUVBS25YNmpBTkJna3Foa2lHOXcwQkFRc0ZBRENCdHpFTE1Ba0dBMVVFQmhNQ1Exb3hPakE0QmdOVkJBTU1NVWt1UTBFZ0xTQlJkV0ZzYVdacFpXUWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrc0lEQTVMekl3TURreExUQXJCZ05WQkFvTUpGQnlkbTdEclNCalpYSjBhV1pwYTJIRWpXN0RyU0JoZFhSdmNtbDBZU3dnWVM1ekxqRTlNRHNHQTFVRUN3dzBTUzVEUVNBdElFRmpZM0psWkdsMFpXUWdVSEp2ZG1sa1pYSWdiMllnUTJWeWRHbG1hV05oZEdsdmJpQlRaWEoyYVdObGN6QWVGdzB4TmpBMU1EUXhNVEU0TkRkYUZ3MHhOekExTURReE1URTRORGRhTUg0eEN6QUpCZ05WQkFZVEFrTmFNUjB3R3dZRFZRUUREQlJKYm1jdUlGSmhaRzl0dzYxeUlNV2dhVzFsYXpFM01EVUdBMVVFQ2d3dVRXbHVhWE4wY25rZ2IyWWdkR2hsSUVsdWRHVnlhVzl5SUc5bUlIUm9aU0JEZW1WamFDQlNaWEIxWW14cFl6RVhNQlVHQTFVRUJSTU9TVU5CSUMwZ01UQXpOekUyT1RFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNUK0JOV0RoUXdDZGVzdE1sb21Dck1yZHE0Nm8yV05WcVZEZXJsbFp3TGQ0WjdzL1NqaXB0SjlRRlFoclIzeE10SWFnNHQ4VUE4RURMK1VxRWZpdUxOd3lxSXFhdWNCNW1SdXprVXNsaFFuTGR1RkZUMXRzWUdYTjVKb3FTbkUrTGxvTEhQV2NGZ1BrUi9oRksvR0pGbmJPYnJqWGZFSGFRRTlMdTlQWkZyUHVpY0pRVytydDlGbjFEa0JQd0pnWktlakJYRmtOUFBKKzg2TnBSN2t3b2phL3NFNjI2TDlCSjk5ejdtckFGbmNzMjY1Y0RjbnZaa0NDNGdoZ2NveHlZdTlSMkVVU0pXQnBDL1J4Y3l0NzdnUjJYZXVqaWgwcUplb0JqYVdsamNZUkUrTTh3c25BcWlJYkl6SlJvTGYvMnRLZUg4T1ZRUGZGRnZMOGJhSjloSkFnTUJBQUdqZ2dIeU1JSUI3akFSQmdOVkhTVUVDakFJQmdZRUFKRTNBd0F3Z2Q4R0ExVWRJQVNCMXpDQjFEQ0IwUVlOS3dZQkJBR0J1RWdCQVI0REFUQ0J2ekNCdkFZSUt3WUJCUVVIQWdJd2dhOGFnYXhVWlc1MGJ5QnJkbUZzYVdacGEyOTJZVzU1SUdObGNuUnBabWxyWVhRZ2FtVWdkbmxrWVc0Z2NHOWtiR1VnZW1GcmIyNWhJRU5sYzJ0bElISmxjSFZpYkdscmVTQmpMaUF5TWpjdk1qQXdNQ0JUWWk0Z2RpQndiR0YwYm1WdElIcHVaVzVwTDFSb2FYTWdhWE1nY1hWaGJHbG1hV1ZrSUdObGNuUnBabWxqWVhSbElHRmpZMjl5WkdsdVp5QjBieUJEZW1WamFDQkJZM1FnVG04dUlESXlOeTh5TURBd0lFTnZiR3d1TUlHQkJnTlZIUjhFZWpCNE1DYWdKS0FpaGlCb2RIUndPaTh2Y1dOeWJHUndNUzVwWTJFdVkzb3ZjV2xqWVRBNUxtTnliREFtb0NTZ0lvWWdhSFIwY0RvdkwzRmpjbXhrY0RJdWFXTmhMbU42TDNGcFkyRXdPUzVqY213d0pxQWtvQ0tHSUdoMGRIQTZMeTl4WTNKc1pIQXpMbWxqWVM1amVpOXhhV05oTURrdVkzSnNNQWtHQTFVZEV3UUNNQUF3RGdZRFZSMFBBUUgvQkFRREFnWkFNQmdHQ0NzR0FRVUZCd0VEQkF3d0NqQUlCZ1lFQUk1R0FRRXdId1lEVlIwakJCZ3dGb0FVZWN2UUkrazZaM0NSZEUvVFVlTGdJUDNoS1Bzd0hRWURWUjBPQkJZRUZCSW9WR3ZucldXM3BNcWtFY0ZyUmd6dWcyeWZNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNOTXBBaW00cUFsU3BHdGR0Mk45c0Rkc3hCRHlCVTdHR0hBcWQ4Z2dySnVPUDNpL2daVkZBL1RYNks1VUQ1aWlsWTFKU3VFcXVuOTVHRTRpcC8ySnVJSTNsa1FPMkhxR1NyczdvbWtOME9vZWdOT256WVRFSFRERHIxTTJZSStLejR5RlBUTVZDTkpQenJteTFWWDlxY2ZLb1VoL0YzdTEvcXhlY0lHTWdzYlFUOVd6RjJDY1NRc0F0QmswUlpuajFqeXNQTXFTSm1Ycm1PTzVkVlhHemxqR2V1N3JBTUttclQwenFSSiszaFluOXlQbWhLb1MrZjJyblRwTGs0Z25ZSGQ1VFhjekJkNVl2OFBNb0NVeWRiamc2ZTZ0ZGxtNWJQREhnTFJrcGlVVm9YYi9mR1pTVmtoa2gwUFhtTW1oR1lsRUhIZWRsNGl6UDFjZ1h2ZnM4WA) in the latest version of CyberChef (v7.6.3). I should point out that icyberchef.com is not officially supported. It has been set up by someone else and is not up to date. The official version can be found here: https://gchq.github.io/CyberChef/

If you're still having problems, feel free to reopen this issue. Thanks.

**Comment by SkyCrawl** [comment]
Ah, I had no idea about that, thanks!
