### ISSUE TITLE
Bug report: OR behaves like XOR

### ISSUE THREAD

**Issue by danisson** [gchq/CyberChef#243]
### Summary
Maybe I misunderstood but OR is behaving like XOR. When the input matches the key, the result is always zero instead of being the same thing as the input.

### Example
Here are some examples in hexadecimal:
[`0a OR 0a = 00`](https://gchq.github.io/CyberChef/#recipe=From_Hex('Space')OR(%7B'option':'Hex','string':'0a'%7D)To_Hex('Space')&input=MGE)
[`01 OR 01 = 00`](https://gchq.github.io/CyberChef/#recipe=From_Hex('Space')OR(%7B'option':'Hex','string':'01'%7D)To_Hex('Space')&input=MDE)
[`ff OR ff = 00`](https://gchq.github.io/CyberChef/#recipe=From_Hex('Space')OR(%7B'option':'Hex','string':'ff'%7D)To_Hex('Space')&input=ZmY)

**Comment by n1474335** [comment]
Good spot. All the code for the OR function was correct, but there was a typo in the configuration so it was calling the XOR function instead.

Thanks for raising the issue.
