### ISSUE TITLE
Bug report : Issue with call instruction in x86 disassembler. 

### ISSUE THREAD

**Issue by mylifeisabug** [gchq/CyberChef#246]
In 16-bit code, an intra-segment direct `CALL` (opcode starting with 0xE8) should only be three bytes long and take a single 16-bit displacement like so: 0xE8, disp-low, disp-high

But in the x86 disassembler, with the "Bit mode" field set to 16, the two bytes (in this case opcodes) following disp-high are lumped together with the `CALL` opcode and ignored.

For instance, when the  bytes `E8 00 00 90 90` are entered `CALL some_loc` is the output, but it should be `CALL some_loc NOP NOP`. The two `NOP`s are missing.

![untitled](https://user-images.githubusercontent.com/36830529/36651053-5c3b99b8-1a6c-11e8-8f54-39d251e71386.png)

**Comment by n1474335** [comment]
Hi @mylifeisabug, thanks for raising this. The [x86-64-Disassembler-JS library](https://github.com/Recoskie/X86-64-Disassembler-JS) is used for this operation, so it will have to be fixed there. If you raise the bug with them, feel free to link to this issue.

Thanks

**Comment by mylifeisabug** [comment]
The bug has been fixed.

**Comment by n1474335** [comment]
Thanks for following this up. I've updated the library in CyberChef so this now [works as expected](https://gchq.github.io/CyberChef/#recipe=Disassemble_x86('16','X86/486',16,0,true,true)&input=RTgwMDAwCjkwCjkw) (once Travis CI has finished [building](https://travis-ci.org/gchq/CyberChef/builds/357565989)).
