### ISSUE TITLE
Bug report: Disabled options get enabled again when changing something in the recipe

### ISSUE THREAD

**Issue by InsOpDe** [gchq/CyberChef#247]
* Version: 7.7.6
* Compile time: 28/02/2018 18:01:49 UTC
* User-Agent: 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.167 Chrome/64.0.3282.167 Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Find_/_Replace(%7B'option':'Simple%20string','string':'foo'%7D,'bar',false,false,true)Reverse('Character')&input=Zm9v)

### Summary
When disabling/enabling a "operation a" the disabled options of "operation b" gets enabled again.
Its important that the options of "operation b" once where enabled before for this to reproduce.
This is confirmed with "From Base64" and "Find / Replace" but is most likely a bug for each operation with checkbox-options

### Example
![cyberchef](https://user-images.githubusercontent.com/10099328/36846242-32d9e7b4-1d5a-11e8-95d1-f497b75cc98f.gif)

**Comment by n1474335** [comment]
Yes, this has been a problem for some time. It's a known bug in the Sortable library that I use for the drag and drop capabilities.

More info here: https://github.com/RubaXa/Sortable/issues/1052

Once it has been fixed, I will update the dependency.

**Comment by GCHQ77703** [comment]
RubaXa seems to no longer maintain Sortable.  The fix for this is, however, on the master branch of the Github repository.

Would it be worthwhile to fork it and release the latest verison to `npm` ourselves?

**Comment by n1474335** [comment]
This has been fixed in SortableJS v1.8.0-rc1 which we use as of https://github.com/gchq/CyberChef/commit/d469fb9c58834164fee8e985a5f0dfe138bcf962#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R124
