### ISSUE TITLE
Bug report: FromHex might have incorrect behavior

### ISSUE THREAD

**Issue by weez15** [gchq/CyberChef#249]
### Summary
Read "04EB" from hex and do sha256 produces unexpected hash value.

### Example
https://gchq.github.io/CyberChef/#recipe=From_Hex('None')SHA2('256')&input=MDRFQg
`>>> hashlib.sha256(bytearray.fromhex("04EB")).hexdigest()
'ed217f56dc61ac951f0652b78f7ed68505bc4f250463e0e9a60298d8214e068b'`

**Comment by n1474335** [comment]
@weez15 Thanks for raising this. I've had a few issues with the hashing operations not handling byte strings correctly before. I had fixed it, then I updated the library and it broke again. I've fixed it once again and added a load of tests so we should notice immediately if anything goes wrong in future.
