### ISSUE TITLE
Feature request: Chain output as parameter

### ISSUE THREAD

**Issue by spifd** [gchq/CyberChef#26]
Hi,
It looks like it's not possible to use the output of an action as a parameter (ex: a key) in another action. Am I right? If yes, that could be an interesting feature so one could chain operations like using a key derivation function to generate the key used to encrypt an input).
Thanks.

**Comment by n1474335** [comment]
Hi @spifd,

This has been on my mind for a while. It would make a good Flow Control operation. There are a few issues to iron out, but I will hopefully address this in the coming months.
