### ISSUE TITLE
Operation request: Protobuf parser

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#262]
### Summary

An operation to parse [Protocol Buffers](https://en.wikipedia.org/wiki/Protocol_Buffers). There are various npm packages that may help with this.

**Comment by d98762625** [comment]
I assume we would have to provide the schema as an argument to the operation to be able to decode a message? Therefore we would need to add a `file` type argument to an operation?

**Comment by n1474335** [comment]
That's an option. You could also just use the `text` data type and pass the entire schema in to that.
