### ISSUE TITLE
Operation request: Improve 'Parse IP range' input options

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#270]
### Summary

The 'Parse IP range' operation currently accepts inputs in either CIDR notation ([10.0.0.0/29](https://gchq.github.io/CyberChef/#recipe=Parse_IP_range(true,true,false)&input=MTAuMC4wLjAvMjk)) or range notation ([10.0.0.0 - 10.0.0.7](https://gchq.github.io/CyberChef/#recipe=Parse_IP_range(true,true,false)&input=MTAuMC4wLjAgLSAxMC4wLjAuNw)).

It would be useful if it could accept a list of IPs and calculate the smallest subnet which covers them all. This would simply be a matter of finding the smallest and largest IPs and constructing a range between them. e.g. the following input would generate the same output as the two examples above:

```
10.0.0.0
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
10.0.0.5
10.0.0.6
10.0.0.7
```

**Comment by jonebeabout** [comment]
Would this be a better improvement for 'Group IP Addresses' with a parameter to calculate smallest subnet instead of user selecting a predefined subnet?

**Comment by n1474335** [comment]
That's certainly a possibility, but the point of the 'Group IP addresses' operation is that you can create multiple groups depending on a specific subnet size. If you want to just group the whole lot into one subnet, I think it fits the 'Parse IP addresses' operation a bit better.
