### ISSUE TITLE
Operation request: Add option for Fork to ignore errors

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#271]
### Summary

Currently, if an operation within a fork causes an error to be thrown, the entire recipe will fail and an exception will be raised ([example](https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn%5C%5Cn','%5C%5Cn',false)Gunzip()&input=H4sIADRQtVoA/wVAuQkAMBBaxdWEexAsUqW46YX4tAp7ehi5AxAGge0RAAAACgpub3QgYSB2YWxpZCBnemlwIGZpbGU)).

An argument could be added to the 'Fork' operation to "Continue on errors" which would ignore these exceptions and continue executing the remaining branches.

**Comment by masq** [comment]
This looks to be done already: [your example with ignore errors turned on](https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn%5C%5Cn','%5C%5Cn',true)Gunzip()&input=H4sIADRQtVoA/wVAuQkAMBBaxdWEexAsUqW46YX4tAp7ehi5AxAGge0RAAAACgpub3QgYSB2YWxpZCBnemlwIGZpbGU). Should this issue be closed?

**Comment by n1474335** [comment]
Good spot!
