### ISSUE TITLE
Operation request: Improvements to Regex highlighting

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#279]
### Summary

The 'Regular expression' operation currently highlights matches. It would be useful to add a tooltip when hovering over those matches that displays information like their offset and capture groups.

**Comment by qistoph** [comment]
How about this?

![image](https://user-images.githubusercontent.com/678500/46803238-e907f480-cd5f-11e8-9974-35e202897167.png)

PR is comming.
