### ISSUE TITLE
Feature request: ascii85/base85 support

### ISSUE THREAD

**Issue by piru** [gchq/CyberChef#286]
### Summary
Consider adding support for base85/ascii85 encoding/decoding - https://en.wikipedia.org/wiki/Ascii85

**Comment by PenguinGeorge** [comment]
I’m currently working on this. Looking in to the various Base85 specs, I plan on including support for Ascii85, Z85, as well as IPv6 encoding. 

As of right now, I have encoding for Ascii85 and Z85 working, and decoding for Ascii85 working. It’ll be a few days before I have a chance to work on the rest.
