### ISSUE TITLE
JSON Beautify and Minify code tidy operations yield error when input box is empty

### ISSUE THREAD

**Issue by jgrevich** [gchq/CyberChef#29]
JSON Beautify and JSON Minify code tidy operations yield an error message when the input box is empty.

#### Steps to reproduce the issue (please be as specific as possible)

1. Visit https://gchq.github.io/CyberChef
1. Expand the code tidy operations
1. Double click on the JSON Beautify or JSON Minify code tidy operations <img width="569" alt="screen shot 2016-12-02 at 12 18 06 am" src="https://cloud.githubusercontent.com/assets/24955/20827150/db012098-b824-11e6-8c88-4f79aa48d30a.png">

#### Expected behavior
It should add the operation to the recipe box without error, similar to the other operations.

#### Actual behavior
The following error message is displayed: <img width="669" alt="screen shot 2016-12-02 at 12 20 14 am" src="https://cloud.githubusercontent.com/assets/24955/20827243/7defd240-b825-11e6-9140-c31f70fcd271.png">

- Operating system (Mac OS X Yosemite 10.10.5)
- Web browser and version (Chrome 55.0.2883.75 (64-bit))
- Date, specific time and time zone when issue was found (Friday, December 2, 2016 8:28a UTC)

**Comment by n1474335** [comment]
Good spot and a comprehensive report, thank you. I've pushed a fix.
