### ISSUE TITLE
Operation request: XOR Hex Delimiter

### ISSUE THREAD

**Issue by jeffg2k** [gchq/CyberChef#295]
### Summary
When doing an XOR using Hex, CyberChef should offer the delimiter drop down menu.  You sort of get use to just pasting in the values and can falsely assume it's reading it the way you expect.

### Example
```
TESTME
XOR HEX: 06:17 = RETRMB
XOR HEX: 0617 = RRUCKR
```

**Comment by n1474335** [comment]
Good spot. I've updated the `Utils.fromHex()` function so that by default it now strips all characters that don't fall within `0-9a-f`. The only delimiter that will still cause issues is `0x` because the `x` will be removed but the `0` will remain. I think we can live with this.
