### ISSUE TITLE
restructure project to keep components and their styles/markup together

### ISSUE THREAD

**Issue by graingert** [gchq/CyberChef#3]
eg:

**css**/lib/bootstrap3.min.**css**
**html**/index.**html**
**js**/config/Categories.**js**

Your source code directories should be chosen by feature, not filetype. This keeps style, markup and code together when navigating your codebase.

There's no need to add extra redundant file type information to your paths, we already know it's a js file because the path ends with `js`. You can use `**/*.js` to select them in scripts.

**Comment by graingert** [comment]
If you want to set different caching strategies per filetype, you can use webpack to move different asset types into different directories automatically.

**Comment by n1474335** [comment]
Hi @graingert,

You make some good points. We'll keep the structure as it is for now but will revisit this when our library management plans come to fruition (#2).
