### ISSUE TITLE
Bug Report - Regular Expression Capability Mismatch

### ISSUE THREAD

**Issue by malvidin** [gchq/CyberChef#301]
"Regular Expression" and "Find/Replace" recipes don't use the same regex capabilities.

Regular Expression:
\p{Greek}+

Input:
\p{Greek}
Ναδ

Regular Expression Output:
\p{Greek}
Ναδ (Highlighted)

Find/Replace Output:
\\
Ναδ

**Comment by n1474335** [comment]
Good spot. The 'Regular Expression' operation uses the `XRegExp` library which supports Unicode character groups, whereas the 'Find / Replace' operation just uses native JS regular expressions which does not. I'll look to add `XRegExp` support to 'Find / Replace' soon.

**Comment by n1474335** [comment]
Fixed in bf264380
