### ISSUE TITLE
Add `recipe` to top level chef object

### ISSUE THREAD

**Issue by d98762625** [gchq/CyberChef#302]
_Dependent on #287 being complete_

### Summary
Create `chef.recipe` object which takes an array of operations and an input. Sample uses:

### Examples
Constructor
```javascript
import {chef, Recipe} from 'chef';
const recipe = new Recipe([
    chef.toBase32,
    chef.fromBase32
]);
```
Execute
```javascript
const output = await recipe.bake('input');
// => 'input'
```

And then we would have array style operations to edit operations array:
```javascript
const result = await recipe.splice(0,1).bake('input');
// => NFXHA5LU
```

### Alternatives

- Instead of `Recipe` class, just have `chef.recipe`
- Just have `chef.bake` which can take an array of operations and an input, or an operation config like the object that's exported in the chef GUI

**Comment by n1474335** [comment]
I think I prefer the `chef.bake` alternative you've listed. It can use the `Recipe` class underneath, but that can be transparent to the user.

`chef.bake` could have a fairly dynamic api that accepts almost anything you throw at it. e.g.
``` javascript
chef.bake("some input", "To Base64");
chef.bake("some input", "tobase64");
chef.bake("some input", ["To Base64", "To Hex"]);
chef.bake("some input", [{"op":"To Base64","args":["A-Za-z0-9+/="]}]); // Web app recipe format
chef.bake("some input", chef.toBase64);
chef.bake("some input", [chef.toBase64, chef.toHex]);
```

**Comment by d98762625** [comment]
I like the operation-by-name format too. 

Overall, I think `chef.bake` is good. It keeps the API small and lenient.
