### ISSUE TITLE
Bug report: Generate PGP key pair operation doesn't work in standalone htm file.

### ISSUE THREAD

**Issue by avnshpnwar** [gchq/CyberChef#305]
### Summary
When using CyberChef as single htm downloaded file, Generate PGP key pair operation doesn't work.

### Example
When we click on Generate PGP key pair, it require helper file PGP.js which is not available.

**Comment by n1474335** [comment]
Thanks for reporting this. I'll look into it.

**Comment by avnshpnwar** [comment]
It is now working in version 8.0.0s. This bug can be closed now.

**Comment by mpepping** [comment]
Did this issue snook back in somewhere around 8.12.x?

https://github.com/mpepping/docker-cyberchef/issues/2
