### ISSUE TITLE
Feature request: Integration with kaitai.io

### ISSUE THREAD

**Issue by s7726** [gchq/CyberChef#314]
Allow processing based on kaitai ksy files making output available for further processing

**Comment by n1474335** [comment]
I'm going to close this one for now as I don't want to start creating lots of hooks into other sites at the moment. If other people would find it useful, please comment here and we may reopen it.

**Comment by tombonner** [comment]
This would actually be a great combination. You could use Kaitai to parse file formats such as PE, PCAP, PNG etc and ingest the data back into CyberChef for processing. I would definitely use this! :)

**Comment by Kreijstal** [comment]
This would be actually useful, it doesn't need to be integrated into the website, but with kaitai struct you don't need to make a parser for many binary files.
