### ISSUE TITLE
Unsupported browser?

### ISSUE THREAD

**Issue by AndreC10002** [gchq/CyberChef#316]
Have the latest version of CyberChef running via 'grunt dev' and am getting an unsupported browser error message.

TypeError: global.getComputedStyle(...) is null
Filename: http://xxx.yy.zzz.44:8080/main.js line 4794 > eval
Line: 95
Column: 31
Error: TypeError: global.getComputedStyle(...) is null
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
CyberChef version: 7.11.1

I'm brand new to NodeJS, so hopefully I'm not making a big mistake.

Thank you.

**Comment by n1474335** [comment]
Hi @AndreC10002, are you still getting this error? I'm not seeing it in Firefox 61.

If no one sees it any more, I'll close this issue.

**Comment by AndreC10002** [comment]
Sorry, but I don't have the resources to verify it anymore.

**Comment by n1474335** [comment]
Ok, I'll close this for now then.
