### ISSUE TITLE
Possible compatibility issue with OpenSSL

### ISSUE THREAD

**Issue by meeas** [gchq/CyberChef#323]
### Summary
I get "Unable to decrypt input with these parameters." error messages when trying to decrypt a message originally encrypted with OpenSSL, using what I believe is the correct EVP derived key

### Example
The following command successfully decrypts the cyphertext on Mac and Linux machines.  Currently I'm using OpenSSL 0.9.8zh on Mac OSX 10.12.6.

echo -n 'U2FsdGVkX1+FCYr3e5DJDDdz1B5ZtQvpiaieRJrSSSw3c9QeWbUL6YmonkSa0kksJ1Jj8Oq4aNhDRADdt+1iPC9hIg87liKbVEc2fqBM8lsiG0oyACgRxJ3oy1XTnAZXlucGqmLnCsqSbwO6N1uANt1pRXJFCefgGvZ3fAherCsZP297KVp7aXCORA8Tk0tNN3PUHlm1C+mJqJ5EmtJJLDdz1B5ZtQvpiaieRJrSSSw5wFphGyd+gWYQ5OgCej2X' | base64 -D | openssl aes-128-ecb -d -pass pass:16-ecb

I have tried to repeat this in CyberChef, with the following steps.

First, I base64 the ciphtext to extract the EVP salt of 85098af77b90c90c

Then derive the EVP key using the password 16-ecb and the salt hex 85098af77b90c90c using MD5, 128 bit, and 1 iteration to receive the EVP key of 522a4923d7344127a3f1af4b554adb32  (as a side note, I've tried all the other hashes just in case my research was wrong about OpenSSL < 1.1 defaulting to MD5 in EVP)

Then I take the raw hex ciphertext minus the first 16 bytes (which was the EVP salt) which gives me:

3773d41e59b50be989a89e449ad2492c3773d41e59b50be989a89e449ad2492c275263f0eab868d8434400ddb7ed623c2f61220f3b96229b5447367ea04cf25b221b4a32002811c49de8cb55d39c065796e706aa62e70aca926f03ba375b8036dd6945724509e7e01af6777c085eac2b193f6f7b295a7b69708e440f13934b4d3773d41e59b50be989a89e449ad2492c3773d41e59b50be989a89e449ad2492c39c05a611b277e816610e4e8027a3d97

Then I attempt to decrypt it with AES Decrypt using the hex key of 522a4923d7344127a3f1af4b554adb32 with no IV, hex input, ecb cipher mode, and no no GCM Tag and I get:  "Unable to decrypt input with these parameters."

So, first off, I'm confused as to why AES can't attempted to decrypt the hex.   If that is a PKCS#7 failure, I'd suggest changing the error message to state such.   But short of that, I don't know why if the key was incorrectly derived I wouldn't at least get garbage out.

Second, can you see if I'm making any mistakes in my efforts or missing some other fact to successfully decrypt this ciphertext?   

As a feature request, it would be awesome if there was a OpenSSL option in the AES Encrypt/Decrypt password dropdown to automatically extract/generate the salt and create the EVP derived key.

**Comment by n1474335** [comment]
Hi @meeas, I get the following when I run your command:

```
$ echo -n 'U2FsdGVkX1+FCYr3e5DJDDdz1B5ZtQvpiaieRJrSSSw3c9QeWbUL6YmonkSa0kksJ1Jj8Oq4aNhDRADdt+1iPC9hIg87liKbVEc2fqBM8lsiG0oyACgRxJ3oy1XTnAZXlucGqmLnCsqSbwO6N1uANt1pRXJFCefgGvZ3fAherCsZP297KVp7aXCORA8Tk0tNN3PUHlm1C+mJqJ5EmtJJLDdz1B5ZtQvpiaieRJrSSSw5wFphGyd+gWYQ5OgCej2X' | base64 -d | openssl aes-128-ecb -d -pass pass:16-ecb
bad decrypt
```

Are you sure it's working correctly? Can you confirm that the key should definitely be EVP derived? Using PBKDF2 I get garbage out, but it doesn't error.
