### ISSUE TITLE
Bug report: Cannot access with Firefox 61.0.1

### ISSUE THREAD

**Issue by Neo23x0** [gchq/CyberChef#328]
### Summary
SecurityError: The operation is insecure.
Filename: https://gchq.github.io/CyberChef/main.js
Line: 99
Error: SecurityError: The operation is insecure.
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0
CyberChef version: 8.0.0

**Comment by n1474335** [comment]
Thanks for reporting this. I can't replicate it on Linux so it must be Mac-specific. Do you have any particular security controls turned on? For instance, are you blocking localStorage?

Is anyone else seeing this error?

**Comment by Neo23x0** [comment]
It was one of the Extensions that caused the error. 

Sorry, I just switched the browser and disabled all extensions (like NoScript) of which I thought that they could be the reason for this issue. 

https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/

**Comment by n1474335** [comment]
Yes, I should imagine NoScript won't play particularly nicely with CyberChef...
Thanks for getting to the bottom of it.

**Comment by Neo23x0** [comment]
Ha 😄, no, a misunderstanding. I had already NoScript disabled when I visited CyberChef. It was a simple "Dark Mode" Add-on that caused the problem and I didn't expect that.
