### ISSUE TITLE
Bug report: Baking after resolving a ingredient error with a set of multiple operations operates on the wrong data.

### ISSUE THREAD

**Issue by picapi** [gchq/CyberChef#329]
### Summary
When using multiple operations, if an intermediary operation has an error, the first bake after this error is corrected will operate on the error text output, rather than the true given input. This could result in misleading outputs while attempting to operate on data.

### Example
Click [here](https://gchq.github.io/CyberChef/#recipe=Split('%20','%5C%5Cn')Vigenère_Decode('')&input=SGVsbG8gV29ybGQh) and then change the key to become a single character. The expectation would be that the output would be each word in the input enciphered using the key on a different line, but the reality is that the No Key Entered message is enciphered, and remains in the output until a second character is utilised.

**Comment by n1474335** [comment]
Thanks very much for raising this @picapi. It was a very easy fix, but it looks like it's been there for a while. Good spot.
