### ISSUE TITLE
Feature Request: A better hex-string converter for the registry editor.

### ISSUE THREAD

**Issue by SalviaSage** [gchq/CyberChef#330]
### Feature Request: A better hex-string converter for the registry editor.

Hi. I really like this website tool.
I found that it is the only tool capable of doing the string to hex and hex to string conversions that I need for the Windows Registry Editor.

Because it allows queuing up multiple conversions. 
Doing this I can now get the conversions I need from this link:
https://gchq.github.io/CyberChef/#recipe=To_Hex(%27Space%27)From_Hex(%27Space%27)Decode_text(%27UTF-8%20(65001)%27)Encode_text(%27UTF16LE%20(1200)%27)To_Hex(%27Comma%27)
(This turns strings into a hex format usable with the windows registry editor.)

And this turns it from the above hex format into the string format:
https://gchq.github.io/CyberChef/#recipe=From_Hex(%27Comma%27)Decode_text(%27UTF16LE%20(1200)%27)Encode_text(%27UTF-8%20(65001)%27)To_Hex(%27Space%27)From_Hex(%27Auto%27)

The only problem though, is that this adds the new lines with the newline (\n) escape character whereas they must be carriagereturn+newline (\r\n) for the windows registry editor.

1) So, I would like an option to switch to using \r\n as new lines instead of only \n
Because of this, I have to correct the new lines manually any time I make new lines.

2) The windows registry editor wraps these hex values by placing a " \\ " syntax 
(this must not exceed 80 characters in length per line)
This is optional but it is how the Windows registry works. So, it would be nice if we could have an option to warp at 80 characters with the " \\ " syntax. I believe this can be implemented programmatically.

3) The windows registry also does not work with a file encoding that is without BOM. The file encoding in this case can simply be made BOM by putting in a FF,FE at the start the conversion.

### Example
So for example, it would look like this: 

"this is a string"

FF,FE,74,00,68,00,69,00,73,00,20,00,69,00,73,00,20,00,61,00,20,00,73,00,74,00,72,00,69,00,6e,00,67,00

I don't think it would be hard to add an option to put the FF,FE characters at the start.

There are already converters and minifiers that is set to work with various different areas of computers in this tool. So I would like to ask that a "windows registry hex-string converter" be added to the "Other" section with the specified 3 changes implemented. You would be helping people who work with the windows registry IMMENSELY 👍

I am willing to provide any other information regarding this issue.
Thanks for your consideration!

**Comment by n1474335** [comment]
Hi @SalviaSage, perhaps this recipe will help you:

https://gchq.github.io/CyberChef/#recipe=Find_/_Replace(%7B'option':'Regex','string':'%5C%5Cn'%7D,'%5C%5Cr%5C%5Cn',true,false,true)Encode_text('UTF16LE%20(1200)')Find_/_Replace(%7B'option':'Regex','string':'%5E'%7D,'%5C%5Cxff%5C%5Cxfe',false,false,false)To_Hex('Comma')&input=dGhpcyBpcyBhIHN0cmluZwp3aXRoIGEgbGluZSBicmVhaw

**Comment by SalviaSage** [comment]
oh wow. That is really nice.
Thanks for that.

**Comment by SalviaSage** [comment]
Hi.
I also have the link for the reverse operation where the hex values get converted to the string.
This also needs the \r\n line breaks.

https://gchq.github.io/CyberChef/#recipe=To_Hex('Space')From_Hex('Space')Decode_text('UTF-8%20(65001)')Encode_text('UTF16LE%20(1200)')To_Hex('Comma')

I don't know how to adapt your link into this configuration.
Can you help me please?

Thanks.

**Comment by SalviaSage** [comment]
Dear @n1474335 

I fear this link you have provided me is no longer 'baking'.

I tried restarting my computer and opening the link with 2 web browsers and although the page loads and the input section works, the output section is stuck in a spinning animation and it says 'Loading CharEnc module'.

It never loads, so I can not use this tool and thus can not proceed with my programming now.
Can you please check this link to see if it works for you or others and fix this link if necessary, other areas are 'baking' fine.

- sal

**Comment by SalviaSage** [comment]
Okay.

This no longer works.
It outputs the following syntax error:

Encode text - Error in https://gchq.github.io/CyberChef/modules/Encodings.js on line 27.<br><br>Message: Unrecognized CP: undefined

Such a shame, because this is a very useful conversion for the project I work on.
I will try to get the converter working again but, in the meantime, perhaps you can
restore it for me.

I don't know if I can fix it on my own.

Thanks.

**Comment by n1474335** [comment]
https://gchq.github.io/CyberChef/#recipe=Find_/_Replace(%7B'option':'Regex','string':'%5C%5Cn'%7D,'%5C%5Cr%5C%5Cn',true,false,true,false)Encode_text('UTF-16BE%20(1201)')Find_/_Replace(%7B'option':'Regex','string':'%5E'%7D,'%5C%5Cxff%5C%5Cxfe',false,false,false,false)To_Hex('Comma')&input=dGhpcyBpcyBhIHN0cmluZwp3aXRoIGEgbGluZSBicmVhaw

**Comment by SalviaSage** [comment]
Thanks for the reply, however I managed to fix it on my own.
