### ISSUE TITLE
Bug Report: Errors on NodeJS 10 Build

### ISSUE THREAD

**Issue by into2332** [gchq/CyberChef#335]
### Summary

Experiencing issues building latest CyberChef on NodeJS 10.

### Example

	Running "eslint:configs" (eslint) task

	Running "eslint:core" (eslint) task

	Running "eslint:web" (eslint) task

	Running "eslint:node" (eslint) task

	Running "eslint:tests" (eslint) task

	Running "clean:prod" (clean) task
	>> 0 paths cleaned.

	Running "exec:generateConfig" (exec) task

	--- Regenerating config files. ---
	>> (node:13150) ExperimentalWarning: The ESM module loader is experimental.
	Written operation index.
	>> (node:13160) ExperimentalWarning: The ESM module loader is experimental.
	>> /root/build7/CyberChef/node_modules/crypto-api/src/crypto-api.js:3
	>> import Has160 from "./hasher/has160";
	>>        ^^^^^^
	>> 
	>> SyntaxError: Unexpected identifier
	>>     at new Script (vm.js:74:7)
	>>     at createScript (vm.js:246:10)
	>>     at Proxy.runInThisContext (vm.js:298:10)
	>>     at Module._compile (internal/modules/cjs/loader.js:657:28)
	>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	>>     at Module.load (internal/modules/cjs/loader.js:599:32)
	>>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	>>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	>>     at createDynamicModule (internal/modules/esm/translators.js:56:15)
	>>     at setExecutor (internal/modules/esm/create_dynamic_module.js:50:23)
	--- Config scripts finished. ---

**Comment by d98762625** [comment]
@into2332 What specific command did you run and which node 10 version?

**Comment by into2332** [comment]
Figured it out, was running 'npm install' as root. Needed to pass 'npm install --unsafe-perm' to build the crypto-api.js

**Comment by n1474335** [comment]
Ah, that makes sense. The specific problem you were seeing there was that the CyberChef postinstall script wasn't running. This will happen when you're running as root or if you use `npm install --ignore-scripts`. You can fix this by running `npm run postinstall` manually, or by not running as root, which is probably a sensible move anyway. You're executing code from hundreds of third party sources so you should definitely be limiting their permissions.
