### ISSUE TITLE
Operation request: please had decimal input to SUB operation

### ISSUE THREAD

**Issue by oppiman** [gchq/CyberChef#337]
The "SUB" operation does not take decimal as input
I would love to see this added. 
Wouldn't require me to convert to hex each time.

**Comment by n1474335** [comment]
Done. Thanks for the suggestion. I've added `Decimal` as an option for the following ops:
- OR
- SUB
- XOR
- ADD
- AND

**Comment by oppiman** [comment]
Thanks a lot.
