### ISSUE TITLE
Feature Request: Ability to set comments/notes on an operation 

### ISSUE THREAD

**Issue by superhac** [gchq/CyberChef#34]
It would be nice to have the ability to add a note or comment to an operation.   I can see this being useful if you publish a receipt and you want to provide some clarity on why your doing a specific operations.  An example would be why your using the "Drop Bytes" operation.   

This could be represented by icon on the operation and then displayed with a mouse over event.

Thanks,

Superhac

**Comment by n1474335** [comment]
#123 added to partially cover this. I'll close it for now but we may revisit to make a more elegant solution in future.
