### ISSUE TITLE
Operation request: URL Escape Characters.

### ISSUE THREAD

**Issue by SalviaSage** [gchq/CyberChef#343]
### Summary

Hi. I just found something that can be done with CyberChef (I hope)
So. If I copy paste a URL from my web browser into my text editor.
It will be recognized as a URL link but until it hits a single quote or something else that needs to be escaped.
### Example

for example, I have this cyberchef link

https://gchq.github.io/CyberChef/#recipe=From_Hex('Comma')Decode_text('UTF16LE%20(1200)')Encode_text('UTF-8%20(65001)')To_Hex('Space')From_Hex('Auto')

and that has to become

https://gchq.github.io/CyberChef/#recipe=From_Hex(%27Comma%27)Decode_text(%27UTF16LE%20(1200)%27)Encode_text(%27UTF-8%20(65001)%27)To_Hex(%27Space%27)From_Hex(%27Auto%27)

Here, I manually replaced the ( ' ) with their escape codes ( %27 ) this is recognized as a URL in both the text editor and in the web browser.

So. How can we automate this? is this already in cyberchef? if not, can we get some help?
Also, how to add things to the favorites?

Thanks.

**Comment by SalviaSage** [comment]
Oh lol, I just regexed it myself.

https://gchq.github.io/CyberChef/#recipe=Find_/_Replace(%7B'option':'Regex','string':'%5C''%7D,'%2527',true,false,true,false)

So this just changes the single quotes to %27 since they stop the URL from beign recognized in text editors.

I'll leave this here if anyone else needs. Closing the issue now.

**Comment by n1474335** [comment]
CyberChef deep links are designed to use as many legal URL characters as possible to keep them short. This is discussed here: https://github.com/gchq/CyberChef/blob/master/src/core/Utils.mjs#L662

```javascript
    /**
     * Encodes a URI fragment (#) or query (?) using a minimal amount of percent-encoding.
     *
     * RFC 3986 defines legal characters for the fragment and query parts of a URL to be as follows:
     *
     * fragment      = *( pchar / "/" / "?" )
     * query         = *( pchar / "/" / "?" )
     * pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
     * unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
     * pct-encoded   = "%" HEXDIG HEXDIG
     * sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
     *                  / "*" / "+" / "," / ";" / "="
     *
     * Meaning that the list of characters that need not be percent-encoded are alphanumeric plus:
     * -._~!$&'()*+,;=:@/?
     *
     * & and = are still escaped as they are used to serialise the key-value pairs in CyberChef
     * fragments. + is also escaped so as to prevent it being decoded to a space.
     *
     * @param {string} str
     * @returns {string}
     */
```

I'm aware that some client applications do not recognise single quotes as legitimate URL characters, but the RFC clearly states that they are. Using the `URL encode` operation is a perfectly legitimate way of getting around this problem, but I won't be changing the default behaviour for CyberChef deep links for the moment. The problem is with the applications that do not accept single quotes.
