### ISSUE TITLE
Bug report: Browser history gets spammed when manually typing input

### ISSUE THREAD

**Issue by opl-** [gchq/CyberChef#359]
### Summary

When manually writing text into the input field, the browser history gets filled with entries for each key stroke. Using the [browser history API](https://developer.mozilla.org/en-US/docs/Web/API/History) you could replace the last entry instead when the input happens below a certain time threshold, in order to avoid this.

### Example

1. Manually type anything into the input field.

2. Open browser history.

3. One entry should now exist for each key press.

### Platform

Firefox 61

**Comment by n1474335** [comment]
Interesting. We do actually use `replaceState`: https://github.com/gchq/CyberChef/blob/f052ed9b00e1bc3d146b3d3b8df3a5ae0021ed9b/src/web/App.mjs#L662

I'll look into this when I get a moment.

**Comment by n1474335** [comment]
I can't replicate this issue. As I understand it, since we use `replaceState`, there shouldn't be a new entry every time you type. Closing this for now.

**Comment by mattnotmitt** [comment]
Just checked this now and I can still replicate it https://gfycat.com/villainousgraciousastarte (every time the favicon flashes, a new entry is added to my history)

**Comment by opl-** [comment]
I can also still replicate this on Firefox 72.0.2, CyberChef v9.20.3.

**Comment by mattnotmitt** [comment]
Looks like this is a [known defect](
https://bugzilla.mozilla.org/show_bug.cgi?id=753264) with Firefox.

**Comment by Kumm-Kai** [comment]
I've also stumbled into this.
But you can work around this by unchecking `Update the URL when the input or recipe changes` in the `Options`.
