### ISSUE TITLE
Feature request: Iterations

### ISSUE THREAD

**Issue by adon90** [gchq/CyberChef#364]
In the online tool https://gchq.github.io it would be great if you want to decode 15 times, to automate it, instead of inserting manually 15 decodes (if this option exists, I haven't found them).
PD: great tool, regards.

**Comment by GCHQ77703** [comment]
Hey @adon90, which decode function are you using that requires you to repeat it 15 times?

**Comment by adon90** [comment]
It is a hacking challenge, a virtual machine (Hack The Box)

**Comment by n1474335** [comment]
You can achieve this using the Jump and Label operations.

Example: https://gchq.github.io/CyberChef/#recipe=Label('loop')From_Base64('A-Za-z0-9%2B/%3D',true)Jump('loop',5)&input=Vm0xNFUxRXlSWGhYV0d4VlYwZDRWVmxVU205VlZsVjNWbFJHVkUxV1dqQlVWbHBQVkcxS1NHUkVWbFZXYkVwVVdWVmtVMDVyTVVWaGVqQTk
