### ISSUE TITLE
Allow alternatives to viewing URLs "on Wikipedia"

### ISSUE THREAD

**Issue by GCHQ77703** [gchq/CyberChef#368]
> Automatic-detection-of-encoded-data-using-CyberChef-Magicopen_in_new on Wikipedia

Some Wikipedia links are, in fact, not Wikipedia links.

**Comment by PenguinGeorge** [comment]
I may be misunderstanding, but currently if the `infoURL` provided is not a Wikipedia article, it won't display the "on Wikipedia" text, but just the URL or "Learn More" text.

**Comment by n1474335** [comment]
Good spot.

Yes, the infoURL can be any link, but I think @GCHQ77703 is referring to the infoURL used for the Magic operation which is parsed as if it were a Wikipedia URL when in fact it isn't.
