### ISSUE TITLE
Support `magic` files for filetype detection

### ISSUE THREAD

**Issue by GCHQ77703** [gchq/CyberChef#369]
At the moment we only support a small number of files that contain simple magic byte strings, being able to parse the `magic` format used by services such as `file` would allow detection of many more files.

**Comment by GCHQ77703** [comment]
Am currently working on this.

**Comment by n1474335** [comment]
Great. Look forward to seeing this!

**Comment by n1474335** [comment]
Support for more filetypes has been added in #440 along with the ability to parse out some file formats from arbitrary byte streams. More formats can be added over time, but I'll close this issue for now.
