### ISSUE TITLE
Bug: Tooltip stays shown, after moving mouse

### ISSUE THREAD

**Issue by viktorstrate** [gchq/CyberChef#37]
When bug happends, the tooltip popup stays shown, and you have to reload the page to make it dissapear.

![Bug](https://cloud.githubusercontent.com/assets/4233458/20879733/699efea8-bad5-11e6-9262-207f8cba5e38.PNG)

## How to reproduce bug
1. Focus search bar
2. Hover over an operation
3. Type something in the searchbar, thile still hovering over an operation
4. Move the mouse away, and the popup will stay open.

**Comment by n1474335** [comment]
Good spot. Fixed.
