### ISSUE TITLE
Bug report: Backslash is removed in "To Table" operation unless it is escaped with backslash

### ISSUE THREAD

**Issue by stianja** [gchq/CyberChef#375]
### Summary
Not sure if this is a bug or feature, but when I add a backslash (\) in the text in "To Table" operation it is removed in the output table for some reason. If i add double slash, it becomes a slash in the output.

See the link for example.

### Example

https://gchq.github.io/CyberChef/#recipe=To_Table(',','%5C%5Cn%5C%5Cr',false,'ASCII')&input=QSxCLEM6XCAsRDpcXCxFLEY

I would expect the output table to be:
+---+---+-----+-----+---+---+
| A | B | C:\  | D:\\ | E | F |
+---+---+-----+-----+---+---+

**Comment by n1474335** [comment]
You are correct. I thought that escaped characters were part of the CSV standard but apparently they are not. We should get this fixed.
