### ISSUE TITLE
Feature request: support uuencoding

### ISSUE THREAD

**Issue by evandrix** [gchq/CyberChef#377]
### Summary

Support [uuencoding](https://en.wikipedia.org/wiki/Uuencoding).

### Example

For instance, [writeup](https://medium.com/bugbountywriteup/tokyowesterns-ctf-4th-2018-writeup-part-1-78558397cb7b) for CTF task would then be do-able.

**Comment by n1474335** [comment]
There is a uuencoding alphabet supported by the Base64 operations:
https://gchq.github.io/CyberChef/#recipe=To_Base64('%20-_')&input=SGVsbG8sIHdvcmxk

Is this sufficient?
