### ISSUE TITLE
Bug report: base58 encoding ignored heading zero bytes

### ISSUE THREAD

**Issue by weez15** [gchq/CyberChef#380]
### Summary

base58 encoding for [0x00, 0x12, 0x34] is same as [0x12, 0x34]

### Example

https://gchq.github.io/CyberChef/#recipe=From_Hex('None')To_Base58('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz')&input=MDAxMjM0

https://gchq.github.io/CyberChef/#recipe=From_Hex('None')To_Base58('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz')&input=MTIzNA

```
>>> base58.b58encode("001234".decode('hex'))
'12PM'
>>> base58.b58encode("1234".decode('hex'))
'2PM'
```

**Comment by n1474335** [comment]
Fixed in #403. Thanks to @bwhitn.
