### ISSUE TITLE
Bug report: "Loading Compression module" could not finish after 8.8.0 build at gchq.github.io

### ISSUE THREAD

**Issue by myfonj** [gchq/CyberChef#382]
### Summary
Been playing with compression yesterday at 8.7.0, when returned to it I saw it upgraded to 8.8.0 and the output stuck on "Loading Compression module".

### Example
https://gchq.github.io/CyberChef/#recipe=Gzip('Fixed%20Huffman%20Coding','','',false)&input=aGVsbG8

---

BTW, this tool is brutally awesome.  Awe and respect!

**Comment by n1474335** [comment]
Thanks for raising this. It has now been fixed.

**Comment by SalviaSage** [comment]
Although this was fixed, the 'Loading CharEnc module' is still not fixed!

Please fix this as soon as possible.

I made a post about it here earlier.
https://github.com/gchq/CyberChef/issues/330#issuecomment-429540887
