### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DigiAngel** [gchq/CyberChef#388]
### Summary
TypeError: "exports" is read-only
Filename: blob:null/119605c7-db9f-4a82-9ad4-9acf2b34a936
Line: 1757
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
CyberChef version: 8.8.2s

### Example
Pretty much the above.

**Comment by DigiAngel** [comment]
Link was:  https://gchq.github[.]io/CyberChef/Cyberchef.htm

**Comment by oppiman** [comment]
same here with a local copy 
TypeError: "exports" is read-only
Filename: blob:null/3dfc5d17-c3e9-4919-930a-826e6f766ce2
Line: 1757
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
CyberChef version: 8.8.2s

**Comment by bwhitn** [comment]
Looks like changing the "useBuiltIns" in the .babelrc file from "usage" to "entry" fixes the issue. Not sure if that is a good fix but it seems to work.

**Comment by geekscrapy** [comment]
Issue still present in release v8.8.6

**Comment by n1474335** [comment]
Fixed in #403. Thanks to @bwhitn.
