### ISSUE TITLE
Bug report: AES Encryption with cipher text of null string appended?

### ISSUE THREAD

**Issue by jiegec** [gchq/CyberChef#392]
### Summary

Encrypting a 16-byte text results in its own 16-byte cipher text with cipher text of null string appended.

### Example

[Recipe 1](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'00000000000000000000000000000000'%7D,%7B'option':'Hex','string':''%7D,'ECB','Hex','Hex')&input=MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA)

Encrypt hex "00000000000000000000000000000000" with AES-128-ECB with key hex "00000000000000000000000000000000" results in "66e94bd4ef8a2c3b884cfa59ca342b2e0143db63ee66b0cdff9f69917680151e".

Expected output was "66e94bd4ef8a2c3b884cfa59ca342b2e". But the output was "66e94bd4ef8a2c3b884cfa59ca342b2e" + "0143db63ee66b0cdff9f69917680151e". It can be confirmed that "0143db63ee66b0cdff9f69917680151e" is the cipher text of a null string.

[Recipe 2](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'00000000000000000000000000000000'%7D,%7B'option':'Hex','string':''%7D,'ECB','Hex','Hex'))

**Comment by imhotepisinvisible** [comment]
This doesn't appear to be a bug.  Forge, the crypto library used by this operation, explicitly states that "[CBC and ECB modes use PKCS#7 padding as default](https://github.com/digitalbazaar/forge#cipher)" which is typical for these operation modes.  It can be seen that `0143db63ee66b0cdff9f69917680151e` is the cipher text of a full padding block of 0x10 bytes: [recipe](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'00000000000000000000000000000000'%7D,%7B'option':'Hex','string':''%7D,'ECB','Hex','Hex')&input=MTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTA)

It might be useful though if these operations included the option to disable padding.

**Comment by jiegec** [comment]
Many thanks. Padding mode should be changeable then.
