### ISSUE TITLE
Firefox 62.03 not loading

### ISSUE THREAD

**Issue by Fake4d** [gchq/CyberChef#393]
### Summary
TypeError: e is undefined
Filename: blob:https://example.com/7716361f-8ed8-4fa6-8fe9-341b7ec05921
Line: 1828
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
CyberChef version: 8.8.5s

### Example
Loading the Cyberchef in my Firefox 62.03 not working. I downloaded the html file from https://gchq.github.io/CyberChef/ and uploaded it to my servers in my internal network. Not working... Is there a missing dependency? 

https://gchq.github.io/CyberChef/ is working in my browser!

**Comment by duchenpaul** [comment]
Same issue, I download to my desktop, and it is stuck at loading page, dont know why.

**Comment by duchenpaul** [comment]
Duplicate with #388

**Comment by n1474335** [comment]
Fixed in #403. Thanks to @bwhitn.
