### ISSUE TITLE
Feature request: Add chmod converter

### ISSUE THREAD

**Issue by Perflyst** [gchq/CyberChef#397]
### Add chmod converter

Possibility to convert chmod from e.g. `--x-w--w-` to `122` and the other way around.
Also, a function with checkboxes would be good to create the chmod value in both forms.

**Comment by n1474335** [comment]
One step ahead of you! There is already an operation that does this: https://gchq.github.io/CyberChef/#recipe=Parse_UNIX_file_permissions()&input=LS0teC13LS13LQ

You can enter the permissions in textual or octal format.
