### ISSUE TITLE
CharEnc not loading

### ISSUE THREAD

**Issue by Struttz** [gchq/CyberChef#402]
CharEnc Module failure

### Summary
when Decoding/encoding text the CharEnc module fails to load

**Comment by SalviaSage** [comment]
This issue still persists as of v8.8.0
bwhitn says he fixed this issue in his pull request.

Please look into this matter.

**Comment by echokilo75** [comment]
Loading CharEnc module error still exists in v8.8.5

**Comment by n1474335** [comment]
Fixed in #403. Thanks to @bwhitn.
