### ISSUE TITLE
<!-- Bug report: -->Cyberchef will not load

### ISSUE THREAD

**Issue by garrettds11** [gchq/CyberChef#405]
### Summary

I have tried to launch cyberchef from multiple browsers, multiple machines, and multiple networks, and every time it just infinitely continues to load or doesn't work.

On Chrome, it just keeps circling with random phrases beneath. On Firefox and Edge, I get an error message.

Thanks for your help. I would love to learn to use this tool.

### Example
TypeError: e is undefined
Filename: blob:null/7f58e5b0-4cf4-4a78-8842-db06b4865a5a
Line: 1828
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
CyberChef version: 8.8.5s

**Comment by cecio** [comment]
The same for me (same error on linux FF 63.0). I had to rollback to 8.8.1 (from 8.8.2 is not working any more).

**Comment by bwhitn** [comment]
I have a pull request in that should hopefully fix this  and a few other issues. It looks like an issue when babel was upgraded.
#403

**Comment by dpanic** [comment]
This is problem which I see in 8.8.6

Uncaught TypeError: Cannot set property 'cptable' of undefined

**Comment by newpIDC** [comment]
Kind of surprised to see no one addressing the issue, its been 20+ days since the first report of the issue. We love CC, please fix it.

**Comment by n1474335** [comment]
Fixed in #403. Thanks to @bwhitn.

Apologies for the time it has taken to fix this, I've been preoccupied elsewhere. I'll start looking at ways to prevent this happening again.
