### ISSUE TITLE
Feature request: Clarify base64 options

### ISSUE THREAD

**Issue by leafcutterant** [gchq/CyberChef#410]
When a recipe uses base64, there are multiple alphabets to choose from. However, it's not entirely clear which entry corresponds to which standard. E.g. there are multiple encodings using `A-Za-z0-9+/=`, but which standard is it?

I propose adding the corresponding RFC numbers to the name of the options.

**Comment by n1474335** [comment]
I've added RFC numbers to relevant Base64 alphabets: 
![image](https://user-images.githubusercontent.com/22770796/48713510-63058600-ec08-11e8-9ad8-68faaf3b14a4.png)

However, many of them do not have associated RFCs.
