### ISSUE TITLE
Feature request: Option to sort JSON dictionary keys alphabetically

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#411]
### Summary

Sort the keys in a JSON object alphabetically. This could be an option in the existing 'JSON beautify' operation or an entirely new operation.

### Example

```json
{
    "z": 2,
    "a": "blah",
    "foo": "bar",
    "what": [
        1,
        2
    ]
}
```
becomes
```json
{
    "a": "blah",
    "foo": "bar",
    "what": [
        1,
        2
    ],
    "z": 2
}
```

**Comment by PhillipNordwall** [comment]
Would just a single level of sorting make sense here, or would a recursive sorting option make the most sense?

Would
```
{
    "z": 2,
    "a": "blah",
    "foo": "bar",
    "recursive": {
        "second","b",
        "first","a"
    }
}
```
become

```
{
    "a": "blah",
    "foo": "bar",
    "recursive": {
        "second","b",
        "first","a"
    }
    "z": 2
}
```
or
```
{
    "a": "blah",
    "foo": "bar",
    "recursive": {
        "first","a",
        "second","b"
    }
    "z": 2
}
```
There is also the sort plugin which has line break options, as well as different sorting orders. Would it make more sense to put this there and leverage it's ordering options?
