### ISSUE TITLE
Operation request: Improve padding support in cipher operations

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#416]
### Summary

Currently the cipher operations (AES, DES, 3DES, RC2 etc.) support PKCS#7 padding when in CBC and ECB modes. It would be useful to have more fine-grain control over this with the option to use null padding, or other schemes.

**Comment by owlstead** [comment]
Oh, wow, finding this completely destroyed my confidence in Cyberchef. My goodness, that's a sad state, a utility knife that just has scissors.

**Comment by n1474335** [comment]
NoPadding options have been added for CBC and ECB modes in AES, DES and Triple DES Decrypt operations in v9.37.0 #1189
