### ISSUE TITLE
Operation request: Operate only on a section of the input

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#427]
### Summary

A Flow Control operation to specify that the subsequent operation is only run on a subsection of the input, rather than the whole thing.

The subsection could be defined using a regular expression or offsets.

Instead of the subsection only applying to one operation, the existing 'Merge' operation could be used to define the point at which the entire input is processed again.

### Example

Input
```
123test456
```

Recipe
```
Subsection (or some other more suitable name)
    Section (regex): .{3}([a-z]+).{3}
To Braille
```

Output
```
123⠞⠑⠎⠞456
```

**Comment by n1474335** [comment]
Closed in #467

**Comment by unluddite** [comment]
Hi,

I'm a bit confounded by how to work with this recipe. I have multiple lines of input with a number in it, and I want to extract the numbers and sum them up. Can't seem to get it work, any pointers?

e.g.,

https://gchq.github.io/CyberChef/#recipe=Subsection('%5ENum%20%3D%20(%5C%5Cd%2B)',true,true,false)Merge()Sum('Line%20feed')&input=TnVtID0gMTAKTnVtID0gMjAKTnVtID0gMzAK

**Comment by unluddite** [comment]
Hi,

I'm not sure how to use this Recipe to, say, extract numbers from some lines of input and sum them up. Am I misunderstanding how this is meant to work?

https://gchq.github.io/CyberChef/#recipe=Subsection('%5ENum%20%3D%20(%5C%5Cd%2B)',true,true,false)Merge()Sum('Line%20feed')&input=TnVtID0gMTAKTnVtID0gMjAKTnVtID0gMzAK

Thanks!

**Comment by n1073645** [comment]
Hello,

For the functionality you are looking for I have come up with the following solution:

https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5C%5Cd%2B',true,true,false,false,false,false,'List%20matches')Sum('Line%20feed')&input=TnVtID0gMTAKTnVtID0gMjAKTnVtID0gMzAK
