### ISSUE TITLE
No dependencies?

### ISSUE THREAD

**Issue by Synchro** [gchq/CyberChef#43]
I noticed that the package.json file has no external dependencies at all (except for dev). This seems like a bad idea as it results in the planned obsolescence and excessive bundling highlighted in #2. I'd like to add features that depend on npm packages, but before I do so, I want to know if there is some specific policy about not using external dependencies or whether I should import stuff manually.

**Comment by n1474335** [comment]
Hi @Synchro,

Library management is something that I hope to improve in the coming months. At the moment, any libraries used in the app itself (as opposed to those used in the build process) should be stored in `src/js/lib` or `src/css/lib` and then added to `Gruntfile.js` to get incorporated into the build.

Ultimately we'll probably use some sort of bundler like webpack, but there are various considerations to be made before we decide which route to go down.

I've written up some [Design Principals](https://github.com/gchq/CyberChef/wiki/Contributing#design-principals) and one of them centres around not using too many libraries unless absolutely necessary. If you're going to utilise every feature available in the library, it's probably worthwhile, but if not it can lead to bloat which everyone will have to download even if they never touch that operation. Vanilla JS is preferred if reasonable.

I look forward to your contributions!

**Comment by n1474335** [comment]
This issue will now be tracked in #2. Closing.
