### ISSUE TITLE
Bug report: 'JSON Beautify' and 'JSON Minifiy' are missing test cases.

### ISSUE THREAD

**Issue by PhillipNordwall** [gchq/CyberChef#431]
### Summary
'JSON Beautify' and 'JSON Minifiy' are missing test cases.

These are currently implemented via vkbeautify, which has an intermediate representation in javascript that is more restrictive than JSON.

Test cases around these boundaries should exist in addition to base functionality in case the method of beautification or minimization is changed in the future.

See related Bug #415  ('JSON beautify' operation losing numeric precision)

### Test cases

- empty
- numeric integer
- numeric integer too large for a IEEE 64-bit float (eg. 9007199254740993 )
- numeric float
- numeric float that will get changed as an IEEE 64-bit float (eg. 0.12345678901234567)
- string
- boolean
- empty list
- list
- object
- object nested with all of the above

**Comment by n1474335** [comment]
I'll close this now that the majority of tests have been added. The IEEE 64-bit float tests can be added as part of #415. I don't think we need this issue to remain open as well.
