### ISSUE TITLE
Operation request: DNS over HTTPS resolver

### ISSUE THREAD

**Issue by OllieJC** [gchq/CyberChef#433]
### Summary
A new operation that allows you to specify the DoH resolver (Cloudflare/Google/custom..) and the record type (A/AAAA/SOA/NS etc.) in operation settings and for the input domain name, would return a JSON object with results in.

### Example
Essentially, simplifying what these do:

[https://gchq.github.io/CyberChef/#recipe=HTTP_request('GET','https://cloudflare-d...](https://gchq.github.io/CyberChef/#recipe=HTTP_request('GET','https://cloudflare-dns.com/dns-query?name%3Dgithub.com%26type%3Dtxt','accept:%20application/dns-json','Cross-Origin%20Resource%20Sharing',false)JSON_Beautify('%20'))

[https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn','%5C%5Cn',false)Regis...](https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn','%5C%5Cn',false)Register('//(.%2B?)/',true,true,false)HTTP_request('GET','https://cloudflare-dns.com/dns-query?name%3D$R0%26type%3Dtxt','accept:%20application/dns-json','Cross-Origin%20Resource%20Sharing',false)Regular_expression('User%20defined','%5C%5C%22data%5C%5C%22:%20%5C%5C%22(?:%5C%5C%5C%5C%22)(?%3Cdata%3E.%2B?)(?:%5C%5C%5C%5C%22)%5C%5C%22%7D',true,true,false,false,false,false,'List%20capture%20groups')Merge()&input=aHR0cHM6Ly9nb29nbGUuY29tL3Rlc3RpbmcKaHR0cHM6Ly9iYmMuY28udWsvdGVzdGluZw)

**Comment by OllieGeek** [comment]
I'll be looking at this over the next week 😃

**Comment by n1474335** [comment]
Completed in #489
