### ISSUE TITLE
Feature request: Magic output filter

### ISSUE THREAD

**Issue by ttttmr** [gchq/CyberChef#438]
### Summary

The magic operation is really magic, great, but it has a lot of output, how to filter and search the output of the magic operation, currently I can use the browser search (Ctrl+F), but that is global, I want to only Find in the "Result snippet"

I tried to find it with the "find/replace" operation, it was messed up.

### Example

For example this [mgaic](https://gchq.github.io/CyberChef/#recipe=Magic(3,true,false)&input=ZFY5U1ZBRVRXa0FUZFg5eWRFZ0RDd1FBVlFaU0Nnc0ZDbEJWVmdKU0JRTlFWd0FDQWxjRFYxY0FCMUlCQ2s0NUNnPT0), I want to find out all the decoding results containing "flag", what should I do? I want to have a filter output operation.

and If add the "find/replace" operation below, like this [magic+find](https://gchq.github.io/CyberChef/#recipe=Magic(3,true,false)Find_/_Replace(%7B'option':'Simple%20string','string':'flag'%7D,'',true,false,true,false)&input=ZFY5U1ZBRVRXa0FUZFg5eWRFZ0RDd1FBVlFaU0Nnc0ZDbEJWVmdKU0JRTlFWd0FDQWxjRFYxY0FCMUlCQ2s0NUNnPT0), it shows a mess 

thank you very much

**Comment by n1474335** [comment]
This has been addressed in #445 with the addition of a [Crib](https://en.wikipedia.org/wiki/Known-plaintext_attack) argument.
