### ISSUE TITLE
Translate operation

### ISSUE THREAD

**Issue by Shuunen** [gchq/CyberChef#44]
Hi :)

I'm French developer and because we develop in English, we often need to translate french words to english to create variables or anything.

It would be great to have a translation operation in CyberChef :+1: 

For example to create a slug url from french sentence :
Input text : "Ma page d'accueil"
Translate operation (FR -> EN) : "My homepage"
To lowercase : "my homepage"
Regex to replace whitespaces : "my-homepage"
Tadaaa :golfing_man:

**Comment by n1474335** [comment]
Hi @Shuunen,

I agree that a set of language translation tools would be very useful. Unfortunately all the big names in translation (Google, Bing etc.) charge for the use of their APIs, which doesn't fit very well with an open source product like CyberChef.

If anyone knows of any good, free translation APIs, please let me know. If not, I'll close this issue after a few weeks.

**Comment by cadnce** [comment]
@willemdh  That project appears to have reverse engineered the google translate api to get the tokens (https://github.com/matheuss/google-translate-token) which is somewhat against the google translate [terms and conditions](https://cloud.google.com/terms/). 

> 3.3 Restrictions. Customer will not, and will not allow third parties under its control to: (a) copy, modify, create a derivative work of, reverse engineer, decompile, translate, disassemble, or otherwise attempt to extract any or all of the source code of the Services

Not sure that would be a great thing to bake into this.

**Comment by n1474335** [comment]
@willemdh: As @cadnce points out, this project is breaking the terms of the Google Translate Ts & Cs, so we won't be using it. Thanks for the suggestion though.

I'll close this issue now. If someone does find a good, free, legal translation API, please feel free to re-open.
