### ISSUE TITLE
Broken on ios

### ISSUE THREAD

**Issue by rragan** [gchq/CyberChef#45]
Sometime between November 28 when it worked on an iPad and now, the web app stopped working. In particular, the operations tab no longer appears and the layout of the input/output areas is below the Bake button. Nor do links at the top right function. I suspect a JavaScript error is interrupting the page load but the debugging environment on iOS is not conducive to seeing what is going on.

**Comment by n1474335** [comment]
Hi @rragan,

Thanks for raising this. If you're using a version that you downloaded yourself, it could be suffering from a bug which I fixed in commit e2e68dd8766adad98960c1547bec176ba6071654.

Does it work if you view the [live demo](https://gchq.github.io/CyberChef/)?

**Comment by n1474335** [comment]
I've checked this on an iPad and it seems to be working. Closing this issue, but feel free to re-open it with details if the up-to-date version is still not working for you.

**Comment by sainiravi1** [comment]
Hi,

Facing same issue on windows, with firefox and cyberchef V 9.16.2 (https://gchq.github.io/CyberChef/).
the operations tab no longer appears and the layout of the input/output areas is below the Bake button. Nor do links at the top right function.

Any fixes??
![bug](https://user-images.githubusercontent.com/43011995/76699517-544ba980-666b-11ea-8ba5-7cbd1d0b6dfb.png)
