### ISSUE TITLE
Operation request: Image manipulation operations from Jimp

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#451]
### Summary

Now that we have introduced the [Jimp](https://github.com/oliver-moran/jimp) library in #448, we should make better use of its capabilities.

Operations could be added to do some of the following:

- contain - Contain an image within a height and width.
- cover - Scale the image so the given width and height keeping the aspect ratio.
- dither - Apply a dither effect to an image.
- flip - Flip an image along it's x or y axis.
- gaussian - Hardcore blur.
- invert - Invert an images colors
- print - Print text onto an image
- resize - Resize an image.
- rotate - Rotate and image.
- scale - Uniformly scales the image by a factor.

**Comment by klaxon1** [comment]
i should have something soon for this.

**Comment by n1474335** [comment]
Closed in #506. Thanks to @j433866!
