### ISSUE TITLE
Split file by offset

### ISSUE THREAD

**Issue by MariasStory** [gchq/CyberChef#454]
This is a feature request.
Please add option to split file by offset. It is also useful to be used in combination with "Scan for Embedded Files" or extracting another interesting information. Maybe the splitting could have a list of offsets to split on?

**Comment by n1474335** [comment]
This is already possible using the [Take bytes](https://gchq.github.io/CyberChef/#recipe=Take_bytes(3,5,false)&input=MDEyMzQ1Njc4OQ) operation.

I am currently working on a PR (#440) that will add a new operation called 'Extract files' which will attempt to locate files within the data, parse them correctly to find their exact length, and extract them for you.
