### ISSUE TITLE
Feature Request: Button for selecting File for input

### ISSUE THREAD

**Issue by masq** [gchq/CyberChef#460]
### Summary
Right now, in order to import a file as input to CyberChef, you must drag and drop a file into the input box. This is pretty handy at times! However, it's:
- Not clear to users that that's available as an option, and 
- Sometimes not user-friendly, particularly when one doesn't have a traditional Window Manager, for example if using i3wm.
It would be nice if there were a button along the input box that upon clicking would prompt a user to select a file (or files?) from their filesystem that they would like to import as input to CyberChef.

### Example
[File chooser prompt in Google Chrome on MacOS](https://blog.mariusschulz.com/content/images/mac-osx-file-selection-dialog.png)
[Example File Chooser Button in CyberChef using 'input' as the icon](https://imgur.com/fExp8LA)

**Comment by n1474335** [comment]
Closed in #478
