### ISSUE TITLE
Operation Request - de bruijn sequence generator

### ISSUE THREAD

**Issue by chudel** [gchq/CyberChef#463]
de bruijn sequence generator

### Summary
Request the addition of a "de bruijn sequence generator" that can generate rolling keycode combinations for use with such lock mechanisms/systems.

### Example
System would accept a `k` and `n` value and generate a sequence appropriately.  See http://www.hakank.org/comb/debruijn.cgi for reference and additional information.

Bonus enhancement: would be to provide a comma separated list of values for k, for example "1,2,3,4" "A,B,C,D", "Square, Triangle, Circle, Line".

**Comment by n1474335** [comment]
Closed in #493
