### ISSUE TITLE
Feature Request: URL Encode All Characters Option

### ISSUE THREAD

**Issue by resech** [gchq/CyberChef#464]
### Summary

There's times where it's handy to encode all characters, it'd be awesome if we had an option for this in the URL Encode Operation or if we could select "%" as a delimiter in To Hex. It looks like this request is similar to #56 

### Example
Encode `Hello, World!` as `%48%65%6c%6c%6f%2c%20%57%6f%72%6c%64%21` instead of `Hello,%20World!`

**Comment by chudel** [comment]
Of course, this is possible already by combining ToHex and Regex Find/Replace?  See this [Recipe](https://gchq.github.io/CyberChef/#recipe=To_Hex('Space')Find_/_Replace(%7B'option':'Regex','string':'%5E%7C%20'%7D,'%25',true,false,true,false)&input=SGVsbG8sIFdvcmxkIQ):

**Comment by n1474335** [comment]
Whilst this can be achieved using Find/Replace, I think it would make a reasonable inclusion to either the 'URL Encode' or 'To Hex' operations.
