### ISSUE TITLE
Broken on IOS

### ISSUE THREAD

**Issue by rragan** [gchq/CyberChef#47]
Re Issue #45 that was closed. It still seems broken on my iPad running ios 9 with Chrome. I sleuthed where the breakage seemed to be. It works at this commit:

https://cdn.rawgit.com/gchq/CyberChef/a4c9bb890746cbea09de1b775f64b21577c59362/cyberchef.htm

and fails at the next commit:

https://cdn.rawgit.com/gchq/CyberChef/7bcf560ff15ba59379b7af14b98498b5b5a924d7/cyberchef.htm

The only change at that commit is the switch from jsHint to EsLint so I think it must be something esLint is doing or maybe the order files are being packaged and maybe two functions with the same name but different load orders -- just theories.

**Comment by rragan** [comment]
I got the IOS device hooked to the webkit debugger and found the error stopping the page from loading. The complaint is about two instances of the use of "const" which used to be "var" and the message indicates that "const" is not allowed in strict mode.  If I hack the "const" instances back to "var", the page loads and works.

My Safari version string is AppleWebKit/601.1.46 (KHTML...)Version/9.0 Movile/13G26 Safari/601.1.

Run from Chrome which is the only IOS browser that handles CyberChef I see the exact same User Agent string. Odd but then it is a Webkit engine.

**Comment by n1474335** [comment]
Hi @rragan,

Thanks for giving me the details. I've pushed a fix for this now. Closing.
