### ISSUE TITLE
Bug report: ToBase64 description is incorrect

### ISSUE THREAD

**Issue by PrinceOfCreation** [gchq/CyberChef#472]
### Summary
The description when moving mouse over the recipe ToBase64 is incorrect. It is actually the same as the FromBase64 recipe. An example is below.

### Example

When mousing over recipe ToBase64 in the menu, the description:

```
Base64 is a notation for encoding arbitrary byte data using a restricted set of symbols that can be conveniently used by humans and processed by computers.

This operation decodes data from an ASCII Base64 string back into its raw format.

e.g. aGVsbG8= becomes hello

Base64open_in_new on Wikipedia
```

appears.

This is wrong, and in fact is the same description for FromBase64. It is correct for FromBase64, but I believe ToBase64 should look a bit like this:

```
Base64 is a notation for encoding arbitrary byte data using a restricted set of symbols that can be conveniently used by humans and processed by computers.

This operation encodes data from its raw format to an ASCII Base64 string.

e.g. hello becomes aGVsbG8=

Base64open_in_new on Wikipedia
```

### Information
* Version: 8.22.0
* Compile time: 10/01/2019 15:47:05 UTC
* User-Agent: [I am using Edge]
* [Link to reproduce](https://gchq.github.io/CyberChef/)

**Comment by n1474335** [comment]
Fixed in #473
