### ISSUE TITLE
simple docker for dev

### ISSUE THREAD

**Issue by GelosSnake** [gchq/CyberChef#474]
### Summary
Created a very simple docker file to make running CyberChef pretty easily.
https://github.com/GelosSnake/CyberChefDocker

### Example
You can run it with the following command:
docker container run -d -p 8080:8080 malwareresearch/cyberchef

Thought might be useful for others.

**Comment by n1474335** [comment]
Great stuff, thanks very much. We'll probably be working on full containerisation at some point with the NodeAPI (#291).

**Comment by nileshtrivedi** [comment]
I think this issue needs to be reopened. #291 was merged in July 2019 but no work has been done on providing a Dockerfile for either development or production deployment. A dockerfile would be useful for easy one-click-install in various platform-as-a-service setups like CapRover.
