### ISSUE TITLE
Bug report: Adding "Register" breaks "From Base" with "Data is not a valid BigNumber" error

### ISSUE THREAD

**Issue by tobek** [gchq/CyberChef#481]
Prepending the "From Base" operation with the "Register" operation produces an error "Data is not a valid BigNumber".

Here is an example: https://gchq.github.io/CyberChef/#recipe=Register('(.*)',true,false,false)From_Base(16)&input=MHgyMGE

![image](https://user-images.githubusercontent.com/3081073/51620761-13da1b00-1f01-11e9-8878-320fe0f3aea6.png)

Expected output should just be `522`. Removing the Register operation does _not_ fix the bug, unless you remove it and then refresh.

**Comment by Sh1n0g1** [comment]
I got  the same error using Filter. I guess that Regex doing something bad.
https://gchq.github.io/CyberChef/#recipe=Filter('Line%20feed','%5E%5C%5Cd*$',false)Multiply('Line%20feed')&input=MTAKMTIwCjMwCg

**Comment by n1474335** [comment]
Thanks for pointing this out. It's a really strange one. It seems to only be a problem when you load in an operation from the Regex module. This module imports XRegExp which seems to break the BigNumber.js library in some way, causing BigNumbers to fail the `instanceof BigNumber` check.

I don't fully understand why this happens, but there is a handy helper function in the BigNumber library called `isBigNumber` which can be used instead and fixes things.
