### ISSUE TITLE
Bug report:XSS on "To Table" operation

### ISSUE THREAD

**Issue by Sh1n0g1** [gchq/CyberChef#483]
### Summary
To Table is not escaping ``<``. ``>`` symbols, which triggers an XSS vulnerability.

![totable_xss](https://user-images.githubusercontent.com/7097845/51976665-99913400-24c8-11e9-8216-6778b7547275.png)
### Example
Input: <script>alert(1)</script>,
Recipe: To_Table(',','\\r\\n',false,'ASCII')

https://gchq.github.io/CyberChef/#recipe=To_Table(',','%5C%5Cn%5C%5Cr',false,'ASCII')&input=PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Piw

**Comment by n1474335** [comment]
Thanks for raising this. Fixed in #488 and merged in v8.23.3
