### ISSUE TITLE
Bug report: HTML not escaped properly

### ISSUE THREAD

**Issue by edwardwall** [gchq/CyberChef#490]
### Summary
When building an HTML options list the value is not escaped. This causes some of the value to be displayed in the name.

### Example

This is a problem for RegExs because some contain a `"` followed by a `>` which causes part of the regex to appear in the name because the HTML is parsed incorrectly, as shown below.

![image](https://user-images.githubusercontent.com/33730573/52420379-e5a43000-2ae9-11e9-9496-c3539e0ecb1f.png)

![image](https://user-images.githubusercontent.com/33730573/52420255-9f4ed100-2ae9-11e9-8900-44305e88d7f9.png)

[Link to show bug](https://gchq.github.io/CyberChef/#recipe=Regular_expression('%5C%5C%5B%5C%5C%5D%7B%7D%5C%5Cs%5C%5Cx7F-%5C%5CxFF%5D*(?:%5B.!,?%5D%2B%5B%5E.!,?%22%3C%3E%5C%5C%5B%5C%5C%5D%7B%7D%5C%5Cs%5C%5Cx7F-%5C%5CxFF%5D%2B)*)?%22%3EURL','(%5BA-Za-z%5D%2B://)(%5B-%5C%5Cw%5D%2B(?:%5C%5C.%5C%5Cw%5B-%5C%5Cw%5D*)%2B)(:%5C%5Cd%2B)?(/%5B%5E.!,?',true,true,false,false,false,false,'Highlight%20matches'))

This issue comes from Line 159 and is present in other places, where the HTML value is not escaped, but the values don't trigger it https://github.com/gchq/CyberChef/blob/6f8a5ea1be18bca1ea5192a185fb79d746576170/src/web/HTMLIngredient.mjs#L159

**Comment by n1474335** [comment]
Good spot, thanks. This has now been fixed in v8.23.4.
