### ISSUE TITLE
Feature request: Show/hide operation arguments depending on other argument values

### ISSUE THREAD

**Issue by j433866** [gchq/CyberChef#491]
### Summary
In some operations, some arguments may be unnecessary depending on the value of other arguments.  For example, in 'Convert co-ordinate format', the compass directions argument isn't needed for output formats like Geohash or MGRS. It would be useful to be able to hide these arguments when they aren't needed, or maybe just disable them so we don't have the UI jumping around.

**Comment by n1474335** [comment]
There actually used to be support for this, but it wasn't very robust so I removed it for simplicity when we released CyberChef into open source. It would definitely be worthwhile reimplementing it. There are several operations where it would make sense.

**Comment by j433866** [comment]
Added in c005c86c276eb8a9f16ebb82b21ce1cb94779c66
