### ISSUE TITLE
use babel and babel-preset-env

### ISSUE THREAD

**Issue by graingert** [gchq/CyberChef#5]
Using the following babel config you can encode your supported browsers:

```
{
  "presets": [
    ["env", {
      "targets": {
        "chrome": 55,
        "firefox": 50,
      },
      "modules": false,
    }]
  ]
}
```

This way you'll be able to use all features of es2016 and those features not supported in chrome or firefox will be automatically translated by babel.

modules: false is set because module bundlers need the "import/export" keywords to create an optimized bundle.

**Comment by n1474335** [comment]
Completed in #95
