### ISSUE TITLE
Operation request: Tar and Untar

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#50]
**Request summary**

Development of operations to Tar and Untar input data.

**Example input and output**

*Untar*
Input: [Test.tar.txt](https://github.com/gchq/CyberChef/files/696917/Test.tar.txt)
Output: Should list both filenames and the file contents. Similar output to the *Unzip* operation.

**Resources**

[https://en.wikipedia.org/wiki/Tar_(computing)](https://en.wikipedia.org/wiki/Tar_(computing))

**Comment by tlwr** [comment]
This can be closed now that #71 is merged
