### ISSUE TITLE
Feature request: File input as operation argument type

### ISSUE THREAD

**Issue by j433866** [gchq/CyberChef#504]
### Summary
It could be useful to be able to input a file as an operation argument, which would enable us to have operations for file comparisons or combining files.

### Example
An operation could be created to mimic the `diff` unix command.

**Comment by n1474335** [comment]
The `text` argument allows loading of files.

For example, you can drag a file over the Public Key argument here:
https://gchq.github.io/CyberChef/#recipe=RSA_Encrypt('-----BEGIN%20RSA%20PUBLIC%20KEY-----','RSA-OAEP','SHA-1')&input=YWJj
