### ISSUE TITLE
Bug report : Error during build

### ISSUE THREAD

**Issue by pierremahot** [gchq/CyberChef#508]
### Summary
Environement :
OS: Docker UBUNTU 18.04
Offline with an npm mirror
Node version : 8.10.0
npm version : 3.5.2

since cyberchef V8.24.2

Command  : grunt node
error durring webpack:generateConfig
message : 
```--- Regenerating config files. ---
Written operation index.
>> SyntaxError: Unexpected tocken import
>>     at ModuleJob.loaders.set [as module Provider] (internal/loader/moduleRequest.js:33.13
>>     at <anonimous>
--- config scripts finished. ---```

**Comment by DBHeise** [comment]
That version of nodeJS does not support the es6 imports. You need to upgrade to at least version 9.0 to get that support. 

Here's an answer with various ways to do this on a clean *nix install: https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by pierremahot** [comment]
We update to nodejs ltd 10 and it resolves the problem thanks you
