### ISSUE TITLE
Classical homophonic ciphers

### ISSUE THREAD

**Issue by be4** [gchq/CyberChef#513]
### Summary
Do you have plan to include homophonic ciphers (which are used e.g. by Zodiac)?

**Comment by ct-online** [comment]
Could you please add a comment: Was this issue closed and solved; or was it just closed without solving it?

**Comment by n1073645** [comment]
It is quite a broad issue to cast, we will continue to add ciphers(including homophonic ones) over time. Rather than having a dedicated PR including a lot of them. Something like this will comprise of multiple issues/PRs.

**Comment by ct-online** [comment]
Thanks a lot
