### ISSUE TITLE
Adding crypanalysis methods

### ISSUE THREAD

**Issue by be4** [gchq/CyberChef#514]
### Summary
CyberChef is a mighty tool to do encryption and decryption operations with many ciphers within a browser. However, what is completely missing, are tools for doing cryptanalysis.

Do you have plans to add these? Would you support others adding such tools?

**Comment by n1474335** [comment]
Yes, absolutely. I'll close this issue for now since it isn't asking for anything specific (and I'm trying to tidy things up a bit!) but I'd welcome the addition of more cryptanalysis-style operations.
