### ISSUE TITLE
Simple math operations

### ISSUE THREAD

**Issue by tbearden** [gchq/CyberChef#517]
Similar to #208 and #215, it would be very helpful to support basic math operations on a delimited input.

For example, I have a string 'pjwsjq873iqq?[nwyzfqUwtyjhy', and want to be to able to 'To Decimal', subtract 5 from each decimal, 'From Decimal', with a final output of 'kernev32.dll:VirtualProtect'

**Comment by s2224834** [comment]
You can do this sort of byte maths already:
https://gchq.github.io/CyberChef/#recipe=SUB(%7B'option':'Hex','string':'05'%7D)&input=cGp3c2pxODczaXFxP1tud3l6ZnFVd3R5amh5
