### ISSUE TITLE
Feature request: Add BLAKE family of hash functions

### ISSUE THREAD

**Issue by grempe** [gchq/CyberChef#523]
### Summary

Please support the BLAKE family of hashing functions. In particular BLAKE2b and BLAKE2s at common bit-lengths.

https://blake2.net/
https://en.wikipedia.org/wiki/BLAKE_%28hash_function%29

**Comment by n1474335** [comment]
Closed in #525

**Comment by grempe** [comment]
Excellent thank you @n1474335 !
