### ISSUE TITLE
Operation request: MD6 hashing

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#53]
**Request summary**

Development of an operation to calculate MD6 hashes. CyberChef already supports MD5 hashing thanks to CryptoJS ([example ](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22MD5%22%2C%22args%22%3A%5B%5D%7D%5D&input=VGVzdA)and [code](https://github.com/gchq/CyberChef/blob/master/src/js/operations/Hash.js#L14)).

**Arguments**

- Output length - Allow the user to specify the digest length from a list including at least 128, 256, and 512 (see [SHA3](https://github.com/gchq/CyberChef/blob/master/src/js/operations/Hash.js#L92) for an example)

**Example input and output**

*Digest length == 128*
Input: Test
Output: bc7e7a90c6610310a6c386ba0482c889

*Digest length == 256*
Input: Test
Output: 2543e1c393d880e4564fed11f15d03ade6c5ccb9dbbd45ff1808010cbd82bdd2

*Digest length == 512*
Input: Test
Output: 702fd91632a6df15bb5041eb2ea031f7b931564eeb5324e92250bf2f4a8cb5eb7f40a607341b1ede16c880040bd04ab828f9aa81b5da3967111cdcdafd390839

**Resources**

https://en.wikipedia.org/wiki/MD6
http://groups.csail.mit.edu/cis/md6/submitted-2008-10-27/Supporting_Documentation/md6_report.pdf
http://groups.csail.mit.edu/cis/md6/ - An implementation in C can be found in the Downloads section
https://github.com/Snack-X/md6 - Includes a JavaScript implementation (which will need to be checked for correctness)

**Comment by graingert** [comment]
MD6 is supposed to be parallel, it would be cool to WASM compile a version with pthreads supported to take advantage of this property.
