### ISSUE TITLE
Operation Request: Add CRC-8 Checksum

### ISSUE THREAD

**Issue by Jerkiller** [gchq/CyberChef#543]
### Summary
Cyberchef is great!
Could you please add the CRC-8 checksum calculation for a given byte list?
This could be very useful for people who need to calculate checksum of little data.

### Example
Input: 59 4C CA 80 02 01 00 11 22 33 44 55 66 77
Output: 4D (CRC-8 ITU-T)

A super-plus could be the possibility to choose between the various CRC-8 algorithms (MAXIM, ITU, DARC...).
An example of the various algorithms could be found at https://crccalc.com/.

**Comment by n1474335** [comment]
Closed in #591
