### ISSUE TITLE
Bug report: Current release version (v8.31.1) does not include the recent XSS fix

### ISSUE THREAD

**Issue by dougburks** [gchq/CyberChef#544]
### Summary
It looks like #539 has been fixed in https://github.com/gchq/CyberChef/commit/01f0625d6a177f9c5df9281f12a27c814c2d8bcf, but no release has been issued since the fix.  Would it be possible to do a quick release (v8.31.2) to include the XSS fix?  Thanks in advance for your consideration!

**Comment by j433866** [comment]
This fix has been included in v18.31.3

**Comment by dougburks** [comment]
Thanks so much!
