### ISSUE TITLE
Feature Request:  Defang IPv4 Address

### ISSUE THREAD

**Issue by co-devs** [gchq/CyberChef#553]
### Summary
Requesting a new feature to defang IP addresses by replacing . with [.], similar to the URL defang operation that currently exists

### Example

**Valid IP Address**

- Input: 8.8.8.8
- Output: 8[.]8[.]8[.]8

**Invalid IP Address**

- Input: 12.300.40.6
- Output: 12.300.40.6

**Comment by n1474335** [comment]
Closed in #556
