### ISSUE TITLE
Bug report: Loaded Regex recipe has an empty pattern if it contained a forward slash

### ISSUE THREAD

**Issue by ilyaglow** [gchq/CyberChef#555]
### Summary
The loaded regex recipe has an empty pattern field if it contained a forward slash.
Looks similar to #319.

### Example
https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','b/',true,true,false,false,false,false,'List%20matches')&input=YQplLwpiLwovZA

**Comment by j433866** [comment]
Duplicate of #532
