### ISSUE TITLE
Feature Request: Option to change Enigma output grouping size

### ISSUE THREAD

**Issue by Willt125** [gchq/CyberChef#558]
### Feature request:

I would like to suggest that the Enigma and maybe Typex(?) operation have the ability to choose the grouping size, or turn off grouping altogether (although I don't care as much about that). Instead of being forced to use the five-character grouping that is the default, I'd like to be able to have the output grouped into other sizes, like four-character as used by the Kriegsmarine. It's not *too* important, but it can be helpful with formatting large encryptions. Thank you for your time, and this amazing set of tools!

**Comment by n1474335** [comment]
This can be achieved using the following recipe: https://gchq.github.io/CyberChef/#recipe=Enigma('3-rotor','LEYJVCNIXWPBQMDRTAKZGFUHOS','A','A','EKMFLGDQVZNTOWYHXUSPAIBRCJ%3CR','A','A','AJDKSIRUXBLHWTMCQGZNPYFVOE%3CF','A','A','BDFHJLCPRTXVZNYEIWGAKMUSQO%3CW','A','A','AY%20BR%20CU%20DH%20EQ%20FS%20GL%20IP%20JX%20KN%20MO%20TZ%20VW','',true)Remove_whitespace(true,true,true,true,true,false)Find_/_Replace(%7B'option':'Regex','string':'(.%7B4%7D)'%7D,'$1%20',true,false,false,true)&input=VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZy4

Simply change the number in the 'Find' field of 'Find / Replace' to modify the group size.
