### ISSUE TITLE
Feature request: AES encryption and decryption should support no padding mode

### ISSUE THREAD

**Issue by jeffli678** [gchq/CyberChef#567]
I get some ciphertext encrypted with AES but has no padding. I tried to decrypt it in CyberChef but fails. I think there are two possible improvements:

1. When an operation fails, give more information on the failure rather than simply say the decryption fails. As for this case, after some research, I found the problem is the CyberChef assumes the ciphertext comes with PKCS 7 padding. However, my input does not have any padding, so it fails. Had CyberChef been able to tell me about this, I would have figured out the problem earlier. See also #392 

2. Allow the user to select whether or not to use padding.

**Comment by Storms-Engineering** [comment]
Doing some research on how to specify what padding to use in node-forge

**Comment by Storms-Engineering** [comment]
I believe I got it working.  But I am trying to fix the tests that it broke since I added a new parameter to the config of AES encrypt/decrypt.

**Comment by n1474335** [comment]
NoPadding options have been added for CBC and ECB modes in AES, DES and Triple DES Decrypt operations in v9.37.0 #1189
