### ISSUE TITLE
Feature request: Attempt To Determine Type

### ISSUE THREAD

**Issue by wazcov** [gchq/CyberChef#570]
It would be nice if a bunch of input was guessed for its type. So let's say you paste a load of binary data, it automatically guessed that it was binary and not say hex or json, and offered the binary step as an option. This would be similar to the way that Google Translate works, when you type in some Spanish, after a word or two, it realises and offers to translate from Spanish instead of French/German etc.

**Comment by n1474335** [comment]
This is what the Magic operation does already. Look out for the magic wand icon in the Output pane. Details here: https://github.com/gchq/CyberChef/wiki/Automatic-detection-of-encoded-data-using-CyberChef-Magic#automated-background-magic
