### ISSUE TITLE
Feature request: add padding option to block ciphers

### ISSUE THREAD

**Issue by NyaMisty** [gchq/CyberChef#574]
### Summary
The DES and AES are using PKCS#7 padding all the time, even if the original data is not padded. That's causing ```Unable to decrypt input with these parameters.``` in the CyberChef.
We can add a new option for user to specify the padding method.

**Comment by j433866** [comment]
Duplicate of #416

**Comment by NyaMisty** [comment]
Sorry I forgot to search first. I apologize 😣
