### ISSUE TITLE
Bug report: XSS in Object_Identifier_to_Hex and any snackbar alert

### ISSUE THREAD

**Issue by mariolima** [gchq/CyberChef#576]
### Summary
The snackbar alert that is displayed on every `handleError()` function call and consequentially `alert()` https://github.com/gchq/CyberChef/blob/3ff10bfeaebad28c72ceff53f8c78ebb4ebb0755/src/web/App.mjs#L592 is vulnerable to self-XSS due to the fact the it allows any text to be rendered as HTML - as per in https://github.com/gchq/CyberChef/blob/3ff10bfeaebad28c72ceff53f8c78ebb4ebb0755/src/web/App.mjs#L603

### Example
Cooking the recipe `Object_Identifier_to_Hex` with `<script>alert(document.domain)</script>` successfully executes the javascript code inputed.
https://gchq.github.io/CyberChef/#recipe=Object_Identifier_to_Hex()&input=PHNjcmlwdD5hbGVydChkb2N1bWVudC5kb21haW4pPC9zY3JpcHQ%2B

**Comment by j433866** [comment]
This has been fixed now, thanks for bringing it to our attention.
