### ISSUE TITLE
Bug report: HTML Entities missing

### ISSUE THREAD

**Issue by apolkosnik** [gchq/CyberChef#577]
Bug report: HTML Entities missing

### Summary
The byteToEntity lookup table at:
 https://github.com/gchq/CyberChef/blob/master/src/core/operations/ToHTMLEntity.mjs#L89

and the entityToByte  lookup table at:
https://github.com/gchq/CyberChef/blob/master/src/core/operations/FromHTMLEntity.mjs#L86
need to be updated to contain the current list of HTML Entities or at least what's listed at: https://dev.w3.org/html5/html-author/charref

### Example
neither of the following entities are converted with "From HTML Entity": ```&sol; &dollar; &Tab;```

**Comment by n1474335** [comment]
Fixed in #579
