### ISSUE TITLE
Not working on Microsoft Edge 42.17134.1.0

### ISSUE THREAD

**Issue by talpeleg1** [gchq/CyberChef#587]
My browser version: Microsoft Edge 42.17134.1.0
The error I received:

```CyberChef encountered an error while loading.

The following browser versions are supported:
Google Chrome 40+
Mozilla Firefox 35+
Microsoft Edge 14+
Your user agent is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

If your browser is supported, please raise an issue including the following details:

Expected identifier, string or number
Filename: https://gchq.github.io/CyberChef/assets/main.js
Line: 105
Column: 52593
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
CyberChef version: 8.33.1```

**Comment by talpeleg1** [comment]
This happened on the sample version. Have not looked at it since though,
just downloaded firefox on my new laptop.

**Comment by n1474335** [comment]
We've recently dropped support for Edge. See the [supported browsers](https://github.com/gchq/CyberChef/blob/master/README.md#browser-support) in the README file.

However, when the [new Chromium version of Edge](https://en.wikipedia.org/wiki/Microsoft_Edge#Discontinuation_of_EdgeHTML_and_adoption_of_Chromium_(2019%E2%80%93present)) is released, we expect it to work fairly well.
