### ISSUE TITLE
small css issue in firefox

### ISSUE THREAD

**Issue by the-wazz** [gchq/CyberChef#59]
firefox 48.0.2.

About/Support dialog > FAQs tab:

the anchors on the current 3 faqs for some reason do not create the usual cursor (pointer). not sure why. the blockquote??

possible fixes (not all checked):
- add ids
- blockquote a { cursor: pointer; }
- a[data-target='#faq-examples'] { cursor: pointer; }
- a[data-target='#faq-load-files'] { cursor: pointer; }
- a[data-target='#faq-fork'] { cursor: pointer; }

other...

html (starting line 301): https://github.com/gchq/CyberChef/blob/master/src/html/index.html

**Comment by n1474335** [comment]
Thanks for pointing this out. It seems to be affecting Chrome as well. Rolling out a fix now.
