### ISSUE TITLE
Feature request: HTML Decimal Encoding/Decoding

### ISSUE THREAD

**Issue by electroxero** [gchq/CyberChef#590]
**HTML Decimal Encoding**
When you want to encode some character in HTML you can use also the Deciamal Encoding
[https://www.ascii.cl/htmlcodes.htm](url)

**Example**
I want to encode the word `home` -> `&#104;&#111;&#109;&#101;`

`&#104;` For example is the letter `h` in ASCI

**Comment by n1474335** [comment]
This is supported by the 'To HTML Entity' operation: https://gchq.github.io/CyberChef/#recipe=To_HTML_Entity(true,'Numeric%20entities')&input=aG9tZQ
