### ISSUE TITLE
Operation request: GOST block cipher

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#592]
###  Summary

Since the Streebog and GOST hashes were added, we now have the capability to implement the GOST block cipher. It would be great to have operations for encrypting and decrypting GOST ciphers.

Details here: http://gostcrypto.com/doc/GostCipher.html

**Comment by Nguyentiensy99** [comment]
Hoàn thành giúp tôi bạn nhé xin cảm ơn

**Comment by n1474335** [comment]
@Nguyentiensy99 Xin chào, cảm ơn tin nhắn của bạn. Chúng tôi hoan nghênh sự đóng góp từ bạn!

**Comment by n1474335** [comment]
Completed in v10.5.0
