### ISSUE TITLE
Bug report: Magic operation output is unreadable in dark mode

### ISSUE THREAD

**Issue by phil-ncsc** [gchq/CyberChef#599]
**Describe the bug**
When using the `Magic` operation, the resulting output is hardcoded to be black text, meaning it is unreadable when using any of the dark themes (or GeoCities)

**To Reproduce**
With the theme set to dark, use the `Magic` operation to produce any output.

**Expected behavior**
The output switches to a white text colour to ensure it is readable when in dark mode.

**Screenshots**
<img width="1320" alt="Screenshot 2019-07-16 at 13 40 51" src="https://user-images.githubusercontent.com/52707208/61295318-ad5af900-a7cf-11e9-9080-61d1762f90b2.png">
<img width="1320" alt="Screenshot 2019-07-16 at 13 44 55" src="https://user-images.githubusercontent.com/52707208/61295430-eb581d00-a7cf-11e9-9843-81da584c1206.png">

**Desktop (if relevant, please complete the following information):**
 - OS: MacOS
 - Browser: Safari (also verified in Chrome)
 - Version 12.1.1

**Comment by anushibin007** [comment]
Similar problem with the Keybindings page in About/Support.

![image](https://user-images.githubusercontent.com/22093731/61352033-f1aacf80-a889-11e9-8397-b106ba4b07ee.png)

![image](https://user-images.githubusercontent.com/22093731/61352076-1141f800-a88a-11e9-8c1e-34f21d769f7e.png)

OS: Windows 10
Browser: Chrome
Version 75.0.3x
