### ISSUE TITLE
Operation request: GPG encryption/decryption support

### ISSUE THREAD

**Issue by antonywu** [gchq/CyberChef#6]
It is a feature request. It would be great to have GPG based (d)encryption that processes texts, either by encrypting (with a public key) or dencrypting messages (with a private key).

**Comment by jp-costa** [comment]
would OpenPGP.js be good starting point for this?

**Comment by seefood** [comment]
I'm using CC for basic demos in talks, and at the very least I'd like to show RSA encrypt and descrypt of a 128 or 256 bit number. nothing fancier needed. Is there anyone looking into this or should I try and dive in myself?

**Comment by tlwr** [comment]
Yeah in a (very old) branch I've got some PGP operations working using OpenPGP.js.

Branch: https://github.com/tlwr/CyberChef/commits/feature-async-ops

This was before CC supported async operations or had modules.

At some point I'll get around to making it a module :)

**Comment by tlwr** [comment]
Just wanted to update this

I've pulled all of my old code into a new branch in a single commit [here](https://github.com/tlwr/CyberChef/commit/728d9066fedda71093b516f9a378e8df76d0cf5b) and attempted to get it all to work with the new module system.

I'm not quite getting it to build at the moment, and I don't have a ton of time to work on it at present - if you want to quickly get PGP to work in CC then this might be a good starting point.

--

As a side note, 99% of the time I use CC it is for hashing or crypto. Having `gpg`, `keytool`, and `openssl` packaged up in CC would be a dream come true. (Done in the GeoCities theme obviously).

**Comment by seefood** [comment]
You use it for actual work? I do it all on the commandline, using CC just for demos and teaching talks.

BTW, if you use GPG a lot, have a look at keybase.io -> A very nice commandline wrapper for your regular functions but also so much more.

**Comment by tlwr** [comment]
I'm a big fan of keybase 👍

When I'm working on my local machine with my regular toolchain and dotfiles (repo in keybase now) I'll do almost everything from the command line.

However when working on a VM or on a remote (where I don't / can't have my tools) then I'll split windows and have a terminal on one half and a browser window with a bunch of CC tabs on the other half. I've also found CC is great for pair programming.

**Comment by n1474335** [comment]
@tlwr Thanks for pulling that PGP module together. I'll take a look at getting it working properly. If you submit a PR for it, I can merge it once it's working.

**Comment by tlwr** [comment]
Put it in a PR (#195)  so it is obvious that we're working on it, however I haven't yet had a chance to have a look at it...

**Comment by n1474335** [comment]
I've just merged #206 which introduces five new operations:
- Generate PGP Key Pair
- PGP Encrypt
- PGP Decrypt
- PGP Encrypt and Sign
- PGP Decrypt and Verify

More utility functions could probably be added at a later date but I'll close this issue for now.
