### ISSUE TITLE
Bug report:To Hex and From Hex does not give expected output.

### ISSUE THREAD

**Issue by n4l0cks** [gchq/CyberChef#609]
Bug report:To Hex and From Hex does not give expected output.

Giving input to either To Hex or From Hex does not result in expected output.

Using Cyberchef and giving the following input "12947848928752043" to the function To Hex produces the following output "3132393437383438393238373532303433". However, providing the same input on the site https://www.binaryhexconverter.com/decimal-to-hex-converter give the following output "2E00000000F1AB".

The same goes with the opposite. Providing the following output "2E00000000F1AB" to the function From Hex produces ".....ñ«" while at the binaryhex-website produces "12947848928752043".

**Desktop (if relevant, please complete the following information):**
 - OS: Windows 10 Enterprise, 1703
 - Browser Firefox Quantum
 - Version 68.0.1 (64-bit

Disclaimer: I'm a bit new to this but I figured it was something strange but maybe I'm just missing some kind of critical information. Sorry if I wasted your time!

**Comment by j433866** [comment]
When using To / From Hex, CyberChef treats the input as a UTF-8 string, not a numerical value, whereas a decimal to hex converter will treat it as a decimal number.

To get the same result using CyberChef, you can use the [To Base operation](https://gchq.github.io/CyberChef/#recipe=To_Base(16)&input=MTI5NDc4NDg5Mjg3NTIwNDM) to convert to a hexadecimal number, and the [From Base operation](https://gchq.github.io/CyberChef/#recipe=From_Base(16)&input=MkUwMDAwMDAwMEYxQUI) to convert it back to a decimal number.
