### ISSUE TITLE
Bug report: JSON to CSV not working for me

### ISSUE THREAD

**Issue by Fake4d** [gchq/CyberChef#610]
Bug report: JSON to CSV not working for me

If I use the Recipe JSON to CSV it just tells me the message:

> Error translating from ArrayBuffer to JSON: SyntaxError: JSON.parse: unexpected end of data > at line 1 column 1 of the JSON data

If i use the demo JSON files from https://json.org/example.html I also get the message:

> Unable to parse JSON to CSV: TypeError: e.replace is not a function

I was not able to use the recipe at all... Cyberchef 9.04 in Browser (Chrome and Firefox fully patched)

The reverse way CSV to JSON works fine for me!

**Comment by n1474335** [comment]
Hi @Fake4d, the JSON to CSV operation only works on certain types of JSON formatted in specific ways. For example, this recipe works: https://gchq.github.io/CyberChef/#recipe=JSON_to_CSV(',','%5C%5Cr%5C%5Cn')&input=WwogICAgewogICAgICAgICJoZWFkZXIxIjogImNlbGwxIiwKICAgICAgICAiaGVhZGVyMiI6ICJjZWxsMiIKICAgIH0KXQ
