### ISSUE TITLE
x86 disassembly doesn't work

### ISSUE THREAD

**Issue by michaelkruglos** [gchq/CyberChef#611]
Why trying to disassemble the following (presented here as hex), the result is incorrect:

> 31 c0 99 b2 20 48 29 d4 31 ff 48 89 e6 0f 05 91 4d 31 c9 31 db b3 02 4c 8d 3d 95 00 00 00 0f b6 44 0c ff 2c 30 3c 09 76 08 2c 31 3c 05 77 7c 04 0a 41 0f be 14 07 c1 e0 07 8d 44 02 67 4c 8d 6c 00 01 48 89 df 4d 31 d2 49 83 ea 02 31 ed ff c5 49 89 f8 48 89 fe 48 89 ef 31 c0 31 d2 49 d1 e8 73 06 48 31 f8 48 31 f2 48 d1 e7 73 03 4c 31 ef 48 d1 e6 73 03 4c 31 ee 4d 85 c0 75 e0 48 89 d7 49 d1 ea 48 0f 42 e8 75 c7 31 eb 0f b6 db 49 01 d9 48 89 eb e2 88 91 49 bb 2e 08 3d 3c c3 2c bc 61 4c 39 db 75 05 b0 e2 49 39 c1 40 0f 95 c7 b0 3c 0f 05 69 69 2e 2b 32 5e 55 49 35 5c 6f 5e 7e 2a 4d 37

**Comment by j433866** [comment]
Hi @michaelkruglos, could you please provide the result you are getting and the result you're expecting?

**Comment by michaelkruglos** [comment]
Hi @j433866 .
Link to cyberchef so you can see what happens for yourself: https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')Disassemble_x86('64','Full%20x86%20architecture',16,0,true,true)&input=MzEgYzAgOTkgYjIgMjAgNDggMjkgZDQgMzEgZmYgNDggODkgZTYgMGYgMDUgOTEgNGQgMzEgYzkgMzEgZGIgYjMgMDIgNGMgOGQgM2QgOTUgMDAgMDAgMDAgMGYgYjYgNDQgMGMgZmYgMmMgMzAgM2MgMDkgNzYgMDggMmMgMzEgM2MgMDUgNzcgN2MgMDQgMGEgNDEgMGYgYmUgMTQgMDcgYzEgZTAgMDcgOGQgNDQgMDIgNjcgNGMgOGQgNmMgMDAgMDEgNDggODkgZGYgNGQgMzEgZDIgNDkgODMgZWEgMDIgMzEgZWQgZmYgYzUgNDkgODkgZjggNDggODkgZmUgNDggODkgZWYgMzEgYzAgMzEgZDIgNDkgZDEgZTggNzMgMDYgNDggMzEgZjggNDggMzEgZjIgNDggZDEgZTcgNzMgMDMgNGMgMzEgZWYgNDggZDEgZTYgNzMgMDMgNGMgMzEgZWUgNGQgODUgYzAgNzUgZTAgNDggODkgZDcgNDkgZDEgZWEgNDggMGYgNDIgZTggNzUgYzcgMzEgZWIgMGYgYjYgZGIgNDkgMDEgZDkgNDggODkgZWIgZTIgODggOTEgNDkgYmIgMmUgMDggM2QgM2MgYzMgMmMgYmMgNjEgNGMgMzkgZGIgNzUgMDUgYjAgZTIgNDkgMzkgYzEgNDAgMGYgOTUgYzcgYjAgM2MgMGYgMDUgNjkgNjkgMmUgMmIgMzIgNWUgNTUgNDkgMzUgNWMgNmYgNWUgN2UgMmEgNGQgMzc

Expected result:
```asm
0:  31 c0                   xor    eax,eax
2:  99                      cdq
3:  b2 20                   mov    dl,0x20
5:  48 29 d4                sub    rsp,rdx
8:  31 ff                   xor    edi,edi
a:  48 89 e6                mov    rsi,rsp
d:  0f 05                   syscall
f:  91                      xchg   ecx,eax
10: 4d 31 c9                xor    r9,r9
13: 31 db                   xor    ebx,ebx
15: b3 02                   mov    bl,0x2
17: 4c 8d 3d 95 00 00 00    lea    r15,[rip+0x95]        # 0xb3
1e: 0f b6 44 0c ff          movzx  eax,BYTE PTR [rsp+rcx*1-0x1]
23: 2c 30                   sub    al,0x30
25: 3c 09                   cmp    al,0x9
27: 76 08                   jbe    0x31
29: 2c 31                   sub    al,0x31
2b: 3c 05                   cmp    al,0x5
2d: 77 7c                   ja     0xab
2f: 04 0a                   add    al,0xa
31: 41 0f be 14 07          movsx  edx,BYTE PTR [r15+rax*1]
36: c1 e0 07                shl    eax,0x7
39: 8d 44 02 67             lea    eax,[rdx+rax*1+0x67]
3d: 4c 8d 6c 00 01          lea    r13,[rax+rax*1+0x1]
42: 48 89 df                mov    rdi,rbx
45: 4d 31 d2                xor    r10,r10
48: 49 83 ea 02             sub    r10,0x2
4c: 31 ed                   xor    ebp,ebp
4e: ff c5                   inc    ebp
50: 49 89 f8                mov    r8,rdi
53: 48 89 fe                mov    rsi,rdi
56: 48 89 ef                mov    rdi,rbp
59: 31 c0                   xor    eax,eax
5b: 31 d2                   xor    edx,edx
5d: 49 d1 e8                shr    r8,1
60: 73 06                   jae    0x68
62: 48 31 f8                xor    rax,rdi
65: 48 31 f2                xor    rdx,rsi
68: 48 d1 e7                shl    rdi,1
6b: 73 03                   jae    0x70
6d: 4c 31 ef                xor    rdi,r13
70: 48 d1 e6                shl    rsi,1
73: 73 03                   jae    0x78
75: 4c 31 ee                xor    rsi,r13
78: 4d 85 c0                test   r8,r8
7b: 75 e0                   jne    0x5d
7d: 48 89 d7                mov    rdi,rdx
80: 49 d1 ea                shr    r10,1
83: 48 0f 42 e8             cmovb  rbp,rax
87: 75 c7                   jne    0x50
89: 31 eb                   xor    ebx,ebp
8b: 0f b6 db                movzx  ebx,bl
8e: 49 01 d9                add    r9,rbx
91: 48 89 eb                mov    rbx,rbp
94: e2 88                   loop   0x1e
96: 91                      xchg   ecx,eax
97: 49 bb 2e 08 3d 3c c3    movabs r11,0x61bc2cc33c3d082e
9e: 2c bc 61
a1: 4c 39 db                cmp    rbx,r11
a4: 75 05                   jne    0xab
a6: b0 e2                   mov    al,0xe2
a8: 49 39 c1                cmp    r9,rax
ab: 40 0f 95 c7             setne  dil
af: b0 3c                   mov    al,0x3c
b1: 0f 05                   syscall
b3: 69 69 2e 2b 32 5e 55    imul   ebp,DWORD PTR [rcx+0x2e],0x555e322b
ba: 49 35 5c 6f 5e 7e       rex.WB xor rax,0x7e5e6f5c
c0: 2a 4d 37                sub    cl,BYTE PTR [rbp+0x37]
```

**Comment by j433866** [comment]
The Disassemble x86 operation takes its input as a hexadecimal string, so you do not need to un-hex your input before disassembly. [This should produce the result you are expecting.](https://gchq.github.io/CyberChef/#recipe=Disassemble_x86('64','Full%20x86%20architecture',16,0,true,true)&input=MzEgYzAgOTkgYjIgMjAgNDggMjkgZDQgMzEgZmYgNDggODkgZTYgMGYgMDUgOTEgNGQgMzEgYzkgMzEgZGIgYjMgMDIgNGMgOGQgM2QgOTUgMDAgMDAgMDAgMGYgYjYgNDQgMGMgZmYgMmMgMzAgM2MgMDkgNzYgMDggMmMgMzEgM2MgMDUgNzcgN2MgMDQgMGEgNDEgMGYgYmUgMTQgMDcgYzEgZTAgMDcgOGQgNDQgMDIgNjcgNGMgOGQgNmMgMDAgMDEgNDggODkgZGYgNGQgMzEgZDIgNDkgODMgZWEgMDIgMzEgZWQgZmYgYzUgNDkgODkgZjggNDggODkgZmUgNDggODkgZWYgMzEgYzAgMzEgZDIgNDkgZDEgZTggNzMgMDYgNDggMzEgZjggNDggMzEgZjIgNDggZDEgZTcgNzMgMDMgNGMgMzEgZWYgNDggZDEgZTYgNzMgMDMgNGMgMzEgZWUgNGQgODUgYzAgNzUgZTAgNDggODkgZDcgNDkgZDEgZWEgNDggMGYgNDIgZTggNzUgYzcgMzEgZWIgMGYgYjYgZGIgNDkgMDEgZDkgNDggODkgZWIgZTIgODggOTEgNDkgYmIgMmUgMDggM2QgM2MgYzMgMmMgYmMgNjEgNGMgMzkgZGIgNzUgMDUgYjAgZTIgNDkgMzkgYzEgNDAgMGYgOTUgYzcgYjAgM2MgMGYgMDUgNjkgNjkgMmUgMmIgMzIgNWUgNTUgNDkgMzUgNWMgNmYgNWUgN2UgMmEgNGQgMzc)
