### ISSUE TITLE
Bug report: AES CTR Bug in encryption and decryption

### ISSUE THREAD

**Issue by sasatefa2009** [gchq/CyberChef#613]
Encrypt  any 3 lines text in CTR and try to decrypt it, for example:
```
greatings
greatings
greatings
greatings
```

the decryption will look like this
```
greatings
greatià...p
..W.k&wz8÷È$.&ù4½
```

also a long text like this will do the same thing
```
greatingsgreatingsgreatingsgreatings
```

**Comment by n1474335** [comment]
Hi @sasatefa2009, thanks for raising this. It was due to the way that the AES Decrypt operation handles blank IVs. I've fixed it in the latest patch and added some tests to make sure it doesn't break again.
