### ISSUE TITLE
AES256 in GCM mode encrypt/decrypt problem - Unable to decrypt input with these parameters

### ISSUE THREAD

**Issue by zember** [gchq/CyberChef#617]
I have problem with AES256 encrypt / decrypt operation.  I encrypt some data and cannot decrypt it. I tried Ctrl+Shift+R on Chrome with no result.
Here is an example:

AES Encrypt
Key-Hex: 7caad7a98976d2307031056971d801ae419e7a4d6aa50e14ca548c14baab2885
IV-Hex: 455ad871a0b49569f053c0c70391afef
Mode: GCM
Input: RAW
Output: HEX

Input data to encrypt: 1122334455

result in output :
a01fb3ad5012f8402bd9

Tag: dd38345975820c29b2bd0f76215e5ee5

AES Decrypt:
Key-Hex: 7caad7a98976d2307031056971d801ae419e7a4d6aa50e14ca548c14baab2885
IV-Hex: 455ad871a0b49569f053c0c70391afef
Mode: GCM
Input: HEX
Output: RAW
GCM Tag : dd38345975820c29b2bd0f76215e5ee5

Input data to decrypt: a01fb3ad5012f8402bd9

result in output :
Unable to decrypt input with these parameters.

**Comment by j433866** [comment]
Thanks for reporting this, it has now been fixed in v9.0.9.
The issue was the same as #469, but for decryption. The IV was being converted to a byteArray, which is not supported for GCM mode, so instead it is now converted to a byte string which is supported by all AES modes.
