### ISSUE TITLE
Bug report: "Extract Domains" actually extracts hostnames

### ISSUE THREAD

**Issue by gwittel** [gchq/CyberChef#618]
**Describe the bug**

Extract domains is more like extract hostnames.  Please rename it or implement the claimed functionality (or implement both as separate items).

**To Reproduce**
Steps to reproduce the behavior or a link to the recipe / input used to cause the bug:

1. Add 'Extract Domains' to a recipe
2. Add input like `http://www.host.com` or `http://www.host.co.uk`  (or leave out the schemes)
3. Output has `www.host.com` or `www.host.co.uk`.  Those would be the hostnames whereas `host.com` and `host.co.uk` are the domains.

**Expected behavior**

The domain for `www.host.com` is `host.com`.

**Screenshots**

n/a

**Desktop (if relevant, please complete the following information):**

- Mac
- Firefox
- 68

**Additional context**

**Comment by n1474335** [comment]
In this case, 'Domains' is being used to refer to 'Domain names'. Domain names are any name assigned via DNS to represent an IP address. In your example above, `com` is the Top Level Domain (TLD), `host` is the second level domain (a subdomain of `com`), and `www` is the third level domain (a subdomain of `host`). The whole thing together, `www.host.com` is technically a Fully Qualified Domain Name (FQDN).

A hostname is a label that identifies a networked device. FQDNs are a type of hostname, but a hostname doesn't necessarily have to use the DNS structure. On a local network you might just assign single word hostnames to identify your devices as globally unique, fully qualified DNS is not really required at that scale.

So the 'Extract Domains' operation isn't really looking for hostnames, it's looking for fully qualified domain names, or as much of the domain name as it can find. There is a potential argument for renaming it to 'Extract Domain names', however I think it's reasonably clear from the context that 'Domains' means 'Domain names' in this scenario.

Does that make sense?

**Comment by n1474335** [comment]
I'll close it for now. Programmatically extracting only the publicly registrable domain would be quite difficult.

Consider the domain `m.en.host.co.uk`. Determining which subdomain is the correct cut off is not trivial and I'm not sure I'm aware of many use cases that would make it worthwhile.
