### ISSUE TITLE
Misc: Android Backward Text Input

### ISSUE THREAD

**Issue by operator-DD3** [gchq/CyberChef#622]
I use 'hackers keyboard' on android 9. Everything I type in any text input box ends up: "SIHT EKIl", when I mean " Like this"

Its as if caps lock is backwards and the flow of text is backwards also.

**Comment by n1474335** [comment]
That's very odd. I'd be interested to understand this, however we don't currently support any mobile devices so I'll close this issue for now. If anyone does work out what's happening here please reopen this issue.
