### ISSUE TITLE
miss the opportunity character to char

### ISSUE THREAD

**Issue by pipiscrew** [gchq/CyberChef#623]
something like 
hxxps://www.browserling.com/tools/text-to-ascii

**Comment by n1474335** [comment]
I'm not quite sure exactly what you're asking for here, but CyberChef can already convert text to its ASCII charcode values, like this: https://gchq.github.io/CyberChef/#recipe=To_Charcode('Space',10)&input=SGVsbG8sIFdvcmxkIQ

I'll close this issue now but if this isn't what you're looking for, please reopen it with more information. Thanks!
