### ISSUE TITLE
Bug report: No scrolling bar for operations menu

### ISSUE THREAD

**Issue by maria8899** [gchq/CyberChef#626]
There is no scrolling bar appearing in the operation menu, meaning you cannot access all functions.

**To Reproduce**
Steps to reproduce the behavior or a link to the recipe / input used to cause the bug:

1. Open CyberChef
2. Try to scroll operation menu

**Expected behavior**
Being able to scroll operations menu

**Screenshots**
https://imgur.com/1ytF4HT

**Desktop (if relevant, please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 68.0.2

**Comment by imathrowback** [comment]
Quick hack to make it work in chrome:

`overflow-y: scroll; `

on the **operations** div.

**Comment by mifriis** [comment]
Issue is also present on Chrome (76.0.3809.132)

**Comment by n1474335** [comment]
Apologies, this was my fault. We're fixing it right now.
https://github.com/gchq/CyberChef/blob/2f0b959aa4e8ed3d2c07062106e7f192347305de/src/web/stylesheets/layout/_structure.css#L42-L44

Clearly I didn't test this very well at all. I'll be adding a load of new UI tests today to make sure it doesn't happen again.

**Comment by maria8899** [comment]
Thanks, I can confirm it works now.
