### ISSUE TITLE
AESEncrypt->AESDecrypt not functioning properly

### ISSUE THREAD

**Issue by DannyBoyk** [gchq/CyberChef#63]
All the other encrypt/decrypt pairs appear to work except for the AESEncrypt->AESDecrypt.  If you AESEncrypt a string with any key, AESDecrypt does not output that same string with the same key.  In fact, it doesn't seem to output anything.

**Comment by n1474335** [comment]
Hi @DannyBoyk,

Have you checked that the "Output result" argument for the AES Encrypt operation is set to "Ciphertext"? The default is "Show all", but the decrypt operation won't understand the format unless it's just the ciphertext.

[Example](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22AES%20Encrypt%22%2C%22args%22%3A%5B%7B%22option%22%3A%22UTF8%22%2C%22string%22%3A%22hello%22%7D%2C%7B%22option%22%3A%22Hex%22%2C%22string%22%3A%22%22%7D%2C%7B%22option%22%3A%22Hex%22%2C%22string%22%3A%22%22%7D%2C%22CBC%22%2C%22Pkcs7%22%2C%22Ciphertext%22%2C%22Hex%22%5D%7D%2C%7B%22op%22%3A%22AES%20Decrypt%22%2C%22args%22%3A%5B%7B%22option%22%3A%22UTF8%22%2C%22string%22%3A%22hello%22%7D%2C%7B%22option%22%3A%22Hex%22%2C%22string%22%3A%22%22%7D%2C%7B%22option%22%3A%22Hex%22%2C%22string%22%3A%22%22%7D%2C%22CBC%22%2C%22Pkcs7%22%2C%22Hex%22%2C%22UTF8%22%5D%7D%5D&input=VGVzdA)

**Comment by DannyBoyk** [comment]
Thank you for that.  I was able to duplicate what you did only specifying a key.  I should amend my first statement to indicate I was also specifying an IV in hex.  My IV was 16 bytes in length.  Even using the same IV in the decrypt block, the message fails to decrypt.  Is it expecting an IV of a specific length?

**Comment by n1474335** [comment]
Thanks for reporting this, I'm getting the same problem when an IV is specified. I'll look into it shortly.

**Comment by Wingless-Archangel** [comment]
from what I random test with the DES encryption also has the same issue even though I put the same key,( or IV and salt) I got blank output for some reasons. I guess, there will be something wrong in the decryption.

**Comment by bwhitn** [comment]
I have been playing around with this. Looks like some issues with what it accepts. AES should only accept 16, 24 or 32 byte keys. DES should only allow 8 byte keys. These functions also require a IV for modes that don't use IVs. I also noticed that the "NoPadding" option doesn't always work.
