### ISSUE TITLE
grunt dev fails

### ISSUE THREAD

**Issue by Nerodoe** [gchq/CyberChef#635]
## Summary
Hi,
When i run grunt dev i get the following error, this is installed on a CentOs box.

    ERROR in ./src/web/stylesheets/vendors/bootstrap.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader                                                       .js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/                                                       cjs.js):
    Error: ENOENT: no such file or directory, scandir '/home/CyberChef/n                                                       ode_modules/node-sass/vendor'
      at Object.readdirSync (fs.js:790:3)
I Have tried to run the following :  npm install --build-from-resource 
But that did not help, can you please advise?

**Comment by n1474335** [comment]
This is usually a problem with `node-sass` which needs to be built in a specific way depending on which OS you are using. Try running `npm rebuild node-sass` and see if that makes any difference.

**Comment by Nerodoe** [comment]
Thanks that worked for me, I still have these warnings, should I be alarmed by them or not?
npm WARN sass-loader@8.0.0 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by n1474335** [comment]
No, that's fine. It should build correctly now.
