### ISSUE TITLE
JSON to CSV TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by kulbozz** [gchq/CyberChef#637]
Happens often, but not all the time. Get the following error when using "JSON to CSV"

'Unable to parse JSON to CSV: TypeError: e.replace is not a function`

**Comment by JacobRReed** [comment]
I'd like to work on this

**Comment by impshum** [comment]
> I'd like to work on this, I'll check it out

Looks like **a lot** of string replacement error handling.

https://github.com/gchq/CyberChef/search?p=2&q=e.replace&unscoped_q=e.replace

**Comment by mcfarlander** [comment]
We were able to determine several cases where this fails.

**Comment by atom-box** [comment]
For JSON to Object I checked out cases where the number of properties was inconsistent from object to object.

Fails for the following pattern:
[ {A: 55, B: 55, C: 55}, {A: 55, B: 55       } ]  extra properties in first object

Works fine for the following patterns:
[ {A: 55, B: 55       }, {A: 55, B: 55, C: 55} ]  missing properties in first object
[ {A: 55, B: 55, C: 55}, {A: 55, B: 55, C: 55,  D:  55} ]   extra properties in second object or any later object

**Comment by datorr2** [comment]
Same error in Version: 9.20.3.

> Unable to parse JSON to CSV: TypeError: e.replace is not a function

I tried with and without JSON Beautify (which works fine by the way), and neither will convert to CSV.

**Comment by naisanzaa** [comment]
Still happens

**Comment by cardoppler** [comment]
Still happens :-(

**Comment by rtrind** [comment]
Same here. My JSON is beautified on SublimeText but fails with this same error on CyberChef.

**Comment by edtatch** [comment]
Hello Team,
Still have this issue, someone have founnd a workaround, please ?
Thank you for help and great work.

**Comment by n1474335** [comment]
I have hopefully fixed this in v9.27.3. If you are still getting errors, feel free to reopen this issue, but please include some example input that causes the error, otherwise it is difficult to know where exactly the problem lies.

**Comment by ianso-msf** [comment]
I think this happens if you have boolean literals in the json? (using vVersion 9.24.7)
