### ISSUE TITLE
Feature request: Hex to ascii

### ISSUE THREAD

**Issue by PowerPress** [gchq/CyberChef#638]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have hex data that is encoded in ascii format and need to manually look up the ascii table.

**Describe the solution you'd like**
I would like a option to decode from hex to ascii to convert for example 41 to a

**Describe alternatives you've considered**
The only alternative is manually using an ascii lookup table

**Additional context**
None

**Comment by mattnotmitt** [comment]
[This](https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')Encode_text('US-ASCII%20(20127)')&input=NDE) should do what you're wanting.

**Comment by PowerPress** [comment]
Perfect
