### ISSUE TITLE
Bug Report: PHP Deserialize - NULL values are incorrectly converted to JSON

### ISSUE THREAD

**Issue by nanawel** [gchq/CyberChef#641]
The NULL value in a PHP-serialized input string is not correctly converted which then break any JSON operation that comes next.

```
a:1:{i:0;N;}
```
gets converted to
```
{"0": }
```
which is not a valid JSON string.

Check out the demo here: https://gchq.github.io/CyberChef/#recipe=PHP_Deserialize(true)JSON_Beautify('%20%20%20%20',false)&input=YToxOntpOjA7Tjt9

**Comment by Storms-Engineering** [comment]
Can I get assigned to this?
