### ISSUE TITLE
MISC

### ISSUE THREAD

**Issue by melissadh** [gchq/CyberChef#644]
SyntaxError: Invalid regular expression: range out of order in character class
Filename: blob:https://cyberchef.immersivelabs.online/6c5f3eb0-21bb-4b9d-ba18-e76cf9107f73
Line: 2162
Column: 1243361
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
CyberChef version: 8.27.0s

**Comment by n1474335** [comment]
It looks like you're running an old version of CyberChef. Try upgrading to the latest release and see if the error persists.
