### ISSUE TITLE
Misc: Data Units Convert to Kilobits (Kb) always return NaN

### ISSUE THREAD

**Issue by burningrooftop** [gchq/CyberChef#649]
Data Units Convert to Kilobits (Kb) always returns NaN.

Problem seems to be in ConvertDataUnits.mjs where DATA_UNITS has "Kilobits (kb)" (note the lowercase "k" in "kb"), whereas elsewhere it is referred to as "Kilobits (Kb)" with an uppercase "K".

* Version: 9.7.1
* Compile time: 26/09/2019 22:12:52 UTC
* User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=Convert_data_units('Megabits%20(Mb)','Kilobits%20(kb)')&input=MTAw)

**Comment by n1474335** [comment]
Good catch! I've just pushed a fix.
