### ISSUE TITLE
Bug Report: CyberChef Encountered an Error While Loading

### ISSUE THREAD

**Issue by TauSigma5** [gchq/CyberChef#662]
When spun up using npm start, CyberChef displays an error message when accessed from Firefox with the message “CyberChef Encountered an Error While Loading”.

System Info: Ubuntu 18.10 (I know don't judge me), NPM 5.8.0, Node.js 8.11.4

Steps to Reproduce:
1. Install according to instructions on Wiki.
2. Go into the folder and type npm start.
3. Open Firefox 68.0 and type localhost:8080.

Expected Behavior:
It launches CyberChef web interface.

Errors: 
`Error: Cannot find module './config/modules/OpModules.mjs'
Filename: blob:http://localhost:8080/e9ab6e97-6c90-44bd-812d-52516ee96e10 line 282 > eval
Line: 9
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.
CyberChef version: 9.7.7`
![image](https://user-images.githubusercontent.com/46148925/66274899-dccf4e00-e872-11e9-8be8-749e8876429b.png)

![image](https://user-images.githubusercontent.com/46148925/66274913-f7a1c280-e872-11e9-86f9-1e9c3c6c78da.png)

**Comment by jerrydark** [comment]
Can confirm same error happening due to failed config generation. Working on workaround

**Comment by jerrydark** [comment]
I just realized that I'm using v12.9.1 and the pull request will solve only in this version. 
Try upgrading to v10.16.3 since that's the version Travis is running on.

**Comment by n1474335** [comment]
Yes, you must be using the current Node LTS to build CyberChef. There are some dependencies that don't support Node 12 yet. We'll update them as soon as they are fixed.
