### ISSUE TITLE
Feature request: Use deploy service such as Netlify

### ISSUE THREAD

**Issue by MarvinJWendt** [gchq/CyberChef#673]
Hi, I was wondering if we could implement a deployment service such as [Netlify](https://www.netlify.com/).

## What are the benefits?

Netlify will automatically deploy a selected branch to the world wide web.
But that's not the best thing about it.
Netlify also deploys pull requests to a live viewable version. This would make every pull request testable as it will be online. Every added operation could be tried out before it goes live. 
This is also very useful for themes and layout changes.

What are your opinions about that?

**Comment by n1474335** [comment]
Hi @MarvinJWendt, thanks for the suggestion. We already use Travis CI to run automated tests and deploy an up-to-date version of CyberChef to GitHub Pages.
