### ISSUE TITLE
Feature Request: remove line breaks or carriage returns

### ISSUE THREAD

**Issue by duckexmachina** [gchq/CyberChef#69]
for Utils:
find and remove line breaks and carriage returns from text

**Comment by n1474335** [comment]
Hi @duckexmachina,

This is already covered by the 'Remove whitespace' operation. [See this example](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22From%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%2C%7B%22op%22%3A%22Remove%20whitespace%22%2C%22args%22%3A%5Btrue%2Ctrue%2Ctrue%2Ctrue%2Ctrue%2Cfalse%5D%7D%2C%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=MGQgMGE).

Thanks for the suggestion though, it's a good one.
