### ISSUE TITLE
Bug report: Memory consuming when calculate file hash

### ISSUE THREAD

**Issue by kotori2** [gchq/CyberChef#698]
**Describe the bug**
If you try to calculate hash of a 50 MB file, it is most likely it will consume 2.5G of RAM. And if you got a ~70MB file, the page will crash due to high memory consumed.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

0. Use Chrome
1. Select hash (MD5/SHA1/etc) on recipe
2. Drag a file larger then 70MB into input window

**Expected behaviour**
Not much memory consuming, at least not crashing the page

**Screenshots**
![image](https://user-images.githubusercontent.com/17663689/67432004-0250ab80-f618-11e9-806f-f9d2a55538cc.png)

**Desktop (if relevant, please complete the following information):**
 - OS: Windows
 - Browser: Chrome 77
 - CyberChef version: 9.7.17

**Additional context**
-

**Comment by n1474335** [comment]
We use the [crypto-api](https://github.com/nf404/crypto-api/) library for most of our hashing operations, including MD5. It's probably worth raising this issue on their repository.
