### ISSUE TITLE
CSS Selection is not working

### ISSUE THREAD

**Issue by danisson** [gchq/CyberChef#70]
I tested all kind of HTML inputs with the CSS Selection action and none of them worked.
I tried well-formed inputs such as:
```
<!doctype html>
<html>
<head>
<meta charset=utf-8>
<title>test page</title>
</head>
<body>
<p>test content</p>
</body>
</html>
```
or non well-formed such as `test<p>???</p> content` and selecting `p` always returned empty strings.

I'm using Chrome Version 57.0.2987.21 beta and CyberChef with compile time: 31/01/2017 18:23:14 UTC

**Comment by Mikescher** [comment]
Hmm, it works when you select `p` with the input
~~~
<div>
<p>test content</p>
</div>
~~~

I think you can't directly select the root element (?)

**Comment by n1474335** [comment]
Hi @danisson, thanks for raising this. @Mikescher is correct - the method of selection was the `jQuery.find()` function which only works for child elements, not root elements.

I've modified the operation to use vanilla JS to parse and query the input so it should [work correctly now](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22CSS%20selector%22%2C%22args%22%3A%5B%22p%22%2C%22%5C%5Cn%22%5D%7D%5D&input=PCFkb2N0eXBlIGh0bWw%2BCjxodG1sPgo8aGVhZD4KPG1ldGEgY2hhcnNldD11dGYtOD4KPHRpdGxlPnRlc3QgcGFnZTwvdGl0bGU%2BCjwvaGVhZD4KPGJvZHk%2BCjxwPnRlc3QgY29udGVudDwvcD4KPC9ib2R5Pgo8L2h0bWw%2B).
