### ISSUE TITLE
Operation request: Add more alphabets to Base64 Operation

### ISSUE THREAD

**Issue by rmartinsanta** [gchq/CyberChef#700]
## Summary
Some challenges and CTFs use special alfabets in base64 when encoding flags or important information. It would be nice if Cyberchef could detect and use (specially the magic tool) some some of the weird but common ones (such as Atom128). See https://gist.github.com/tunelko/49b7e64c1688d62d0ecd.

Thanks in advance.

**Comment by rmartinsanta** [comment]
Example of ATOM-128 encoding/decoding tool: http://k4.cba.pl/dw/crypo/tools/eng_atom128c.html

**Comment by n1474335** [comment]
Closed in #943
