### ISSUE TITLE
Feature request: Export or display recipes as code

### ISSUE THREAD

**Issue by kulbozz** [gchq/CyberChef#701]
About about a feature to convert cyberchef recipes to shell, python, php, C, or javascript? This would especially be useful in writing scripts for automation. Either an export button to code or a toggle switch to view the recipe as code and then the ability to copy the code out. The code should expect standard input.

**Comment by mattnotmitt** [comment]
This has been suggested before in #482 - it would be a nice feature to have but it would require so much work it's probably infeasible. [gchq/CyberChef-server](https://github.com/gchq/CyberChef-server) may be useful to you when it's feature complete, and you could use the [Node API](https://github.com/gchq/CyberChef/wiki/Node-API) if you want to use JS.
