### ISSUE TITLE
Feature request: Auto-select Search on load

### ISSUE THREAD

**Issue by Reelix** [gchq/CyberChef#703]
**Is your feature request related to a problem? Please describe.**
When the page loads and you know what you want, you need to click on the "Search" box before you type.

**Describe the solution you'd like**
I suggest an extremely small usability change - That the search box is selected by default so that you may immediately start typing from a bookmark.

**Describe alternatives you've considered**
Making it one of the first boxes that get selected when "Tab" is pressed after page load

**Comment by n1474335** [comment]
This has been implemented in #705. The input is auto-focused initially, but the search bar is the next element in the tabfocus list. After that, operation arguments come next.

Remember you can also use keyboard shortcuts to jump to specific places. They can be found in the 'About/Support' pane.
