### ISSUE TITLE
Bug report: OCR operation errors on safari

### ISSUE THREAD

**Issue by d98762625** [gchq/CyberChef#771]
**Describe the bug**
Running OCR on some image on safari browser results in the following message in the output: `Error performing OCR on image. (ReferenceError: Can't find variable: Worker)`

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Open web UI for chef, load OCR operation.
2. place some image with words in the input
3. See error

**Expected behaviour**
The text in the image to be in the output

**Screenshots**

**Desktop (if relevant, please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Safari 13.0.2
 - CyberChef version: 9.7.19

**Additional context**
No problems on chrome / firefox

**Comment by n1474335** [comment]
Safari isn't one of our supported browsers so I'll close this. If someone particularly wants to fix it, go ahead.
