### ISSUE TITLE
Bug report: Gzip comment not working

### ISSUE THREAD

**Issue by zehuanli** [gchq/CyberChef#870]
**Describe the bug**
*Very minor bug, but it would be great if this could be fixed:*

The Gzip encoder has an optional `Comment` field that allows users to supply comment. (Documented in [rfc1952](https://tools.ietf.org/html/rfc1952#page-6), see `FCOMMENT`). It is implemented in [Gzip.mjs](https://github.com/gchq/CyberChef/blob/7244d4d343e5fafe3409fe535efee7658418c384/src/core/operations/Gzip.mjs#L76) but there's a typo - "options.flags.fcommenct" should actually be "options.flags.fcomment", as I assume from the context.

**To Reproduce**

1. Open CyberChef
1. Select `Gzip` operation and deflate some text, save the output (better as hex).
1. Put something in the `Comment` field, compare the new output with the one in previous step.
1. Observe that the comment was not put into the deflated data. (Although the new output **will be different** because different timestamps are used).

**Expected behaviour**
The text in the `Comment` field should present in the deflated data.

**Desktop (if relevant, please complete the following information):**
 - CyberChef version: [9.9.0]

**Comment by n1474335** [comment]
Fixed in #926
