### ISSUE TITLE
Bug report: Import Fails Behind an Nginx Server

### ISSUE THREAD

**Issue by 3lpsy** [gchq/CyberChef#871]
**Describe the bug**
When trying to use CyberChef behind an nginx proxy, I receive an error with certain recipes due to an inability to pull assets. For example, when using Generica Code Beautifier, I receive:

Loading script from “http://xxxx/modules/Code.js” with importScripts() was blocked because of a disallowed MIME type (“text/html”).

When inspecting the network traffic, the server returned a 404 for http://xxxx/modules/Code.js

When looking at the build/prod root directory being served, no "modules" directory exists. Was it supposed to be created with npm run prod?

**To Reproduce**
Build the project: npm run prod 
Setup nginx to server build/prod as the root
Attempt to sue the Generic Code Beautifier

**Expected behaviour**
It works

**Desktop (if relevant, please complete the following information):**
 Commit: 734962ac22c020d02deefdb5cb2466f6991b4f52

I couldn't find any documentation behind setting up nginx so I'm unaware if there are any special rules required. It's a really simple nginx config with the built folder as the root.

Nginx Config: 
```
server {
	listen 80 default_server;
	root /opt/CyberChef/build/prod;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files $uri $uri/ =404;
	}
}
```

Contents of build/prod: 
```
assets
BundleAnalyzerReport.html
CyberChef_v9.8.0.zip
images
index.html
```

**Comment by n1474335** [comment]
Running `npm run build` should populate the `build/prod` directory including the `modules` subdirectory. Could this be a permissions problem? Can you confirm if the `build/prod/modules` folder is present on the filesystem, not just accessible via nginx?

**Comment by 3lpsy** [comment]
Not sure what happened. The modules directory wasn't there. Then, when I tried to rebuild, I kept getting DCed from the server because of memory. I added the mem restriction env variable and rebuilt so maybe it was that. Anyways, it works now. Thanks!
