### ISSUE TITLE
Bug report: Bootstrap-material-design need https://popper.js.org/

### ISSUE THREAD

**Issue by pierremahot** [gchq/CyberChef#901]
**Describe the bug**
Error with offline use : missing https://popper.js.org

**To Reproduce**
Here is a docker image that recreate the bug and mimic our build.
https://hub.docker.com/r/wakalou/cyberchef
the Dockerfile is in the readme

Error while loading cyberchef when offline on boostrap-material-design.js.
```
CyberChef encountered an error while loading.
The following browser versions are supported:

    Google Chrome 50+
    Mozilla Firefox 38+

Your user agent is:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

If your browser is supported, please raise an issue including the following details:

TypeError: Bootstrap's tooltips require Popper.js (https://popper.js.org/)
Filename: http://172.17.0.2:8080/main.js line 4079 > eval
Line: 2386
Column: 15
Error: TypeError: Bootstrap's tooltips require Popper.js (https://popper.js.org/)
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
CyberChef version: 9.11.5
```

**Expected behaviour**
no error

**Desktop (if relevant, please complete the following information):**
 - OS: Linux
 - Browser: Firefox/70.0
 - CyberChef version: 9.11.5

**Additional context**
I build the project offline with no error with a git mirror and a nodejs mirror.
Version working before cyberchef v8.33.1
The weebpack module rules is working only for dropdown menu bot not tooltips

**Comment by n1474335** [comment]
Is anyone else seeing this?

**Comment by pierremahot** [comment]
Hello I still get the same error.
When running in grunt dev firefox tell me this in the console too
```
TypeError: document.getElementById(...) is null localhost:121:26
Error in source links : Error: NetworkError when attempting to fetch resource. URL of the resource : webpack:///./node_modules/popper.js/dist/umd/popper.js? URL link source : popper.js.map 
Error in source links : Error: NetworkError when attempting to fetch resource. URL of the resource : webpack:///./node_modules/file-saver/dist/FileSaver.min.js? URL link source : FileSaver.min.js.map
```
webpack : 4.41.2
npm : 6.11.3
nodejs: v10.17.0
Cyberchef : 9.11.13
grunt-cli: v1.3.2
grunt: v1.0.4

**Comment by n1474335** [comment]
Unfortunately I can't seem to replicate this. If anyone can reproduce it, please let me know.

**Comment by pierremahot** [comment]
Here is a docker image that recreate the bug and mimic our build at work.
https://hub.docker.com/r/wakalou/cyberchef
the Dockerfile is in the readme
We rebuild node sass offline (with just npm and apt mirror) but before  v8.33.1 we have no problem with it.

**Comment by d98762625** [comment]
@pierremahot running your image locally, I cannot get the same behaviour:

- on firefox 76 I get no errors
- on chrome 83 I get the following warning: `DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

but the UI works OK and it doesn't seem to degrade the experience.

The Dockerfile you use just pulls the latest Chef version, which for me is `9.20.6`. Could you try again with this later version (bootstrap version has been bumped) and see if you get any issues then?

**Comment by pierremahot** [comment]
Very very sorry all my falt we were modifying the default favoris in /src/web/index.js and I don't update It since verry long time so it miss imports very sorry for no seeing my fault before ... sorry for taking tour time.
