### ISSUE TITLE
Feature request: Make it easy to embed and auto fill in input

### ISSUE THREAD

**Issue by awick** [gchq/CyberChef#903]
First off CyberChef is awesome!  

**Is your feature request related to a problem? Please describe.**
We've had a simple action from Moloch (https://molo.ch) for a while that will auto launch CyberChef and fill in the input box with data from Moloch.  It was always kind of a hack, didn't work great with certain browsers, and works even worse lately.

Currently we generate a page, try setting 'input-text' after a timeout, and cross our fingers.
(https://github.com/aol/moloch/blob/master/viewer/views/cyberchef.pug)

Sometimes the timeout isn't long enough and the user has to hit the Bake button again.  Some browsers just don't work

**Describe the solution you'd like**
Really we are looking for suggestions on how to do it right.

Maybe add a url param that uses the browser fetch api to get the input box, or make it easy for us to inject a function that we could then write in the page to fetch the data?

Sorry if we are missing some obvious way to already do this. :)

**Comment by n1474335** [comment]
You can populate the input field using the `input` URL param. The value should be encoded in Base64. e.g. https://gchq.github.io/CyberChef/#input=SGVsbG8sIFdvcmxkIQ

**Comment by awick** [comment]
Oh sorry, I left out that we want to populate more then what can be in a url parameter usually.  50k or more.

**Comment by n1474335** [comment]
Ah fair enough, that makes sense.

There is a globally defined variable called `app` that gives you access to the main CyberChef web app and lets you control almost everything.

You can call
```javascript
app.setInput("some string")
```
to cleanly add a new input string.

If you want to upload a file it's a little less obvious but still fairly simple:
```javascript
const myFile = new File([1,2,3,4,5], "my_file.dat")
app.manager.input.loadUIFiles([myFile])
```

You can load multiple files by passing them into the array argument. They will get passed off to a separate thread to be loaded as efficiently as possible.

You should be able to call these functions fairly quickly after loading CyberChef. If you want to be certain they will work, you can listen for the custom `apploaded` event which fires once everything is set up and ready to rock and roll.

```javascript
window.addEventListener("apploaded", () => {
    const myFile = new File([1, 2, 3, 4, 5], "my_file.dat");
    app.manager.input.loadUIFiles([myFile]);
});
```

Does that answer the question?
