### ISSUE TITLE
Bug report: Render Markdown not rendering when there is a disabled Module before

### ISSUE THREAD

**Issue by byteloop** [gchq/CyberChef#905]
**Describe the bug**
The Render Markdown Module does not render the input when there is a disabled module (for example JSON Beautify) before.

**To Reproduce**
Input: "# Hey" which is the markdown syntax for a header
Modules: JSON Beautify (disabled), Render Markdown (enabled)

**Expected behaviour**
Output is the rendered Version of "# Hey". The correct output can be seen when the disabled Module is deleted.

**Additional context**
Another thing i found was that a MD5 module before the Render Markdown was not used when a disabled JSON Beautify comes first.
If the MD5 Module is disabled it is displayed in green, the disable button is displayed in red.

Setup for this:
DIsabled JSON Beautify Module
Disabled MD5 Module
Render Markdown Module
and Input "# Hey"

**Comment by d98762625** [comment]
@byteloop I am unable to reproduce this issue - can you try again on the latest version of CyberChef and, if the issue still persists, give more information on your environment? Thanks.
