### ISSUE TITLE
Feature request: Download/curl from URL into input field

### ISSUE THREAD

**Issue by tjhowse** [gchq/CyberChef#918]
When using the CSS selector to parse data from HTML it would be nice if I didn't have to paste in the HTML under analysis into the input field each time.

I would like an operation that downloads a target file, E.G. `https://website.com/index.html` into the input field, ready for analysis. A more general-purpose solution would be an operation implementing (an approximation of) the unix command-line tool `curl`. This would allow queries to REST/SOAP APIs and analysis of the response.

**Comment by n1474335** [comment]
Does this do what you want? https://gchq.github.io/CyberChef/#recipe=HTTP_request('GET','','','Cross-Origin%20Resource%20Sharing',false)
