### ISSUE TITLE
Feature request: Python client/method for automatic processing

### ISSUE THREAD

**Issue by weslambert** [gchq/CyberChef#922]
**Is your feature request related to a problem? Please describe.**
I am looking for a straightforward way to automate the request for Cyberchef to process and transform data, then perform further processing of that data.

**Describe the solution you'd like**
A Python client or method to create a request to Cyberchef and get back the transformed data.

**Describe alternatives you've considered**
I've considered the Node API, but am not that familiar with Node to know how to tie in with something like Python to initiate a request and get back a response.

**Comment by weslambert** [comment]
@n1474335 , is there anyway I can help with this, or achieve an alternative solution?

**Comment by phil-ncsc** [comment]
@weslambert Would https://github.com/gchq/CyberChef-server help?

**Comment by weslambert** [comment]
Hi @phil-ncsc , 

That is exactly what I am looking for.  I'm not sure how I missed it.  Thanks so much!
