### ISSUE TITLE
cyberchef is hanging forever on "bake" a request after the recent build

### ISSUE THREAD

**Issue by ariel777** [gchq/CyberChef#924]
**Describe the bug**
cyberchef is hanging forever on "bake" a request after the 3-days-ago build
Suspicious build: Version 9.11.13 Last build: 3 days ago as it worked correctly before.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Go to https://cyberchef.amazon-corp.com/#recipe=JPath_expression('$.awslogs.data','%5C%5Cn')From_Base64('A-Za-z0-9%2B/%3D',true/disabled)Gunzip(/disabled)JPath_expression('$',''/disabled)Unescape_string(/disabled)&input=eyJhd3Nsb2dzIjp7ImRhdGEiOiJBQUEifX0
2. processing takes forever

**Expected behaviour**
Fast processing.

**Screenshots**
Clear from the description.

**Desktop (if relevant, please complete the following information):**
 - OS: MacOS
 - Browser: chrome Version 78.0.3904.108 (Official Build) (64-bit), firefox, etc.
 - CyberChef version: 9.11.13

**Additional context**

**Comment by n1474335** [comment]
Hi @ariel777,

Unfortunately I can't seem to replicate this behaviour in the official CyberChef app: https://gchq.github.io/CyberChef/#recipe=JPath_expression('$.awslogs.data','%5C%5Cn')From_Base64('A-Za-z0-9%2B/%3D',true/disabled)Gunzip(/disabled)JPath_expression('$',''/disabled)Unescape_string(/disabled)&input=eyJhd3Nsb2dzIjp7ImRhdGEiOiJBQUEifX0

I'll close this for now.
