### ISSUE TITLE
Dropdown is shown beneath the recipe item below

### ISSUE THREAD

**Issue by dunielpls** [gchq/CyberChef#925]
**Describe the bug**
Dropdowns contained by an item in the recipe list are shown beneath the recipe item below as per the screenshot.

**To Reproduce**
1. Add "XOR" to recipe.
2. Add any item to the recipe below XOR.
3. Open the dropdown for "Key" type (e.g. click "HEX").

**Expected behaviour**
Expected the dropdown to show on top of the recipe item below the dropdown's parent item.

**Screenshots**
![image](https://user-images.githubusercontent.com/5176746/70839423-037aa980-1e0d-11ea-80c8-9e444f3d33e0.png)

**Desktop**
 - OS: Windows
 - Browser: Microsoft Edge Dev 80.0.355.1
 - CyberChef version: 9.11.14

**Proposed solution**
When a dropdown is activated by clicking its trigger, set the CSS attribute `z-index: 1` on its parent item (`#rec-list .operation`) in the recipe list and remove it again when the dropdown is closed.

**Comment by n1474335** [comment]
Unfortunately Microsoft Edge is not a supported browser. See here: https://github.com/gchq/CyberChef#browser-support

**Comment by dunielpls** [comment]
That was a quick dismissal - the new Microsoft Edge is based on Chromium.

I also tested this in Google Chrome just now, same host machine but Chrome version 79.0.3945.79 - the issue is present also there:
![Screenshot_19](https://user-images.githubusercontent.com/5176746/70910317-c9c5c080-200f-11ea-9f9f-281cc15f626f.png)

**Comment by n1474335** [comment]
Apologies, we'll take a look
