### ISSUE TITLE
Bug report: Blowfish does not support variable key sizes

### ISSUE THREAD

**Issue by rgov** [gchq/CyberChef#930]
**Describe the bug**
When I try to set a Blowfish key to a 15-byte string, I get: `Blowfish uses a key length of 8 bytes (64 bits).`

**To Reproduce**
Add a Blowfish node with a key that is not 8 bytes long.

**Expected behaviour**
It should work if the key is between 4 and 56 bytes long, according to Wikipedia.

**Comment by kevthehermit** [comment]
Bumping this as its still broken on current release and i can see a PR to fix has been written.

**Comment by komen205** [comment]
Bumping this.

**Comment by dru1d-foofus** [comment]
Bumping as well.
