### ISSUE TITLE
Bug report: Visual issue on input when selecting output

### ISSUE THREAD

**Issue by phil-ncsc** [gchq/CyberChef#937]
**Describe the bug**
When clicking or selecting any text in the output page when using Safari, the input text is visually duplicated with a vertical offset.

**To Reproduce**
Using Safari, add an operation and some input text. Then select some of the output and notice the distortion in the input box.
This issue does not appear in Chrome on the same CyberChef version.

**Expected behaviour**
No visual artefacts in the input box when selecting output

**Screenshots**
<img width="951" alt="image" src="https://user-images.githubusercontent.com/52707208/72357910-a9a72100-36e3-11ea-9233-7bf0a44672a2.png">
<img width="849" alt="image" src="https://user-images.githubusercontent.com/52707208/72357946-b75ca680-36e3-11ea-8fc8-9409db2daaa7.png">

**Desktop (if relevant, please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 13.0.4
 - CyberChef version: 9.12.0

**Comment by n1073645** [comment]
Unfortunately Safari is not a supported browser. See here: https://github.com/gchq/CyberChef#browser-support
