### ISSUE TITLE
http get only works on very limited number of sites

### ISSUE THREAD

**Issue by bertyboy** [gchq/CyberChef#941]
The description says -
Makes an HTTP request and returns the response. 
I've tried this on multiple sites, such as
https://www.bbc.co.uk/
https://www.virustotal.com/gui/home/search
https://github.com/
https://www.itv.com/

The only sites I could find that is worked on was:
https://neil-fox.github.io/
https://pages.github.com/

Any help much appreciated.

**Comment by retnikt** [comment]
This is not a bug. The error message reads:
```
TypeError: NetworkError when attempting to fetch resource.

This error could be caused by one of the following:
 - An invalid URL
 - Making a request to an insecure resource (HTTP) from a secure source (HTTPS)
 - Making a cross-origin request to a server which does not support CORS
```
We know that the URL is valid, and that both URLs are Secure Resources (HTTPS) so the problem is
> Making a cross-origin request to a server which does not support CORS

CORS is a security measure in modern browsers which prevents you from reading cross-site responses from servers which don't explicitly allow it.

**Comment by d98762625** [comment]
Closing as behaviour is explained.
