### ISSUE TITLE
Feature request: Add "Unique" option to the "Sort" operation

### ISSUE THREAD

**Issue by cnotin** [gchq/CyberChef#960]
**Summary**
The "Unique" and "Sort" operations are very similar to the Unix `uniq` and `sort` commands that are often used together.
The `sort` command commnly has a `-u` parameter to apply the "Unique" operation without having to pipe it to `uniq` which is a nice shortcut that I'm used to use now.

**Request**
I'd suggest to add a "Unique" option, off by default, to the Sort operation.

**Alternative**
The alternative is of course to chain the already available Sort and Unique operations

**Comment by cnotin** [comment]
If you like it I can propose an implementation!

**Comment by n1073645** [comment]
Unfortunately to implement the -u flag in the sort operation we would have to either duplicate code or have an inter-operation dependency (where we would call the uniq operation from inside of the sort operation) which is not ideal in either case. I would recommend sticking with piping the output of sort into unique.

**Comment by cnotin** [comment]
Ok then! Thx
