### ISSUE TITLE
Feature request: Extract Text from Image 

### ISSUE THREAD

**Issue by DDAZZA** [gchq/CyberChef#961]
**Problem**
Its common for people to take photographs of presentation slides or share screen shots that contain text.  It is timeconsuming to type these out.

**Suggested behaviour**
Open image file as Input.
Select Operation 'Extract Text from Image' 
View text in Ouput

**Additional features**
Further feature exhancements may be able to detect formats e.g. tables and convert to somthing like CSV format.

**Alternatives**
There are free online alternatives, however these commonly have an overwheleming amount of adverts and/or retain your information.

**Comment by n1073645** [comment]
There is an operation called Optical Character Recognition(OCR) that extracts text from images already implemented in CyberChef. Does this do what you need? [https://gchq.github.io/CyberChef/#recipe=Optical_Character_Recognition(true)](url)

**Comment by DDAZZA** [comment]
@n1073645 yes, thanks!
