### ISSUE TITLE
Operation request: Converting Decimal Numbers into Hex Numbers

### ISSUE THREAD

**Issue by shaihu** [gchq/CyberChef#962]
## Summary
The existing 'To Hex' recipe doesn't seem to be handling the conversion of numbers correctly

### Example Input

0895751945

### Example Output

35641709

Thanks in advance!

**Comment by n1073645** [comment]
The "To Hex" operation operates on bytes. To convert a number like "0895751945" you need to select the "To Base" operation. e.g. [https://gchq.github.io/CyberChef/#recipe=To_Base(16)&input=MDg5NTc1MTk0NQ](url)

**Comment by shaihu** [comment]
That helps - thanks!
