### ISSUE TITLE
Operation request: Luhn algorithm

### ISSUE THREAD

**Issue by shaihu** [gchq/CyberChef#963]
## Summary

Calculate a checksum using the Luhn algorithm

### Example Input

35245709116975

### Example Output

7

Thanks in advance!

**Comment by n1073645** [comment]
Please could you link an example implementation/specification because this online tool [https://www.dcode.fr/luhn-algorithm/](url) when run on your input does not produce 7.

**Comment by shaihu** [comment]
sorry, missed one digit.
The input should have been 35641709012469

I use https://planetcalc.com/2464/

**Comment by n1474335** [comment]
Implemented in v9.14.0

**Comment by shaihu** [comment]
Thank you!!!
