### ISSUE TITLE
Bug report: Regex with email builtin regex is wrong 

### ISSUE THREAD

**Issue by AlessandroPerucchi** [gchq/CyberChef#964]
**Describe the bug**
The regex recipe for detecting email is simply wrong, it doesn't follow the officials RFC.
https://en.wikipedia.org/wiki/Email_address

**To Reproduce**
1. Get Regular Expression
2. Choose the Email builtin regex
3. Write in the input field, an email, like "alex+john@example.com"
4. In the output field, only "john@example.com" is highlighted

**Expected behaviour**
I expect that the highlight is on "alex+john@example.com".

**Desktop (if relevant, please complete the following information):**
 - CyberChef version: [e.g. 9.13.1]

**Additional context**
To correct my '+' problem the email builtin regex could be change to :
\b(\w[-+.\w]*)@([-\w]+(?:\.[-\w]+)*)\.([A-Za-z]{2,4})\b
But this is not a correct handling on all the case of detection of good and wrong email format.

**Comment by n1073645** [comment]
It is quite difficult to write a regex that matches on every possible valid email address. I agree that there is room for improvement on this one and I will take a look.
