### ISSUE TITLE
Feature request: High Res CyberChef Logo Request

### ISSUE THREAD

**Issue by mattnotmax** [gchq/CyberChef#969]
**Is your feature request related to a problem? Please describe.**
Cyberchef is cool. What's cooler? Cyberchef stickers. But there are no high res images of CyberChef to make stickers

**Describe the solution you'd like**
A vector or high res image of our favourite Chef

**Describe alternatives you've considered**
The current images available are too low-res to make quality stickers

**Additional context**
None. Cyberchef is great. I just want to spread the word.

**Comment by mattnotmitt** [comment]
I've been sent some stickers in the past with good quality vectors so I
expect they have them somewhere!

**Comment by n1474335** [comment]
We certainly do. I'll look into adding them to the repository.

**Comment by n1474335** [comment]
Various versions of the logo have been added here in SVG and PNG formats: https://github.com/gchq/CyberChef/tree/master/src/web/static/images/logo
