### ISSUE TITLE
Misc: Firefox issue

### ISSUE THREAD

**Issue by jakehemmerle** [gchq/CyberChef#970]
I set it up with Traefik and Let's Encrypt. This is the first time using the image in a while. Not sure why this is happening. It is running on a subdomain with a wildcard cert.

SecurityError: The operation is insecure.
Filename: webpack:///./src/web/RecipeWaiter.mjs?
Line: 510
Error: SecurityError: The operation is insecure.
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0
CyberChef version: 8.22.0

**Comment by n1474335** [comment]
I'm not able to recreate this. Is anyone else facing this problem?

**Comment by jakehemmerle** [comment]
Problem fixed itself. Not sure what the deal is.
