### ISSUE TITLE
Bug report: Incorrect Luhn Checksum

### ISSUE THREAD

**Issue by shaihu** [gchq/CyberChef#971]
**Describe the bug**
Checksum for 35726908971331 lists as 6.
based on the explanation from https://en.wikipedia.org/wiki/Luhn_algorithm is should be 7

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Search for Luhn under 'Operations'
2. Choose Luhn Checksum
3. paste 35726908971331 into input

**Expected behaviour**
Output = 7

Chrome on Windows 10

**Comment by n1073645** [comment]
The Luhn Checksum Mod 10 is 6 in this case.
The next Check Digit would be 7.

**Comment by shaihu** [comment]
Thanks for the explanation!
Is there a way to get the check digit?

**Comment by n1474335** [comment]
Fix merged

**Comment by shaihu** [comment]
Excellent.
Thanks so much!!!
