### ISSUE TITLE
Bug report: Possible bug in Lorenz SZ40 advance

### ISSUE THREAD

**Issue by oilulio** [gchq/CyberChef#973]
For a Lorenz SZ40 the Psi wheels should only move when the 37-tooth motor wheel shows an 'x'.  That wheel moves if the 61-tooth motor wheel shows an x.  The 61-tooth wheel moves at each encryption.  These wheels have no other effect than advancing the Psi wheels.  
This is described in _Colossus_, by B Jack Copeland and is what the comments in the code (Lorenz.mjs) say.

From this it should follow that if every cam is set ('x') on the 37-tooth motor wheel, then the settings on the 61-tooth wheel are irrelevant.

This [counterexample](https://gchq.github.io/CyberChef/#recipe=Lorenz('SZ40','Custom',false,'Send','Plaintext','Plaintext','%2B/-/.',1,1,1,1,1,1,1,1,1,1,1,1,'..xx.....x.xx...xxxx.x......x..x..xx...x...','.......xxx....xx....xx..x.xx...xxx.x.......x..x','..........xxxx..xx.x.x...x.x...xx.xxxx..x.x.x..x...','..............xxx.xx..x.xxx..x.xxxx...x.x.x..xx.x..xx','..................x.x..x.x.x.x..x..x.x.x.xxxx..xxxx....x.x.','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx','....................................x........................','....................xxxx.........x.x..x..','x........x.x....x..xx...x..xx..','.......x.x..x.x..x...x.xx.x.x','x.......xxx...x..x.x.xx..x','.xx...xxx.xx...xx.....x')&input=SSBXQU5ERVJFRCBMT05FTFkgQVMgQSBDTE9VRCBUSEFUIEZMT0FUUyBPTiBISUdIIE9FUiBWQUxFUyBBTkQgSA) has every cam set on the 37, only one set on the 61, yet toggling that single cam radically changes the decryption.  Further, the cam is in the middle of the 61 wheel (i.e. not close to the active cam) yet changes the decryption from the beginning.

**Comment by oilulio** [comment]
And I'm fairly certain the problem is that the code (Lorenz.mjs) reads the arrays as M37 then M61 in the lines
            chosenSetting.M[1] = this.readLugs(lugm37);
            chosenSetting.M[2] = this.readLugs(lugm61);

But in INIT_PATTERNS had the arrays declared instead with 61 as array index 1 and 37 as array index 2..
        "M": {
            1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            2: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

That would explain why figures apparently in M61 affect M37.  Recommended solution : reverse the empty arrays in INIT_PATTERNS.

**Comment by VirtualColossus** [comment]
Hmm .. you're right and yes, appears the custom arrays are being loaded reversed! I'll work on amend and re-test.

**Comment by VirtualColossus** [comment]
Pull request has been entered that should fix this.

Example of working pin settings based on your Psi and Chi wheels for Gil Haywood's daffodil Tunny test on fixed code: [example](https://gchq.github.io/CyberChef/#recipe=Lorenz('SZ40','Custom',false,'Send','Plaintext','Plaintext','%2B/-/.',1,1,1,1,1,1,1,1,1,1,1,1,'..xx.....x.xx...xxxx.x......x..x..xx...x...','.......xxx....xx....xx..x.xx...xxx.x.......x..x','..........xxxx..xx.x.x...x.x...xx.xxxx..x.x.x..x...','..............xxx.xx..x.xxx..x.xxxx...x.x.x..xx.x..xx','..................x.x..x.x.x.x..x..x.x.x.xxxx..xxxx....x.x.','....................................x','........................................x....................','....................xxxx.........x.x..x..','x........x.x....x..xx...x..xx..','.......x.x..x.x..x...x.xx.x.x','x.......xxx...x..x.x.xx..x','.xx...xxx.xx...xx.....x')&input=SSBXQU5ERVJFRCBMT05FTFkgQVMgQSBDTE9VRCBUSEFUIEZMT0FUUyBPTiBISUdIIE9FUiBWQUxFUyBBTkQgSA)

It adds just the Chi plus null Psi initially until Chi wheel with 23 pins has fully rotated then shifts M37 once so Psi wheels then continue stepping adding new Psi values completing the text.

**Comment by n1474335** [comment]
Fix merged

**Comment by oilulio** [comment]
Thanks, yes - that's what I was looking to produce, as per https://oilulio.wordpress.com/2014/07/20/encrypting-to-known-text-with-tunny/
