### ISSUE TITLE
Bug report: Magic discovers a valid operation that fails when applied

### ISSUE THREAD

**Issue by cnotin** [gchq/CyberChef#988]
**Describe the bug**
I found a case where the magic operation automatically suggests an operation on my input. In the preview we clearly see that the base64 decode is good and would give a JPEG file ("JFIF" marker)
![image](https://user-images.githubusercontent.com/550823/77258894-e52f1000-6c7d-11ea-90bc-b7e81a4373c4.png)

But when I apply it, the whole recipe fails.
![image](https://user-images.githubusercontent.com/550823/77258984-8d44d900-6c7e-11ea-9067-cb736f28f345.png)

**To Reproduce**
1. Use latest version on https://gchq.github.io/CyberChef/
2. Load this input:
[input.txt](https://github.com/gchq/CyberChef/files/4366229/input.txt)
3. Notice the magic operation that appears, click to apply it

**Expected behaviour**
To see the decoded output like in the preview

**Additional context**
My input is, I admit, erroneous because it is composed of:
```
[1st valid base64 image]
[unrelated text]
[2nd valid base64 image]
```
My guess is that the magic only checks the first few input octets so it stays in the "1st valid base64 image" section so it can decode without issue. Whereas the recipe applies on the whole input and fails due to the garbage text in the middle.

I do not know the code enough to say if this guess is true but this behaviour disturbed me a moment (I recreated the input file but in my case I had 2 large images and I initially didn't see the text in middle)

**Comment by n1073645** [comment]
Magic takes a sample of the bytes from the start of the input, then matches against a regex. In this input's case the number of bytes taken is not large enough to detect the invalid base64 (the text in the middle). If you run the full Magic operation it will detect the error and not recommend the operation. 

The text in the middle makes the base64 invalid, even if you tick the `remove non-alphabet chars` option, meaning that it won't decode. 

For this specific input, you could fork on \n and then From Base64 as a work around.
[https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn','%5C%5Cn',false)From_Base64('A-Za-z0-9%2B/%3D',true)Merge()Extract_Files(true,false,false,false,false,false,false,true)](url)

**Comment by cnotin** [comment]
Thanks for your reply and the proposed workaround. I already fixed it myself by splitting in two inputs.
I just wanted to inform you about this issue if perhaps you have an idea to detect it and warn the user. But I haven't any so I'm fine if you close this too :)
