### ISSUE TITLE
Feature request: Load Recipe Option -> Add to Recipe to existing

### ISSUE THREAD

**Issue by mattnotmax** [gchq/CyberChef#990]
**Is your feature request related to a problem? Please describe.**
Some saved recipes are essentially 'post-processing'. E.g. you've de-obfuscated a script and are left with some output. You then want to apply another recipe to that output (for a simple example: extract URLs and defang). Currently you'd have to copy that back to the input and apply the saved recipe. This isn't good for workflow or for sharing scripts specific to the problem at hand. 

**Describe the solution you'd like**
In the load recipe option window an 'Add Recipe to existing...' which would add the saved recipe operations immediately below the last operation in the current window.

**Describe alternatives you've considered**
Alternatives are manual -> copy output to new Window or this one, and load the other recipe which wipes the current work done.

**Comment by n1073645** [comment]
Do you mean the same as #280

**Comment by mattnotmax** [comment]
Yes, that looks cool. Not sure if having an option in the recipe menu would be a workaround for any issues accessing local storage but #280 it would be way cooler. Please, as long as the final saved recipe would also include the 'function' to make share-ability possible. 

Happy if you want to close and continue there.
