### ISSUE TITLE
Operation request: CBOR encoding/decoding

### ISSUE THREAD

**Issue by Danh4** [gchq/CyberChef#991]
Operations to support encoding and decoding CBOR 

See https://tools.ietf.org/html/rfc7049

**Comment by equalsJeffH** [comment]
see also: https://tools.ietf.org/html/draft-ietf-cbor-7049bis

**Comment by p-** [comment]
This would be nice for decoding WebAuthn-related data.

**Comment by n1474335** [comment]
Closed in #999
