### ISSUE TITLE
Bug report: <Insert title here>

### ISSUE THREAD

**Issue by AV-IO** [gchq/CyberChef#997]
**Describe the bug**
No input or output is shown.

**To Reproduce**
1. Open App

**Expected behaviour**
Usable input and output boxes

**Additional context**
* Using Android App downloaded from play store
* Version: 9.20.2
* Compile time: 27/03/2020 14:26:40 UTC
* User-Agent:
Mozilla/5.0 (Linux; Android 10; ONEPLUS A6013 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.149 Mobile Safari/537.36
* [Link to reproduce](https://gchq.github.io/CyberChef/#input=null)

**Comment by mattnotmitt** [comment]
The app that you are talking about is not official and there is no support
for mobile browsers.

**Comment by AV-IO** [comment]
I'll close this myself, since it is not supported. Sorry about that
